### ISSUE TITLE
Deshacer lo hecho en 1.6.01.04 hotfix

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#1]
sE Realizo una modificacion  por  ajuste excecpional en Resumen movimientos y grabacion IF6002,  Fue para el mes de agosto por lo tanto deshacer .

**Comment by psarco-artear** [comment]
Se deshacen cambios por HotFix cierre de mes.
Se solicita paso a producción para pruebas y OK.

**Comment by rscocco** [comment]
ya están lo cambios deployados en Preproductivo de FILMOWEB

**Comment by vivikorz** [comment]
LO PROBARE

**Comment by rscocco** [comment]
Ya está implementado en productivo según GLPI  https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=44281
