### ISSUE TITLE
Titulos para Programar LA-LM-PE

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#10]
El subfile queda cargado con 15 registros por página, es necesario tener más registros por página e indicar cuántas "páginas" tiene la búsqueda.

**Comment by vivikorz** [comment]
Incluir además que incluya a posibildad de ordenar dentro del filtro seleccionado por fecha de ultima exhibicion

**Comment by psarco-artear** [comment]
Se agrega opción de para seleccionarla cantidad de registros que se pueden visualizar en el grid. 
Se agrega contador de página actual y total de páginas.
Pendiente ordenamiento para Ultima Exhibición.

**Comment by psarco-artear** [comment]
Para poder realizar el ordenamiento, se va a cambiar todo el evento load para poder cargar una sdt y poder manipular los datos desde alli.

**Comment by psarco-artear** [comment]
Se reprograma evento LOAD para poder seleccionar por fecha de ultima exhibición.
Se agrega flecha Ascendente/Descendente al lado del titulo de la columna correspondiente a la fecha para poder seleccionar el ordenamiento.

Modelo: FILMO
Objeto: HFCW14001 (UPD) 
              PFCW14001 (NEW)

**Comment by rscocco** [comment]
Ya esta disponible en Filmo ALFA 
Objetos :   
 HFCW14001
PFCW14001

**Comment by vivikorz** [comment]
Rechazo:
Todas las pruebas las hago en paralelo con producción dado que me copie los datos.
1) Pongo como seleccion el proveedor pol-ka (1457) y me trae muchos más titulos que los esperados. Por lo tanto accedo a la tabla de TN6001 para obtener el contrato y así seleccionarlo en CO6001 y me trae titulos que no son del proveedor POLKA POR EJEmplo el titulo ='LA1548' no está en ningún contrato de pol-ka y esto en produccion no sucede.
2) Como filtro pongo titulo en castellano que comience con "AL" y los trae pero en vez de ordenarlos por titulo castellano como está en producción los ordena por tipo de titulo y nro.de titulo (perdió el ordenamiento original de produccion)
3) El ordenamiento por fecha está bien pero si cambio de búsqueda por ejemplo Pedi titulo que comincen con T y luego ordeno por fecha lo ordena pero si luego pido titulos que empiecen con A me los comienza ordenando por fecha cuando en realidad deberia ordenarlos por titulo castellano tal como lo pido en el pto.2
4) Lo mismo sucede si la búsqueda fue por titulo original ordena por ttktpotit +mtkrnotit y debe ordenar por titulo original
5)   Si la búsqueda fue Genero perdio todo orden no me doy cuenta criterio de órden pero no es como el de produccion, se perdio

**Comment by psarco-artear** [comment]
Se coloca el ordenamiento como se encontraba anteriormente.
Se verifica y corrige la validación de los contratos.

Modelo: FILMO
Objeto: HFCW14001 (UPD)
             PFCW14001 (UPD)

**Comment by rscocco** [comment]
Se implementa en Filmo ALFA
Objeto: HFCW14001 , PFCW14001

**Comment by vivikorz** [comment]
Probado nuevamente proveedor polka, trae titulos que no son de contratos con proveedor polka, por ejemplo muestra 
LM010662 | LARA CROFT -LA CUNA DE LA VIDA

 SELECT *FROM filmo.TN6001 where mtknrotit =10662 and ttktpotit = 'LM';
select *from filmo.co6001 where cokcon  in (1743, 1745, 1749, 1788, 2094, 2349, 2121); 

LO MISMO SUCEDE MUESTRA LA 10179 Y PARA ESE TITULO CTO 785 NO TIENE EL PROVEEDOOR 1457

En produccion esa misma consulta de proveedor trae 4 registros en desa me esta mostrando 2 paginas y media de 100 o sea mas de 200 registros.

**Comment by rscocco** [comment]
Se implementa en Filmo ALFA
Objeto: HFCW14001 , PFCW14001

**Comment by vivikorz** [comment]
FIltro proveedor ok
FILTRO PROVEEDOR CON TITULO OK
FILTRO CALIFICACION OK
FILTRO DURACION OK
ORDENO POR FECHA OK
PIDO PASAJE A INTEGRACION

**Comment by rscocco** [comment]
Se implementa en Filmo INT
Objeto: HFCW14001 , PFCW14001

**Comment by vivikorz** [comment]
OK INTEGRACION
Probado siempre en paralelo con produccion
Señal M24 - Señal C13 y Señal CAA
Filtros de proveedor, duracion, titulo. Orden correcto. Visualizacion de páginas correcto.
Orden de fecha de exhibicion correcto tanto ascendente como descendente. Pido pasaje a preprod cuando esté todo el release

**Comment by rscocco** [comment]
Se implementa en Filmo Preprod
Objeto: HFCW14001 , PFCW14001

**Comment by vivikorz** [comment]
ok preprod. SE pasara con el proximo deployed

**Comment by rscocco** [comment]
Se implementa en servidores Gxprod el proyecto Filmo.war.

Según solicitud:    https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52333
