### ISSUE TITLE
Consulta titulo para programar SE MS 

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#11]
El subfile queda cargado con 15 registros por página, es necesario tener más registros por página e indicar cuántas "páginas" tiene la búsqueda.

**Comment by psarco-artear** [comment]
Se agrega opcion para seleccionar cantidad de registros por pagina
Se modifica el indicador de pagina mostrando página n de x

Modelo: FILMO
Objeto: HFCW13001 (UPD)

**Comment by rscocco** [comment]
Ya esta disponible en Filmo Alfa 
Objeto: HFCW13001

**Comment by vivikorz** [comment]
Probado filtro titulo castellano y filtro titulo origianal, se ve paginado.
Puedo elegir si veo de 15 o 50  o 100
ok desarrollo se pasara a int con todo el release

**Comment by rscocco** [comment]
Ya esta disponible en Filmo INT
Objeto: HFCW13001

**Comment by vivikorz** [comment]
Probado filtro titulo castellano y filtro titulo origianal, se ve paginado.
Puedo elegir si veo de 15 o 50 o 100
ok int se pasara a preprod con todo el release

**Comment by rscocco** [comment]
Ya esta disponible en Filmo Preprod
Objeto: HFCW13001

**Comment by vivikorz** [comment]
OK PREPROD
Se pasara a prod en el proximo deployed con todo el release

**Comment by rscocco** [comment]
Se implementa en servidores Gxprod el proyecto Filmo.war.

Según solicitud:    https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52333
