### ISSUE TITLE
Consulta Histórica de Titulos

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#12]
El subfile queda cargado con 15 registros por página, es necesario tener más registros por página e indicar cuántas "páginas" tiene la búsqueda.

**Comment by psarco-artear** [comment]
Se agrega opción de para seleccionarla cantidad de registros que se pueden visualizar en el grid.
Se agrega contador de página actual y total de páginas.
Modelo: FILMO
Objeto: HFCW11001 (UPD)

**Comment by rscocco** [comment]
Ya esta disponible en Filmo Alfa 
Objeto: HFCW11001

**Comment by vivikorz** [comment]
OK DESARROLLO. PASAR JUNTO CON OTROS ISSUES A INTEGRACION

**Comment by rscocco** [comment]
Ya esta disponible en Filmo INT
Objeto: HFCW11001

**Comment by vivikorz** [comment]
ok integracion probe por titulo castellano, por señal, por clave por original
Pido pasaje a preprod con todo el release

**Comment by rscocco** [comment]
Ya esta disponible en Filmo Preprod
Objeto: HFCW11001

**Comment by vivikorz** [comment]
ok preprod se pasara a prod con el proximo deployed

**Comment by rscocco** [comment]
Se implementa en servidores Gxprod el proyecto Filmo.war.

Según solicitud:    https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52333
