### ISSUE TITLE
Consulta de Contratos

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#13]
El subfile queda cargado con 15 registros por página, es necesario tener más registros por página e indicar cuántas "páginas" tiene la búsqueda.

**Comment by psarco-artear** [comment]
Se agrega opción de para seleccionarla cantidad de registros que se pueden visualizar en el grid.
Se agrega contador de página actual y total de páginas.
Modelo: FILMO
Objeto: HFCW15001 (UPD)

**Comment by rscocco** [comment]
ya esta en FIlmo  ALFA

Objeto: HFCW15001

**Comment by vivikorz** [comment]
Probado  en desarrollo con proveedro POLKA y comparado con Produccion mostró 7 paginas de 15 cada una.
Luego puse que muestre 100 y me mostro una sola página correcto.
Puse un contrato en especial y lo mostro
Ok desa. Pasar a int

**Comment by rscocco** [comment]
ya esta en FIlmo INT

Objeto: HFCW15001

**Comment by vivikorz** [comment]
Probado con proveedor POLKA TANTO para C13, CVR y M24 OK comparado con produccion ok
Seleccionado el contrato 2307 ok comparado con prod.
Pido pasaje a preprod junto con todo el release

**Comment by rscocco** [comment]
ya esta en FIlmo Preprod

Objeto: HFCW15001

**Comment by vivikorz** [comment]
ok preprod 
Probado x proveedor y x contrato comparado con produccion
se pasara en el proximo deployed
