### ISSUE TITLE
Consulta Ingreso Devolucion

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#14]
El subfile queda cargado con 15 registros por página, es necesario tener más registros por página e indicar cuántas "páginas" tiene la búsqueda.

**Comment by psarco-artear** [comment]
Se agrega opción de para seleccionarla cantidad de registros que se pueden visualizar en el grid.
Se agrega contador de página actual y total de páginas.
Modelo: FILMO
Objeto: HFCW16001 (UPD)

**Comment by rscocco** [comment]
Ya esta en filmo alfa 

Objeto: HFCW16001

**Comment by vivikorz** [comment]
Probado filtro de titulo castellano "LOS A" ok
Probado con clave ok
Probado titulo original TO y ok
En todos los casos controlé cantidad de paginas comparados con prod
Pido pasaje a int

**Comment by rscocco** [comment]
Ya esta en filmo INT

Objeto: HFCW16001

**Comment by vivikorz** [comment]
Probado filtro de titulo castellano "mujeres" ok
Probado con clave ok
Probado titulo original  ok
Pido pasaje a preprod

**Comment by rscocco** [comment]
Ya esta en filmo Preprod

Objeto: HFCW16001

**Comment by vivikorz** [comment]
ok preprod se probo con la familia ingals y el zorro comparando con prod.
Se pasara a prod con el siguiente deployed

**Comment by rscocco** [comment]
Se implementa en servidores Gxprod el proyecto Filmo.war.

Según solicitud:    https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52333
