### ISSUE TITLE
Consulta Reporte Trasmision

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#15]
El subfile queda cargado con 15 registros por página, es necesario tener más registros por página e indicar cuántas "páginas" tiene la búsqueda.

**Comment by psarco-artear** [comment]
Se agrega opción de para seleccionarla cantidad de registros que se pueden visualizar en el grid.
Se agrega contador de página actual y total de páginas.
Modelo: FILMO
Objeto: HFCW17001 (UPD)

**Comment by rscocco** [comment]
Ya esta disponible en Filmo Alfa

**Comment by vivikorz** [comment]
Probado para la señal canal 13 dia 2/1/2021 y para M24 día 12/1/2021
Comparado con produccion. Se ven iguales y en desa se ve la opcion de cantidad de registros y total de páginas. ok
Pido pasaje a int

**Comment by rscocco** [comment]
Ya esta disponible en Filmo INT
Objeto: HFCW17001

**Comment by vivikorz** [comment]
Probado en integracion se ve opcion de elegir cantidad de registros a mostrar
Pido dia 13/12/2020 y es correcto.
Pido pasaje a preprod con todo release

**Comment by rscocco** [comment]
Ya esta disponible en Filmo Preprod
Objeto: HFCW17001

**Comment by vivikorz** [comment]
ok preprod se probo con el 12/2/2021 y comparado con prod
Se pasara a prod con el ultimo deployed

**Comment by rscocco** [comment]
Se implementa en servidores Gxprod el proyecto Filmo.war.

Según solicitud:    https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52333
