### ISSUE TITLE
Modificar  Rutina General ChequearMaterialRecibido

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#18]
No debe considerar igual proveedor si lo encuentra y es proveedor diferente tambien lo dara por recibido pero adicionando tambien registro en RM RT6001 CON otro idremito y el proveedor que tenga desde el contrato.
Para ello modifiqué la especificacion de la rutina 
Esta rutina es llamada desde alta de contrato y modificacion de contrato

**Comment by vilinares** [comment]
Necesito que se haga una prueba con la aplicación para ver que procesos intervienen, porque no me concuerda lo que esta en el procedimiento con la especificación.

**Comment by vilinares** [comment]
Se realizo una modificación en el proceso para realizar una prueba sin quitar el parámetro, solo modificando el query para que no lo tome en cuenta. Eso para no tener que modificar todos los procesos que llaman a este procedimiento

**Comment by vivikorz** [comment]
Cargado contrato para proveedor Korz  señal canal 13 repeticion con la titulo el zorro (SE13899) que se encuentra recibido para otro proveedor arroja el siguiente error:
ERROR
java.sql.SQLException: ORA-20001: ORA-20001: ORA-00001: unique constraint (FILMO.PK_TP6001) violated ORA-06512: at "FILMO.FIL_PKG_ALTA_CONTRATOS_2", line 1996 ORA-06512: at line 1
Se puede ver la rutina : PR_14CONF
que arroja el siguiente error: 
PK TP6001 (p_contrato = 2383 - p_grupo = 1 - p_senial = C13 - p_clave = SE001389 - p_capitulo = 1 - p_parte = 0)

**Comment by vivikorz** [comment]
Al validar que el titulo para diferente proveedor existe debe incluir el proceso clonador que ya fue realizado para correr de manera separada, esa seria la rutina a ejecutar

Pl clonador

DECLARE
-- Variable declarations
l_P_TIPOTIT CHAR (2);
l_P_NROTIT NUMBER;
l_P_CONTRATOV NUMBER;
l_P_GRUPOV NUMBER;
l_P_PROVEEDORV NUMBER;
l_P_CONTRATON NUMBER;
l_P_GRUPON NUMBER;
l_P_PROVEEDORN NUMBER;
BEGIN
-- Variable initializations
l_P_TIPOTIT := 'tipo titulo cargado x el usuario';
l_P_NROTIT := nrode titulo seleccionado por el usuario;
l_P_CONTRATOV := contrato donde se encontro viejo;
l_P_GRUPOV := grupo donde se encontro viejo;
l_P_PROVEEDORV := proveedor donde se encontro;
l_P_CONTRATON := contrato nuevo;
l_P_GRUPON := grupo nuevo;
l_P_PROVEEDORN := proveedor nuevo;

-- Call
FILMO.PR_CLONAR_REMITOS (P_TIPOTIT      => l_P_TIPOTIT,
                         P_NROTIT       => l_P_NROTIT,
                         P_CONTRATOV    => l_P_CONTRATOV,
                         P_GRUPOV       => l_P_GRUPOV,
                         P_PROVEEDORV   => l_P_PROVEEDORV,
                         P_CONTRATON    => l_P_CONTRATON,
                         P_GRUPON       => l_P_GRUPON,
                         P_PROVEEDORN   => l_P_PROVEEDORN);

-- Transaction control
COMMIT;

END;

**Comment by vivikorz** [comment]
Se pedirá un proceso similar al clonador con un pto en menu. 
Un titulo repeticion sin recontratacion con diferente proveedor que se encuentra en el canal tanto desde alta d contrato como modificacion de contrato lo dejan a consultar y eso es correcto por definicion original del sistema.
Y como no hay manera de sacarle esa marca.
POR LO TANTO DESDE clonador hay que solucionarlo
Desde alta de contrato funciona da de alta a los titulos sus remitos y deja a consultar es error x que el remito es de otro proveedor.
Desde amodificacion deja a consultar y no adiciona en ningun lado
debo hacer un clonador que solucione ambos pasos y x afuera. 
Crearé un nuevo issue

**Comment by vivikorz** [comment]
cierro este issue será reemplazado x el 38 ya que se hara un pto de menu con seleccion de titulo y el usuario lo realizara independientemente de la carga de contrato
