### ISSUE TITLE
Cierre y precierre contable (fp400)

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#20]
Rutina gValidarMesCont
// Valida que el mes a procesar 
SI EN  IF6001 el ultimo id de interfez (if6001.ifkint) TIENE  IFFMRCOPE = 'S' 
tomar el  IFFMESCIE dónde  los primeros cuatro digitos sean   C01Año y los úitlimos 2 a C01Mes
Si  C01mes = 12 EL MES A VISUALIZAR PARA CERRAR SERÁ  01 Y AÑO A VISUALIZAR SERA c01año+1
Si C01MES <12 SÓLO SE SUMARÁ 1 A C01MES 

Si en  IF6001 el ultimo id de interfez (if6001.ifkint) tiene  IFFMRCOPE <>  'S' entonces
IFFMESCIE dónde  los primeros cuatro digitos sean   C01Año y los úitlimos 2 a C01Mes a procesar

**Comment by rscocco** [comment]
Ya esta disponible en FILMO de **Integracion**,  con su ok se replicara en ALFA

Objeto modificado :   FP45001

**Comment by vivikorz** [comment]
Probado en integracion mes 01/2021 precierre anduvo ok, pude seleccionar.
Hice ok operativo y ahi agrego el registro en if6001.
Hice cierre definitivo y actualzió la marca de interfaz en N que no estaba hecha
Hice interfaz a sap actualizo marca
Volví a hacer precierre de 01/2021 y detecto que ya habia cerrado
Volvi a pulsar cierre definitivo 01/2021 y detecto que ya estaba cerrado por lo tanto ok prueba en integracion
Pasarlo a desarrollo para realizar otra prueba. Gracias

**Comment by rscocco** [comment]
Ya está implementado en Filmo ALFA

**Comment by vivikorz** [comment]
Probado en desarrollo aproveché y corri tambien el proceso de copia que era un arreglo. Mes 01/2021 precierre anduvo ok, pude seleccionar.
Hice ok operativo y ahi agrego el registro en if6001.

**Comment by vivikorz** [comment]
Hice cierre definitivo y actualzió la marca de interfaz en N que no estaba hecha

**Comment by vivikorz** [comment]
Hice interfaz a sap actualizo marca

**Comment by vivikorz** [comment]
hago precierre febrero no debe haber movimientos pero es correcto que me permita hacerlo

**Comment by vivikorz** [comment]
actualizo marcas correctamente. Hice cierre de febrero y dejo hacer eso es correcto. No hay datos pero el mes pude seleccionar.
Doy por terminada la prueba en desa

**Comment by vivikorz** [comment]
Probado en desa mes 01/2021 precierre anduvo ok, pude seleccionar.

Hice ok operativo y ahi agrego el registro en if6001.

Hice cierre definitivo y actualzió la marca de interfaz en N que no estaba hecha

Hice interfaz a sap actualizo marca

HICE precierre de 02/2021 y OBVIO POR NO TENER DATOS SALIO EN BCO LOS REPORTES PERO EN LOS TITULOS PONIA FEBRERO
por favor pasar a preprod. quedaria sin efecto el toque sucio del otro dia

**Comment by rscocco** [comment]
Ya esta implementado en Filmo preprod

**Comment by vivikorz** [comment]
Preprod. Hice un precierre de febrero. Obvio salio mensaje correcto avisandome que no cerré Enero, mensaje correcto.
Se ven mas meses además de enero. Añoi 2021 ok

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=51959

**Comment by rscocco** [comment]
Se implemento en servidores Gxproductivos el proyecto Filmo.war

según solicitud :   https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=51959
