### ISSUE TITLE
Copia datos de produccion a esquemas de Pruebas

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#21]
Hoy por hoy se ejecuta 
BEGIN
pr_copia_datos_produccion('FILMO');
END;
Necesito agregar en ese pl las nuevas tablas de costeo.
Por lo que vi selecciona tablas que terminen en 6001 6002 y 6003 hay que agregarle las siguientes:

Truncate table GRILLA_COSTEO_POR_RATING;
INSERT INTO GRILLA_COSTEO_POR_RATING SELECT * FROM FILMO.GRILLA_COSTEO_POR_RATING@DB_PROD;

Truncate table GRILLA_COSTEOPOREXC;
INSERT INTO GRILLA_COSTEOPOREXC SELECT * FROM FILMO.GRILLA_COSTEOPOREXC@DB_PROD;

Truncate table HIST_GRILLA_COSTEOPOREXC;
INSERT INTO HIST_GRILLA_COSTEOPOREXC SELECT * FROM FILMO.HIST_GRILLA_COSTEOPOREXC@DB_PROD;

Truncate table HIST_GRILLA_COSTEOPORRATING;
INSERT INTO HIST_GRILLA_COSTEOPORRATING SELECT * FROM FILMO.HIST_GRILLA_COSTEOPORRATING@DB_PROD;

Truncate table HIST_TITULO_EXCEDENTE;
INSERT INTO  HIST_TITULO_EXCEDENTE SELECT *FROM FILMO.HIST_TITULO_EXCEDENTE@DB_PROD;

Truncate table HIST_TITULO_RATING;
INSERT INTO  HIST_TITULO_RATING SELECT *FROM FILMO.HIST_TITULO_RATING@DB_PROD;

Truncate table HIST_TITULOCFM;
INSERT INTO  HIST_TITULOCFM SELECT *FROM FILMO.HIST_TITULOCFM@DB_PROD;
           
Truncate table TITULOCFM;
INSERT INTO TITULOCFM SELECT *FROM FILMO.TITULOCFM@DB_PROD;

Truncate table TITULOEXCEDENTE;
INSERT INTO TITULOEXCEDENTE SELECT *FROM FILMO.TITULOEXCEDENTE@DB_PROD;

Truncate table TITULORATING;
INSERT INTO TITULORATING SELECT *FROM FILMO.TITULORATING@DB_PROD;

**Comment by vilinares** [comment]
Se realizaron los ajustes solicitados en Ambiente de Desarrollo tanto en el proceso pr_copia_datos_produccion como en el proceso pr_copia_datos_test, este ultimo se encuentra dentro del primero y verifica que se hayan copiado los datos

**Comment by vivikorz** [comment]
Ejecutado en desarrollo
BEGIN
pr_copia_datos_produccion('FILMO');
END;

Pude ver que copio en desa la tabla titulocfm y su histórico con el contrato cargado en produccion.
Las nuevas tablas de exc y rat no tienen mov.
Esta en desa el cto2373 de M24.
OK DESARRROLLO PIDO PASAJE A INTEGRACIOIN

**Comment by vilinares** [comment]
Se realizo pasaje a Integración

**Comment by vivikorz** [comment]
por favor pasar a preprod. Gracias

**Comment by vilinares** [comment]
Se realizo pasaje a Preprod. Como este issue no pasa a Producción, no se crea TAG. Solo replicamos las modificaciones en el ambiente de Preprod y se dejaron en el repositorio los procesos modificados

**Comment by vivikorz** [comment]
Probando en preprod.

 BEGIN

pr_copia_datos_produccion('FILMO');

END;


Como ya tenia los datos copiados borre un registro de la tabla TITULOCFM y si copia bien debo tener 3 registros no 2 como dejé.

**Comment by vivikorz** [comment]
Probado en preprod. Copio correcto y la prueba cental fue con la tabla TITULOCFM que antes no estaba en PL y ahora se agregó. Yo la dejé con 2 registros y en prod habia 3 copio y dejó 3 o sea correcto.
Cierro tarea, este pl no se pasa a prod ya que es para copia de datos de produccion a esquema de prueba.
