### ISSUE TITLE
CLONADOR

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#22]
PL para clonar remitos a partir de parametros ingresados

**Comment by vivikorz** [comment]
el documento esta en https://apps.canal13.artear.com.ar/share/page/site/Artear/documentlibrary#filter=path%7C/Proyectos/Filmo/Ingreso%2520de%2520Materiales&page=1

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/share/page/site/Artear/documentlibrary#filter=path%7C/Proyectos/Filmo/Ingreso%2520de%2520Materiales&page=1

**Comment by vivikorz** [comment]
Para probar tomar como datos viejos CONTRATO = 2038 grupo 1 "SE1389" proveedo 350774 
Como parametro contrato nuevo 2376 SE1389 PROVEEDOR 38563 
O sea se debe calcular el nuevo id de remtio (rutina hecha en material recibido) y  los remitos que encuentra para el viejo remito clonarlos pero con el nuevo id y nuevo contrato grupo
Ademas adicionar fichas de chequeos iguales a las existentes pero referenciar al nuevo id de remtio

**Comment by vilinares** [comment]
Se realizo procedure nuevo para la clonación, con el nombre PR_CLONAR_REMITOS. El mismo deja traza en LOG_PROCESOS para ver si su ejecución fue correcta o da algún error.

Para ejecutarlo se llama de la siguiente manera:

DECLARE
    -- Variable declarations
    l_P_TIPOTIT      CHAR (2);
    l_P_NROTIT       NUMBER;
    l_P_CONTRATOV    NUMBER;
    l_P_GRUPOV       NUMBER;
    l_P_PROVEEDORV   NUMBER;
    l_P_CONTRATON    NUMBER;
    l_P_GRUPON       NUMBER;
    l_P_PROVEEDORN   NUMBER;
BEGIN
    -- Variable initializations
    l_P_TIPOTIT := 'SE';
    l_P_NROTIT := 1389;
    l_P_CONTRATOV := 2038;
    l_P_GRUPOV := 1;
    l_P_PROVEEDORV := 350774;
    l_P_CONTRATON := 2376;
    l_P_GRUPON := 1;
    l_P_PROVEEDORN := 38563;

    -- Call
    FILMO.PR_CLONAR_REMITOS (P_TIPOTIT      => l_P_TIPOTIT,
                             P_NROTIT       => l_P_NROTIT,
                             P_CONTRATOV    => l_P_CONTRATOV,
                             P_GRUPOV       => l_P_GRUPOV,
                             P_PROVEEDORV   => l_P_PROVEEDORV,
                             P_CONTRATON    => l_P_CONTRATON,
                             P_GRUPON       => l_P_GRUPON,
                             P_PROVEEDORN   => l_P_PROVEEDORN);

    -- Transaction control
    COMMIT;
END;

**Comment by vivikorz** [comment]
Clonador probado perfecto.

**Comment by vivikorz** [comment]
por favor pasar a integracion

**Comment by vilinares** [comment]
Se realizo pasaje a Integración

**Comment by vivikorz** [comment]
Probado precierre luego de corrido el clonadaor y los totales de canal 13 dan correctos
Corro cierre definitivo para ver movimientos en pp6003/6002/6001

**Comment by vivikorz** [comment]
Corrido cierre definitivo en integracion y clonado dejo todo bien y los reportes y movimientos estan correctos.

Pido pasaje a preprod

**Comment by vilinares** [comment]
Se creo TAG_FILMO_20210225_1-7-HOTFIX_PL para su pasaje a Preprod

**Comment by rscocco** [comment]
Se implementa en la base preproductiva los documentos descargados de :    **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-02-25)%20-%20%2322**
y registrado con el tag pl:    TAG_FILMO_20210225_1-7-HOTFIX_PL

Detalle de ejecución :   
Procedure PR_CLONAR_REMITOS compilado

**Comment by rscocco** [comment]
El DBA  implementa en la base productiva los documentos descargados de : https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-02-25)%20-%20%2322
y registrado con el tag pl: TAG_FILMO_20210225_1-7-HOTFIX_PL

Segun solicitud:    https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52234
