### ISSUE TITLE
implementacion Filmoteca 1.7 HotFix Clonador Remitos

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#23]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52234

**Comment by rscocco** [comment]
El DBA  implementa en la base productiva los documentos descargados de : https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-02-25)%20-%20%2322
y registrado con el tag pl: TAG_FILMO_20210225_1-7-HOTFIX_PL

Segun solicitud:    https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52234
