### ISSUE TITLE
Reporte de exhibciones x CICLO (400B2)

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#24]
RFP400B2 exhibidos x ciclo el caso de la Jaula de la moda ES UN titulo cuya cabecera dice canje y sus capitulos o sea los que esta informado en TituloCOSTEO DICE   CASH
Este Reporte debe mostrar el tipo de costeo de la cabecera del contrato tal como fue siempre (atributo CO6001.COMCANJE

**Comment by axel-miller** [comment]
Actualizando modelo de filmoteca
Verificando funcionamiento en local con los datos recien copiados

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Ya esta disponible en FIlmo alfa

**Comment by vivikorz** [comment]
ok desa pasar a int

**Comment by rscocco** [comment]
ya esta disponible en Filmo int

**Comment by vivikorz** [comment]
ok integracion por favor pasar a preprod. gracias

**Comment by rscocco** [comment]
ya esta disponible en preprod

**Comment by vivikorz** [comment]
solucionado en preprod pido pasaje a prod

**Comment by rscocco** [comment]
Se mplemento en servidores gcproductivos el proyecto **Filmoweb.war**  según solicitud :    **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52319**
