### ISSUE TITLE
Arreglo de Reportes Cierre Precierre

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#27]
RFP40075    Listado de Baja / Modificación de Contratos Fílmicos
 RFP40083    Listado de Baja / Modificación de Fílmicos Recibidos 
RFP400K1    Listado de Baja / Modificación de Fílmicos Recibidos perp 
RFP40067    Listado de Nuevos Contratos
 RFP400J9    Listado de Nuevos Contratos Señal: Titulos Perpetuos
 RFP40089    Listado de Fílmicos por Recibir 
RFP40068    Listado de Fílmicos Recibidos
RFP400K3    Listado de Fílmicos Recibidos Titulos Perpetuos 
RFP40078    Listado de Fílmicos Activados luego de Vencidos Sin Exhibir Señal
 RFP400a5    Listado de Fílmicos Exhibidos por Ciclo Sin Amortización - 
RFP400B2    Listado de Fílmicos Exhibidos por Ciclo -
 RFP40086    Listado de Fílmicos Exhibidos por Contrato/Proveedor 
RFP40092    Listado de Fílmicos por Exhibir
 RFP40042    Listado de Amortización de Fílmicos Sin Recepción-ExhibiciónSeñal 
RFP40076    Listado de Fílmicos Vencidos Sin Exhibir 
RFP400c4    Listado de Activación de Derechos Propios Por Ciclo 
RFP400K5    Listado de Amortización de Fílmicos Perpetuos
 RFP400K6    Listado de Baja / Modificación de Contratos Fílmicos perp
 RFP400b4    Listado de Cambios de Amortización 
RFP400a9    Listado Resumen de Fílmicos Exhibidos por Ciclo

  Tanto en el cierre contable como en precierre contable en los reportes del documento que anexo habrá que:  tomar el atributo    CO6001.Concanje se sumarizará según el atributo  de la cabecera

En sintesis deshacer lo realizado ne el mantis 12144

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Ya está disponible en FILMO ALFA

**Comment by vivikorz** [comment]
Reporte de alta de contrato:

Cargué contrato 2182 cuyo atributo COMCAMJE ES 'S' en el reporte sale como N, (RFP40067)  Axel por favor tomar la  correccion de lo desarrollado

**Comment by axel-miller** [comment]
para el reporte RFP40067 COMCAMJE se obtiene de
     For Each COkCon // CO6001
    Where COkCon      = &COkCon

**Comment by vivikorz** [comment]
axel en sintesis:los reportes mencionados aqui tinen que sacar ese atributo de CO6001 PERO LOS NUEVOS REPORTES LOS RFP400N01EE DEBE SACARLO DE TABLA TITULO EXCEDENTE (EXCANJE)
- RFP400N01ER  OBTENERLO DE TITULO RATING RACANJE)I-
-  RFP400N01EF OBTENERLO DE CFMCANJE MISMAS LOGICAS PARA 100503/4/5 QUE TRATAN DE LOS DE COSTEO
- GRACIAS

**Comment by axel-miller** [comment]
No entiendo

**Comment by vivikorz** [comment]
Hablando con Axel por telefono p aclarar nota

**Comment by vivikorz** [comment]
RFP40067 ok

**Comment by vivikorz** [comment]
[
[VKORZ_F100501_Filmicos_Exhibiciones_Excedente_Duracion_2021319_549848.pdf](https://github.com/SistemasArtear/Filmoteca/files/6171276/VKORZ_F100501_Filmicos_Exhibiciones_Excedente_Duracion_2021319_549848.pdf)
](url)

**Comment by vivikorz** [comment]
Axel corrido un precierre en desa 03/2021 y cto.2384 en TITULOEXCEDENTE ES CANJE NO y como veras en el reporte su sumatoria va a canje S

**Comment by axel-miller** [comment]
con los cambios en local
[
[MESCUDERO_F100501_Filmicos_Exhibiciones_Excedente_Duracion_2021319_557016.pdf](https://github.com/SistemasArtear/Filmoteca/files/6171554/MESCUDERO_F100501_Filmicos_Exhibiciones_Excedente_Duracion_2021319_557016.pdf)
](url)

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Se implementa en FilmoWEB  ALFA

Objetos modificados :  FP400B2 ,  FP40035f

**Comment by vivikorz** [comment]
Axel corrido un precierre en desa 03/2021 y cto.2384 en TITULOEXCEDENTE ES CANJE NO ahora sale bien

**Comment by vivikorz** [comment]
RFP400a9 ok resumen de exhibidos por cicolo

**Comment by vivikorz** [comment]
AXEL ESTARIA BIEN LO DE SEPARAR LOS CANJES Y LOS CASH TAL COMO LO PEDI PERO POR FAVOR FIJATE QUE ANULAMOS DOS EXHIBICIONES DE 400470 Y EN TOTAL SALE CORRECTO QUE ES CASH PERO PONE TOTAL 400473 Y DEBERIA SER 800946.
Eso solo el resto de cash y canje se ve bien.
Con esto terminariamos el arreglo del issue. gracias

**Comment by vivikorz** [comment]
[
[VKORZ_F100506_Anulacion_Exhibicion_CFM_2021319_787892.pdf](https://github.com/SistemasArtear/Filmoteca/files/6173827/VKORZ_F100506_Anulacion_Exhibicion_CFM_2021319_787892.pdf)
](url)

**Comment by vivikorz** [comment]
Sintesis  de ERRORES issue:­ Queda revisar:
a)    Total canje y cash de los nuevos reportes de costeo:­ F100504 505 y 506­ F100501 502 503
b)    Titulo SE10854 RATING FECHAS EXHIBICION 2/3 Y 3/3 CANAL 13 CORRECTO   PERO NO SALIERON LAS DE M24 SE10853 DE 2/3  Y 3/3 POR FAVOR REVISAR YA  QUE NO SALEN LAS DE RATING DE M24.(QUIZAS SEA POR ALGUN ERROR AL CAMBIAR  DE SEÑAL)
c)  RFP400N01BF tiene dos anulaciones BF correcto pero por favor revisar que un BF es por 28/2 ese es correcto y otra del 31/1 y no sale correcto, pone ambas con 28/2

**Comment by axel-miller** [comment]
Se remiten cambios resolviendo
a) Total canje y cash de los nuevos reportes de costeo:­ F100504 505 y 506­ F100501 502 503

**Comment by rscocco** [comment]
Se implementa en FilmoWEB ALFA

Objetos modificados : FP400B2 , FP40035f, FP400N01

**Comment by vivikorz** [comment]
siguen sin salir exhibiciones por rating dE M24 SE10853 DE 2/3 Y 3/3 POR FAVOR

**Comment by vivikorz** [comment]
De este issue pido pasaje a integracion de los reportes siguientes que ya les di el ok y desprendo los que no andan y lo incorporo en el 31:
Pasar intgracion: 
RFP40075 Listado de Baja / Modificación de Contratos Fílmicos
RFP40083 Listado de Baja / Modificación de Fílmicos Recibidos
RFP400K1 Listado de Baja / Modificación de Fílmicos Recibidos perp
RFP40067 Listado de Nuevos Contratos
RFP400J9 Listado de Nuevos Contratos Señal: Titulos Perpetuos
RFP40089 Listado de Fílmicos por Recibir
RFP40068 Listado de Fílmicos Recibidos
RFP400K3 Listado de Fílmicos Recibidos Titulos Perpetuos
RFP40078 Listado de Fílmicos Activados luego de Vencidos Sin Exhibir Señal
RFP400a5 Listado de Fílmicos Exhibidos por Ciclo Sin Amortización -
RFP400B2 Listado de Fílmicos Exhibidos por Ciclo -
RFP40086 Listado de Fílmicos Exhibidos por Contrato/Proveedor
RFP40092 Listado de Fílmicos por Exhibir
RFP40042 Listado de Amortización de Fílmicos Sin Recepción-ExhibiciónSeñal
RFP40076 Listado de Fílmicos Vencidos Sin Exhibir
RFP400c4 Listado de Activación de Derechos Propios Por Ciclo
RFP400K5 Listado de Amortización de Fílmicos Perpetuos
RFP400K6 Listado de Baja / Modificación de Contratos Fílmicos perp
RFP400b4 Listado de Cambios de Amortización
RFP400a9 Listado Resumen de Fílmicos Exhibidos por Ciclo

  Tanto en el cierre contable como en precierre contable en los reportes del documento que anexo habrá que: tomar el atributo CO6001.Concanje se sumarizará según el atributo de la cabecera

En sintesis deshacer lo realizado ne el mantis 12144

no iran en este issue los 100501/02/03/ 04/05/ 06 o sea se desprenden los de tipo de costeo EE EF ER Y SUS ANULACIONES O MODIFICACIONES
GRAACIAS

**Comment by vivikorz** [comment]
Por favor Axel indicale a Ricardo que espero en integracion. Gracias

**Comment by axel-miller** [comment]
Se remiten los objetos por correo

**Comment by rscocco** [comment]
Se consolida modificacion

**Comment by vivikorz** [comment]
Por favor Ricardo  necesito  en integracion los reportes mencionados en la nota anterior. gracias

**Comment by rscocco** [comment]
Se implementa en FilmoWEB INTEGRACION

Objetos modificados : FP400B2 , FP40035f,

**Comment by vivikorz** [comment]
RFP40067 Listado de Nuevos Contratos ok integracion

**Comment by vivikorz** [comment]
RFP40092 Listado de Fílmicos por Exhibir ok integracion (ok  2385 cabe  S TITU N Y 2384 CAB.S TITU N)

**Comment by vivikorz** [comment]
POR FAVOR PASAR TODO A PREPROD. GRACIAS

**Comment by rscocco** [comment]
Se implementa en FilmoWEB Preproduccion

Objetos modificados : FP400B2 , FP40035f,

**Comment by vivikorz** [comment]
Cargado el contrato 2383 mixto cabecera canje titulo no canje
Modificado el contrato 2378 cab.canje y titulo no canje
Recibido chequeado programado el titulo del contrato 2383 
De esta forma tengo varios reportes para generar

**Comment by vivikorz** [comment]
RFP40067 Listado de Nuevos Contratos ok preprod

**Comment by vivikorz** [comment]
se pasara este issue a produccion: https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52614

**Comment by rscocco** [comment]
Se implementa en productivo servidores gx  segun solicitud :  https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52614
