### ISSUE TITLE
BACKUP DIARIO Y MENSUAL

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#29]
No corrio

**Comment by vivikorz** [comment]
Virginia al correr el pl me da el siguiente error 
Informe de error -
ORA-20001: ORA-00001: restricción única (FILMO.SYS_C00228031) violada
ORA-06512: en "FILMO.PKG_FILMO_BACKUP", línea 10783
ORA-06512: en línea 2

**Comment by vivikorz** [comment]
probado en desarrolo solo 
BEGIN
pr_copia_datos_produccion('FILMO');
END;
esta ok

**Comment by vivikorz** [comment]
avanzara con todo el release

**Comment by vivikorz** [comment]
POR FAVOR Virginia preprara este issue para ir avanzando a integracion gracias

**Comment by vilinares** [comment]
Se realizo pasaje a Integración

**Comment by vivikorz** [comment]
Viginia para  ejecutarlo hice en integracion :
BEGIN
pr_copia_datos_produccion('FILMO');
END;

VEO las tablas de back-up febrero creadas pero no con datos adentro. Me podes indicar cual seria el error.
Recordar que se para esquemas de prueba es diferente a produccion x que en prod.deben crearse en esquema back que no tenemos y ahora se crean en filmo int

**Comment by vilinares** [comment]
Para hacer las pruebas de este proceso que se modifico se debe ejecutar de la siguiente manera:

begin
PKG_FILMO_BACKUP.PR_COPIA_MENSUAL('vkorz');
end;

**Comment by vivikorz** [comment]
Ejecutado para correr en entorno
 de prueba
babegin
PKG_FILMO_BACKUP.PR_COPIA_MENSUAL('vkorz');
SE crearon las tablas con datos ok.
Por favor preparar para preprod. gracias
end;

**Comment by vilinares** [comment]
Se crea TAG_FILMO_20210319_1-11-01_PL para su pasaje en Preprod.

Nota: El script 00 es solo para ejecutarse en Preprod así como lo indica su etiqueta, ya que en Prod esas tablas existen en el esquema FILMOBACKUP

**Comment by rscocco** [comment]
Se implementa en la Base Oracle preproductiva el documento descargado de :   **https://github.com/SistemasArtear/plsql/releases/tag/TAG_FILMO_20210319_1-11-01_PL**
Registrado con el TAG PL :  **TAG_FILMO_20210319_1-11-01_PL**

**Solo se ejecuta  El script 00** 
Detalle de ejecucion: 
Table PP6001_FEBRERO_PREVIO creado.
Table PP6002_FEBRERO_PREVIO creado.
Table PP6003_FEBRERO_PREVIO creado.
Table IF6001_FEBRERO_PREVIO creado.
Table IF6002_FEBRERO_PREVIO creado.
Table CO6001_FEBRERO_PREVIO creado.
Table CH6001_FEBRERO_PREVIO creado.
Table CS6001_FEBRERO_PREVIO creado.
Table ET6001_FEBRERO_PREVIO creado.
Table GC6001_FEBRERO_PREVIO creado.
Table GR6001_FEBRERO_PREVIO creado.
Table GT6001_FEBRERO_PREVIO creado.
Table HC6001_FEBRERO_PREVIO creado.
Table HF6001_FEBRERO_PREVIO creado.
Table HI6001_FEBRERO_PREVIO creado.
Table HN6001_FEBRERO_PREVIO creado.
Table HO6001_FEBRERO_PREVIO creado.
Table HP6001_FEBRERO_PREVIO creado.
Table HR6001_FEBRERO_PREVIO creado.
Table HS6001_FEBRERO_PREVIO creado.
Table HT6001_FEBRERO_PREVIO creado.
Table MT6001_FEBRERO_PREVIO creado.
Table OC6001_FEBRERO_PREVIO creado.
Table OP6001_FEBRERO_PREVIO creado.
Table OT6001_FEBRERO_PREVIO creado.
Table PH6001_FEBRERO_PREVIO creado.
Table PY6001_FEBRERO_PREVIO creado.
Table RC6001_FEBRERO_PREVIO creado.
Table RM6001_FEBRERO_PREVIO creado.
Table RT6001_FEBRERO_PREVIO creado.
Table SC6001_FEBRERO_PREVIO creado.
Table SH6001_FEBRERO_PREVIO creado.
Table SM6001_FEBRERO_PREVIO creado.
Table SS6001_FEBRERO_PREVIO creado.
Table ST6001_FEBRERO_PREVIO creado.
Table TJ6001_FEBRERO_PREVIO creado.
Table TL6001_FEBRERO_PREVIO creado.
Table TN6001_FEBRERO_PREVIO creado.
Table TO6001_FEBRERO_PREVIO creado.
Table TP6001_FEBRERO_PREVIO creado.
Table TS6001_FEBRERO_PREVIO creado.
Table US6001_FEBRERO_PREVIO creado.
Table GRILLA_COSTEOPOREXC_FEBRERO_PR creado.
Table GRILLA_COSTEO_POR_RATING_FEBRE creado.
Table HIST_TITULO_EXCEDENTE_FEBRERO_ creado.
Table HIST_TITULOCFM_FEBRERO_PREVIO creado.
Table HIST_TITULO_RATING_FEBRERO_PRE creado.
Table TITULOCFM_FEBRERO_PREVIO creado.
Table TITULOEXCEDENTE_FEBRERO_PREVIO creado.
Table TITULORATING_FEBRERO_PREVIO creado.
Table HIST_GRILLA_COSTEOPOREXC_FEBRE creado.
Table HIST_GRILLA_COSTEOPORRATIN_FEB creado.

**Comment by vivikorz** [comment]
Probado en preprod copia previa mensual. Anduvo ok.
begin
PKG_FILMO_BACKUP.PR_COPIA_MENSUAL('vkorz');
end;
Sino tengo todo release terminado igualmente pasaré este issue a prod.

**Comment by vivikorz** [comment]
Se pasara a produccion - https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52614

**Comment by rscocco** [comment]
El Dba Implementó en productivo segun solicitud :  https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52614
