### ISSUE TITLE
ACTIVAR TITULO VENCIDO (ERROR INESPERADO)

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#3]
Contrato 2221 titulo LM13082 SE encuentra en dos grupos.
Grupo 1 en standby = S y con costo 
Grupo 2 cancelado. 
Se intenta dar activar titulo vencido del contrato 2221 pero la aplicacion da error inesperado
Intuyo que no debe estar reconociendo el grupo al cual pertenece el titulo a activar y entonces arroja ese error.
Yo como prueba al grupo que esta cancelado lo hice "desaparecer" y luego entre a la aplicacion y pude extneder la vigencia.
Ademas otra duda es como distingue el atributo tnmstdby si solo pregunta por G o x S tambien. Ya que tambien me lo permitio  solo cuando este atributo paso a G

**Comment by vivikorz** [comment]
http://jbosspreprod.artear:8080/Filmo/#
Solapa trabajar con contrato: ACTIVAR TITULO VENCIDO
FIL_PKG_FP170	FN_VALIDA_CONTRATO_SELEC	Comenzar a procesar fn_valida_contrato_selec( Clave = LM013082 - Senial =  CAA - Id Contrato =  2221 )
FIL_PKG_FP170	PR_LISTA_CONTRA_TITULO	Fin a procesar pr_lista_contra_titulo( Clave = LM013082 - Senial =  CAA )
FIL_PKG_FP170	PR_LISTA_CONTRA_TITULO	Comenzar a procesar pr_lista_contra_titulo( Clave = LM013082 - Senial =  CAA )

**Comment by vivikorz** [comment]
Se ve claramente que no pone el grupo y el titulo esta en dos grupos

**Comment by bernardocamera** [comment]
Fue colocada una condición más en el select de la función FN_VALIDA_CONTRATO_SELEC, para que determine en forma unívoca en grupo al cual pertenece el conjunto Clave, Señal, Contrato)

**Comment by vivikorz** [comment]
Esta en prueba en desarrollo. Al parece rno necesito java Bernardo

**Comment by vivikorz** [comment]
Cargue probelma en el att, 136868. No funciona correctamente

**Comment by bernardocamera** [comment]
Fue realizada una modificación en la función que controla la historia contable, a fin de que se permita la activación del título vencido.

**Comment by vivikorz** [comment]
ok desarrollo pido pasaje a integracion

**Comment by bernardocamera** [comment]
Fue realizado el pasaje a Integración

**Comment by vivikorz** [comment]
ok prueba en integracion por favor pasar a  preprod, gracias

**Comment by bernardocamera** [comment]
Fue creado el TAG   TAG_FILMO_20200924_1-8_PL  @rscocco

**Comment by rscocco** [comment]
se implementa en la base oracle preproductiva el documento descargado de  : **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2020-09-24)%20-%20%233**    y registrado con el tag :  **TAG_FILMO_20200924_1-8_PL**

**Comment by vivikorz** [comment]
https://github.com/settings/security-log

**Comment by vivikorz** [comment]
ok prueba en preprod pediré pasaje a produccion

Probado el titulo Hugo LM13082 ANDUVO CORRECTO. HAY QUE SITUARSE EN LA SEÑAL DEL MENU.

Grabó en TN6001, HN6001 Y PY6001.

Lo probé desde activar titulo vencido y desde trabajar con titulos vigencias (sino me equivoco es la misma rutina) siempre trajo bien para modificar la fecha y grabo en TN HN Y PY

Además tome un titulo que estaba en gastos en pp6003 y tambien activo y grabó correctamente.

Además trabajé desde trabajar titulo y cambio de vigencia que es esa rutina y anduvo ok

**Comment by rscocco** [comment]
El Dba implementa  en la base oracle productiva el documento descargado de : https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2020-09-24)%20-%20%233 y registrado con el tag : TAG_FILMO_20200924_1-8_PL
  Según solicitud :    **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=44409**
