### ISSUE TITLE
P600 - Intefaz a Sap - Tipo de costeo

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#30]
El fp600 y tiene lo siguiente

If &Tiktpoimp <> 'CFM'   //SGP Req 11649 28/05/2019
                   Do 'GeneraPosicion'
                   IF &GeneraCabe ='S'
                        Do 'GuardaCabe'
                        &moviOk ='S'
                   Endif
               Endif                    //SGP Req 11649 28/05/2019

En el mantis 11649 se habia pedido:  modicar el asiento correspondiente a exhibicion de titulos de modo si el tipo de importe del titulo es 'CFM' no lo tenga en cuenta pra la generación del asiento. El tipo de importe se obtiene de la tabla GR6001 buscando por Contrato, Grupo, Señal del atributo Tiktpoimp 

Ese arreglo del mantis 11649 no deberia ir.

**Comment by axel-miller** [comment]
EL objeto en cuestion es el FP60007

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
ya esta en filmo alfa

**Comment by vivikorz** [comment]
Voy a tomar la ifz 216 de la tabla pp6003  y pondre a los mov. EF tipo de importe CFM como lo tenia originalmente y asi correr la ifz nuevamente y deberia interfacear los movimientos

**Comment by vivikorz** [comment]
Tomada la interfaz 216 (pp6003) y corregidos los contratos 2373 y 2378 le puse en tipo de importe CFM y a GR6001 TAMBIEN.
A la tabla if6001 le puse la marca de corrida interfaz en sap en N
Corri ifz de 02/2021 y se puede ver en sgva.ofcablote el FI015705 Correctamente. Pido pasaje a integracion.

**Comment by rscocco** [comment]
Se implementa en FIlmoWEB  de Integracion.

Objetos modificados :  FP400B2, FP40035f ,  FP400N01.

**Comment by rscocco** [comment]
Ya está Disponible en FIlmoWeb Integracion  

EL objeto Modificado FP60007

**Comment by vivikorz** [comment]
Copie datos de produccion en integración corri en integracion con la copia de produccion sin agregar ni quitar datos solo sacandole al IF6001 LA MARCA DE IFZ, volviendo a poner en tipo de importe al Mov.E cfm  y al MOV.EF CFM y además  poniendo que reproceso mes 02/2021 y lo del cfm lo hace bien pero no me pasa ninguna exhibicion
o sea las exhibiciones que corresponden por ejemplo al cto 2311 que son normales no las paso
por favor miralo, hice eso porque el cierre de febrero tenia si o si CFM en tipo de importe y para que interfacee le pusios FIJ pero en realidad era CFM y asi deberia pasar.
O sea el cfm anduvo bien pero no interfaceo a sap en integracion en el lote FI016516 o en FI016517 ninguna exhibicion de ninguna señal. Por favor miralo que es muy importante

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Ya está Disponible en FIlmoWeb ALFA
EL objeto Modificado FP60007

**Comment by vivikorz** [comment]
PROBADO EN DESARROLLO SE VEN  LAS EXHIBICIONES DE M24 CTO,2378 TANTO LAS DE COSTO FIJO (EF) COMO LAS COMUNES E, YA QQUE EL CONTATO ERA MIXTO.
Pido pasaje a integracion

**Comment by rscocco** [comment]
Ya está Disponible en FIlmoWeb Integracion

EL objeto Modificado FP60007

**Comment by vivikorz** [comment]
Ricardo por favor corrobora el pasaje porque no genero correctamente la tabla  en desa si. Gracias

**Comment by vivikorz** [comment]
PROBADO EN integracion el mes 02/2021 hecho paralelo en integracion con prod.Ya que no tengo todo lo que hice fue dejar en GR6001 EL TIPO de importe CFM y en pp6003 tambien.
No olvidar que para que anduviera en 02/2021 en prod tuvimos que cambiarlo a fij x que la aplicacion los CFM no interfaceaba.
Pido pasaje a
 preprod E VEN LAS EXHIBICIONES DE M24 CTO,2378 TANTO LAS DE COSTO FIJO (EF) COMO LAS COMUNES E, YA QQUE EL CONTATO ERA MIXTO.

**Comment by rscocco** [comment]
Se verifico y el objeto modificado esta en integracio,  a pedido de Axel se especifica con llamadores Forzado.-

**Comment by rscocco** [comment]
Ya está Disponible en FIlmoWeb Preproduccion

EL objeto Modificado FP60007

**Comment by vivikorz** [comment]
PORBANDO ISSUE 30 EN PREPROD

modifique marca en IF6001 DE INTERFACEDO NO

UPDATE "FILMO"."PP6003" SET PPKTPOIMP = 'CFM' WHERE PPKCON = 2373;

UPDATE "FILMO"."PP6003" SET PPKTPOIMP = 'CFM' WHERE PPKCON = 2378;

UPDATE "FILMO"."gr6001" SET PPKTPOIMP = 'CFM' WHERE cokCON = 2373;

UPDATE "FILMO"."gr6001" SET PPKTPOIMP = 'CFM' WHERE cokCON = 2378;

Esto se hace para dejar como fue originalmente las tablas y no salia en produccion estos registros

Para que fueran interfaceados se habia hecho en producion dejar tipo importe FIJ pero eran CFM

**Comment by vivikorz** [comment]
[ISSUE30 .txt](https://github.com/SistemasArtear/Filmoteca/files/6204227/ISSUE30.txt)
EN LA PRIMERA SOLAPA ES EL OFCABLOTE DE PREPROD Y EN LA SEGUNDA SOLAPA EL OFCABLOTE DE PRODUCCION Y COMPARE CANTIDAD DE REGISTROS

**Comment by vivikorz** [comment]
doy por finalizada la prueba se pasara a prod junto con el release o el lunes solo con el back up y se desprendera del resto

**Comment by vivikorz** [comment]
se pasara produccion en https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52614

**Comment by rscocco** [comment]
Se implementa en productivo servidores gx  segun solicitud :  https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52614
