### ISSUE TITLE
RFP400N01EF - ARTEAR

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#31]
Cargue un titulo SE10846 CUYAS FECHAS DE EXHIBICION SON LAS DETALLADAS A CONTINUACION.
ESTAS EXHIBICIONES SALENC ORRECTAMENTE EN EL REPORTE DE EXHIBIDOS PERO EN EL REPORTE DE COSTO FIJO MENSUAL DEBERIA HABER 1 EXHIBICION (EF) POR ENERO OTRA POR FEBRERO Y OTRA POR MARZO PORQUE SUS MOV.E que se generan son de esos meses, o sea si son de diferentes meses las Exhibicines de estos titulos debe generar 1 EF por cada mes y esta generando uno solo
Por favor revisar.   

SE010846  05/01/21 0.00 0.00 70.00C130014997 TE DOY LA VIDA
SE010846  01/03/21 0.00 0.00 0.00C130014997 TE DOY LA VIDA
SE010846 02/02/21

Si  esas tres exhibiciones fueran del mismo mes de exhibicion ahi si deberia ser un solo EF.

Cargue otro contrato fijo 2382 con SE10847 al igual que en el caso anterior tiene exhbiiciones e enero feberro y marzo y se pueden ver en los reportes de exhibiciones pero no salen estas tres exhbiciones en los reportes de CF debe salir un ef POR ENERO un EF febrero Y ef MARZO

**Comment by vivikorz** [comment]
Dice el CU QUE SI ENCUENTRA MOVIMIENTO DE E ( lo hay)  sale en el reporte de exhibiciones x tituto contrato 
 //Si Importe_costeo > 0 eso tambien existe en tabla titulocfm 

Definicion: se debe generar con al menos una exhibicion en el mes el EF del mes de la exhibicion si es que no existe EF para ese titulo contrato grupo en interfaces anteriors

**Comment by vivikorz** [comment]
FP100503 FILMICOS EXHIBIDOS CFM

**Comment by vivikorz** [comment]
Axel tambien por favor mirá que en la corrida que estoy haciendo de marzo por ejemplo hoy 18/3 el reporte RFP400N01EF -
tiene exhibicione por cnaje y por no canje y en su sumatoria no se ven discriminadas
Por ejemplo cto 2381 canje SI
Y CTO 2383 tiene canje NO y si miras los totales solo arroja totales en la columna de canje y deberia un total con la sumatoria de los tque tienen CFMCANJE = 'S' y en cash lo que tiene CFMCANJE = 'N'

**Comment by axel-miller** [comment]
Por esta  razon muestra un solo EF
FIL.10.04.Grabar Temporal
objeto FP40053w (no esta especicicado lo siguiente)
If &Tipo_movimiento='EF' or &Tipo_movimiento='BF'
    Do 'Busca_Previos'
Endif

Sub     'Busca_Previos'
    For each TGuUsrTmp TGmWrk TGfDte TGhTme TGK05 TGK01 TGK02 TGK03 TGK06 TGK07    
    Where TGuUsrTmp = &usuario
    Where TGmWrk    = &WrkStn 
    Where TGfDte    = &Hoy 
    Where TGhTme    = &HoraN6  
    Where TGK01     = &Tipo_movimiento
    Where TGK02		= str(&Proveedor)
    Where TGK03		= str(&Contrato)
    Where TGK05		= &Senal
    Where TGK06		= &Tipo_Titulo
    Where TGK07		= str(&Nro_Titulo)
        &grabo ='N'

**Comment by vivikorz** [comment]
AXEL: VOY A CORROBORAR QUE CON EL CASO DE USO DIGA QUE NO SE GRABE SI TODO ESO ES DEL MISMO MES DE EXHIBICION OPORQUE EL CASO QUE PLANTEO SON DE DISTINTOS MESES DE EXHIBICION QUE SE CONTABILIZAN EN LA MISMA IFZ PERO CORRESPONDEN A MESES DISTINTOS-
o SEA SI ESTOY CERRANDO MARZO Y ENCUENTRA FECHAS DE EXHIBICIONES DE MARZO NO SE HACE PERO SI ENCUENTRA DE FEBRERO O ENERO O ANTES SI

**Comment by vivikorz** [comment]
VEO ESTO EN UML:
//Se busca si existe en PP6003 movimiento de tipo 'EF' para el titulo contratado para el periodo de la fecha de exhibición. Tener en cuenta que la fecha que se registra en PP6003 para los movimientos tipo 'EF'
es el último día del periodo de la fecha de exhibición

Contabilizado_EF =0
Hay_contabilizado ='N'

Leer PP6003
	donde PPkcon = Contrato
	y Grkgrupo = Grupo
	y Snkcod = Señal
	y Ttktpotit = Tipo_Titulo
	y Mtknrotit = Nro_Titulo
	y Tvkidmov = 'EF'
	y Ppkgtkfece = ultimo día / mes de Fecha_exhibicion / año de Fecha_ exhibición
	y Ppkpgkcod = Programa

	Contabilizado_EF = PPnimpexh
	Hay_contabilizado ='S'

**Comment by axel-miller** [comment]
[MESCUDERO_F100503_Filmicos_Exhibiciones_CFM_2021319_888959.pdf](https://github.com/SistemasArtear/Filmoteca/files/6173732/MESCUDERO_F100503_Filmicos_Exhibiciones_CFM_2021319_888959.pdf)

Me parecece que asi lo esperabas

**Comment by vivikorz** [comment]
[.]([url](url
[VKORZ_F100506_Anulacion_Exhibicion_CFM_2021319_787892.pdf](https://github.com/SistemasArtear/Filmoteca/files/6173811/VKORZ_F100506_Anulacion_Exhibicion_CFM_2021319_787892.pdf)

))

**Comment by vivikorz** [comment]
AXEL ESTARIA BIEN LO DE SEPARAR LOS CANJES Y LOS CASH TAL COMO LO PEDI PERO POR FAVOR FIJATE QUE ANULAMOS DOS EXHIBICIONES DE 400470 Y EN TOTAL SALE CORRECTO QUE ES CASH PERO PONE TOTAL 400473 Y DEBERIA SER 800946.
Eso solo el resto de cash y canje se ve bien.
Con esto terminariamos el arreglo del issue. gracias

**Comment by axel-miller** [comment]
Queda revisar los total canje y cash

**Comment by vivikorz** [comment]
Sintesis  de ERRORES issue:
Queda revisar:
1) Total canje y cash de los nuevos reportes de costeo:
F100504 505 y 506
F100501 502 503 
2) Titulo SE10854 RATING FECHAS EXHIBICION 2/3 Y 3/3 CANAL 13 CORRECTO  PERO NO SALIERON LAS DE M24 SE10853 DE 2/3  Y 3/3 POR FAVOR REVISAR YA QUE NO SALEN LAS DE RATING DE M24.(QUIZAS SEA POR ALGUN ERROR AL CAMBIAR DE SEÑAL)

**Comment by vivikorz** [comment]
Axel esta el reporte
[VKORZ_F100503_Filmicos_Exhibiciones_CFM_2021322_049368.pdf](https://github.com/SistemasArtear/Filmoteca/files/6182902/VKORZ_F100503_Filmicos_Exhibiciones_CFM_2021322_049368.pdf)
Por favor revisar este reporte 
1)  SE10850 SALE UNA SOLA VEZ PERO DEBE SALIR LA EXHIB.DE FEBRERO Y LA DE MARZO
2) SE10838 NO DEBERIA SALIR YA QUE NO ESTAN  CONFIRMADAS O SEA NO TIENEN SUMOVIMIENTO E O SEA EN GT6001.GTMCONEX = 'N'  o sea estan en grilla pero no confirmadas si corroboras no estan en  el reporte de exhibiciones x ciclo 
3) SE10846 TIENE PARA MARZO TRES EXHIBICIONES ENERO FEBRERO MARZO O SEA DEBE SALIR 3 VECES1 X CADA MES CON REFERENCIA DEL MES DE LA EXHIBICION
[VKORZ_F100503_Filmicos_Exhibiciones_CFM_2021322_049368.pdf](https://github.com/SistemasArtear/Filmoteca/files/6183012/VKORZ_F100503_Filmicos_Exhibiciones_CFM_2021322_049368.pdf)

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Ya está Disponible en FIlmoWeb ALFA

EL objeto Modificado FP40099, FP40053w y  FP400N011

**Comment by vivikorz** [comment]
lo reportardo en el issue sale correcto

**Comment by vivikorz** [comment]
agregue en este issue los reportes que saque del 27. Por favor Axel, informale a Riicardo bien que reportes pasar

**Comment by vivikorz** [comment]
AXEL ESTOY VIENDO EN PRODUCCION QUE EL CTO 2378 QUE ES DE CFM tiene exhibiciones en marzo y no salen en produccion poir favor fijate sino es mucho lio y no lleva mucho tiempo que solo la marca de contabilizado si en TITUTLOCFM la debe poner en los meses contabilizados y la puso por ejemplo en  el cierre defeberp  para marzo abril y todas las escalas cargadas.
SIno lo corrigo x sql y lo vemos x separado

**Comment by axel-miller** [comment]
SE10838 NO DEBERIA SALIR YA QUE NO ESTAN CONFIRMADAS O SEA NO TIENEN SUMOVIMIENTO E O SEA EN GT6001.GTMCONEX = 'N' 

En El tratamento de Exibiciones CFM no se considera la tabla GT6001

**Comment by axel-miller** [comment]
SE10851 SI TE FIJAS TIENE FECHA EXHIBICION 16/03 Y LA ESCALA DE CFM ES PARA 02/2021 O SEA NO DEBERIA SALIR

Segun Titulo CFM no esta contabilizado para 202103

**Comment by axel-miller** [comment]
Se remiten cambios a ALFA

**Comment by rscocco** [comment]
Ya está Disponible en FIlmoWeb ALFA

EL objetos Modificados FP40067,, FP40053,  FP40053w FP400N01  FP40099,  y FP400N011

**Comment by vivikorz** [comment]
Probado en desarrollo y la jaula que cabecera es canje y titulo cfm es cash sale correcto, sumariza correcto en columna cash
.Sale correcta EE de Mirta legarand.
pido pasaje a integracion

**Comment by rscocco** [comment]
Ya está Disponible en FIlmoWeb INTEGRACION

EL objetos Modificados FP40067,, FP40053, FP40053w FP400N01 FP40099, y FP400N011

**Comment by vivikorz** [comment]
Probando en integracion. EL cto.2378 al mes 03/2021 modifiqué para tener marca en S

Esta el titulo mirta legrand cargado en prod como excedente y le puse yo duracion exce.asi sale el reporte

**Comment by vivikorz** [comment]
ok integracion Los reportes de Costo FIJO y de Excdente se ven correctos. Ademas de ver las exhibiciones de M24 y C13 clasicas correspodientes a estos dos contratos
Pido pasaje a preprod

Lote en integracion FI016521

 
Corri tambien ifz a sap en integracion viendo entre los asientos:
<item>1FB01                31032021SA580031032021ARS                  EXHIBICION POR EXCEDENTE                                                                                                                            
<item>240105040017          83330,00                              957041-   2381    C13-STORYLAB SA-LA NOCHE DE Y OTROS-                        C130013211                                                            
		<item>240105040030          53330,00                              957041-   2381    C13-STORYLAB SA-LA NOCHE DE Y OTROS-                        C130009156                                                                </item>
		<item>250105040015          53330,00                              957041-   2381    C13-STORYLAB SA                                                                                                                       </item>
		<item>250105040015          83330,00                              957041-   2381    C13-STORYLAB SA                                                                                                                       </item>
		<item>1FB01                31032021SA580031032021ARS                  EXHIBICION POR CF - CM                                                                                                                              
		<item>240501060006         400473,00                               14938-   2378    M24-FILMIC  S.A.-LA JAULA DE LA MODA 2021-LA JAULA          M240012786                                                       
		<item>250105040015         400473,00                               14938-   2378    M24-FILMIC  S.A.                                                                                                                      </item>

**Comment by vivikorz** [comment]
Hice precierre habiendo copiado datos en preprod. Cargue un contrato mixto p C13 poniendo exhibiciones de febrero y marzo y el reporte salio correcto, con ambas exhibiciones una de febrero y una de marzo. 
Ademas esta de produccion mirta legrand con excedente le cargue la duracion excdente
Salio la jaula de marzo  
Los reportes de Costo FIJO y de Excdente se ven correctos. Ademas de ver las exhibiciones de M24 y C13 clasicas correspodientes a estos dos contratos

**Comment by vivikorz** [comment]
Cargado glpi
 https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52639

**Comment by rscocco** [comment]
Se implementa en servidores Gxproductivos el proyecto **Filmoweb.war**
según solicitud :    **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52639**
