### ISSUE TITLE
pasaje a produccion del proyecto FILMO HOT FIX 1.11.01

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#33]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52614

**Comment by rscocco** [comment]
Se implementa en gxproductivo 
 https://github.com/SistemasArtear/Filmoteca/issues/30
https://github.com/SistemasArtear/Filmoteca/issues/27  

El DBA implementa en la Base Oracle Productiva  conector sprod el documento descargado de : https://github.com/SistemasArtear/plsql/releases/tag/TAG_FILMO_20210319_1-11-01_PL
Registrado con el TAG PL : TAG_FILMO_20210319_1-11-01_PL  x  https://github.com/SistemasArtear/Filmoteca/issues/29

Según solicitud :   https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52614
