### ISSUE TITLE
Confirmar  Costo Fijo/Mixto 

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#35]
En EA dentro de Artear.Filmoteca
              Confirmar exhibicion con costeo  - Confirmar exhibicion CostoFIJOoMixto

**Comment by vivikorz** [comment]
Cargué en desarrollo el contarto 2386 con escalas de costo fijo e importe en el grupo por lo tanto es MIXTO
Por el issue 36 ya deja marca de ajuste en N ya que es un contrato generado en el mismo mes 
Tiene escala en 2021 de enero a mayo 2021. EL TITULO ES SE10850 CON exhibiciones en 8/2 15/2 y 2/3, las confirmo.
Hago precierre de marzo y deberia haber en el reporte de exhibiciones por costo fijo o mixto dos registros y no salen

Estas dos exhibiciones saldrian si su marca de ajuste es S pero no es S ya que como expliqué antes es un alta  y debe venir con Ajsue en N
Adunto lo que creo que es desde el ea

**Comment by vivikorz** [comment]
Cuando le pongo la marca en S se puede ver en el log por donde fue
2334 &Grupo                     1 &Senal            M24 &Tipo_Titulo      LM &Nro_Titulo            13132 &Capitulo                  0 &Parte                     0 &Sgto                      0 &Fecha_exhibicion 10/01/21 &Importe             325 &Proveedor        951434 &Moneda       USD &Tipo_Importe FIJ &Anio               2021 &Mes                   3 &TipoMov      E_38 GRImMrcCex = N  EXAJUSTE = S]
19 Apr 2021 16:45:51,401 INFO  pfp40053c [VKORZ--Final &cant          0]
19 Apr 2021 16:45:51,401 DEBUG pfp40053a [VKORZ--inicio CFM &Tipo_Titulo SE &Nro_Titulo      10850]
19 Apr 2021 16:45:51,402 DEBUG pfp40053a [VKORZ--&usuario VKORZ &WrkStn FP400 &Hoy 19/04/21 &HoraN6     164142 &Renglon       1720 &IFkInt 9999999999 &FModo F]
19 Apr 2021 16:45:51,402 DEBUG pfp40053a [VKORZ--&Programa    1254400 &Contrato       2386 &Grupo          1 &Senal C13]
19 Apr 2021 16:45:51,402 DEBUG pfp40053a [VKORZ--&Tipo_Titulo SE &Nro_Titulo      10850 &Capitulo          1 &Parte          0 &Sgto          0]
19 Apr 2021 16:45:51,402 DEBUG pfp40053a [VKORZ--&Fecha_exhibicion 08/02/21 &Importe        263 &Proveedor     157484 &Moneda ARS &Tipo_Importe CFM]
19 Apr 2021 16:45:51,402 DEBUG pfp40053a [VKORZ--&Anio       2021 &Mes          3 &TipoMov E_38 &MESANIO     202102 &MESANIOANT     202101]
19 Apr 2021 16:45:51,402 DEBUG pfp40053a [VKORZ--SEL00 &Contrato       2386 &Grupo          1 &Senal C13 &Tipo_Titulo SE &Nro_Titulo      10850 &MESANIO     202102]
19 Apr 2021 16:45:51,403 DEBUG pfp40053a [VKORZ--Pocesar_Registro &cant          1 &Hay_cambios N &Importe_costeo        102 &TipoMov E_38]
19 Apr 2021 16:45:51,403 DEBUG pfp40053a [VKORZ--SEL01 Pocesar_Registro &Hay_cambios N AJUSTECF N TCCONTABILIZADO N &Importe_costeo      102.00 &TipoMov E_38]
19 Apr 2021 16:45:51,403 DEBUG pfp40053a [VKORZ--&Importe_costeo > 0]
19 Apr 2021 16:45:51,403 DEBUG pfp40053a [VKORZ--Procesar_movimiento_de_tipo_EF]
19 Apr 2021 16:45:51,404 DEBUG pfp40053a [VKORZ--No XXGRABO NADA  &Renglon       1720 &Tipo_Titulo: SE &Nro_Titulo:      10850 &Capitulo:          1 &Parte:          0 &Tipo_movimiento: EF &Senal: C13]
19 Apr 2021 16:45:51,404 INFO  pfp40053a [VKORZ--Final CFM &Tipo_Titulo SE &Nro_Titulo      10850 &cant          1 &cant2         0]
19 Apr 2021 16:45:51,404 DEBUG pfp40053b [VKORZ--Inicio FModo F &Renglon       1720]
19 Apr 2021 16:45:51,405 INFO  pfp40053b [VKORZ--Final &cant          0 &cant2         0....]

**Comment by vivikorz** [comment]
Además cargué contrato 2387 que es fijo o sea importe titulo 0 y con escala tampoco salio en el reporte esperado

**Comment by vivikorz** [comment]
PR_ACTUALIZA_TN6001 se ve en los logs que en este proceso actualiza TN cuando actualiza TN podria ejecutarse.

**Comment by bernardocamera** [comment]
La actualización de la tabla TITULOCFM está introducida en el procedure PR_ACTUALIZA_TN6001.

**Comment by vivikorz** [comment]
ERROR

java.sql.SQLException: ORA-20001: ORA-01400: cannot insert NULL into ("FILMO"."HIST_GRILLA_COSTEOPOREXC"."IDMOVHIST") ORA-06512: at "FILMO.FIL_PKG_CONFIRMAR_PROG", line 1616 ORA-06512: at line 1

**Comment by bernardocamera** [comment]
Fueron realizadas modificaciones en el package para corregir este error.

**Comment by vivikorz** [comment]
OK DESARROLLO PIDO PASAJE A INTEGRACION

**Comment by bernardocamera** [comment]
EL package FIL_PKG_CONFIRMAR_PROG, que contiene este issue, fue pasado a Integración.

**Comment by vivikorz** [comment]
los titulos SE10858 Y SE10857  FUERON PROGRAMADOS Y CONFIRMADO, GRabó la marca de ajuste en S  para el mes de la exhibicion como fue solicitado. ok

**Comment by bernardocamera** [comment]
Fue creado el tag :

 TAG_FILMO_20210518_1-12_PL

**Comment by rscocco** [comment]
Se implementa en la Base Oracle preproductiva el documento descargado de :   **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-05-18)%20-%20%2336%20-%20%2337**  y Registrado con el TAG PL :  **TAG_FILMO_20210518_1-12_PL**
Contiene tambien  :   https://github.com/SistemasArtear/Filmoteca/issues/37  ,  ​https://github.com/SistemasArtear/Filmoteca/issues/36
​,  https://github.com/SistemasArtear/Filmoteca/issues/40

Detalle Ejecucion : 
Package FIL_PKG_ALTA_COSTEOS compilado
Package body FIL_PKG_ALTA_COSTEOS compilado
Package FIL_PKG_MODIF_TIPO_COSTEO compilado
Package body FIL_PKG_MODIF_TIPO_COSTEO compilado
Package FIL_PKG_CONFIRMAR_PROG compilado
Package body FIL_PKG_CONFIRMAR_PROG compilado

**Comment by vivikorz** [comment]
[VKORZ_F100503_Filmicos_Exhibiciones_CFM_2021519_332377.pdf](https://github.com/SistemasArtear/Filmoteca/files/6510958/VKORZ_F100503_Filmicos_Exhibiciones_CFM_2021519_332377.pdf)
El contrato 2392 que contenia un costo fijo para M24 y costo mixto para C13 fueron confirmados y tal como adjunto en el reporte saldrian en precierre.

**Comment by vivikorz** [comment]
ok preprod solicito pasaje a produccion en: https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53006
