### ISSUE TITLE
Alta de Contratato con Tipo de Costo FIJO y MIXTO - Marca de ajuste

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#36]
Tal como está en EA. 
EN CU.GrabarCostoFijoMensual (CFM)
Desde alta de contato 
  AjusteCF     = N
Contabilizado   = N
y en CU
GrabarMixto

Ante la duda mirar EA

Tanto en tabla tituloCFM como en su HISTORICO

**Comment by bernardocamera** [comment]
Fueron introducidas las modificaciones solicitadas para alta de contratos con tipo de costo fijo y mixto.

**Comment by vivikorz** [comment]
Cargado un contrato 2390 proveedor korz mixto. TABLA titulocfm con marca de ajuste en N eso es correcto.ok

**Comment by vivikorz** [comment]
OK DESARROLLO PIDO PASAJE A INTEGRACION

**Comment by bernardocamera** [comment]
Los objetos fueron pasados a Integración.

**Comment by vivikorz** [comment]
Cargado cto.2391 SE10857 MARCA DE AJUSTE EN N tanto en titulo cfm como su historico

**Comment by rscocco** [comment]
Se implementa en la Base Oracle preproductiva el documento descargado de :   **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-05-18)%20-%20%2336%20-%20%2337**  y Registrado con el TAG PL :  **TAG_FILMO_20210518_1-12_PL**
Contiene tambien  :   https://github.com/SistemasArtear/Filmoteca/issues/37

Detalle Ejecucion : 
Package FIL_PKG_ALTA_COSTEOS compilado
Package body FIL_PKG_ALTA_COSTEOS compilado
Package FIL_PKG_MODIF_TIPO_COSTEO compilado
Package body FIL_PKG_MODIF_TIPO_COSTEO compilado

**Comment by vivikorz** [comment]
Grabado el contrato 2392 señal C13 FIJO y M24. Mixto, ambos titulos con sus escalas fueron grabados en tabla titulocfm e hist-CFM, con marca ajuste N contabilizado N. Eso es correcto.
Por lo tanto ok preprod

**Comment by vivikorz** [comment]
ok preprod solicito pasaje a produccion en: https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53006

**Comment by rscocco** [comment]
El DBA implementa en la Base Oracle Productiva el documento descargado de : **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-05-18)%20-%20%2336%20-%20%2337** y Registrado con el TAG PL : **TAG_FILMO_20210518_1-12_PL**

Según solicitud :     **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53006**
