### ISSUE TITLE
Modificar Escala Costo FIJO y Mixto dentro de Modificacion de Contrato 

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#37]
EN EA CU.Alta Modificación BAJA CF Mixto

Se puede agregar escala y modificar escala no contabilizaa marca de ajuste en N
Si se modifica escala ya contabilizada su marca de ajuste será S

Alta ModificaciónBaja_ CostoFijoMensual (CFM)

Se puede agregar escala y modificar escala no contabilizaa marca de ajuste en N
Si se modifica escala ya contabilizada su marca de ajuste será S

**Comment by bernardocamera** [comment]
Fueron programadas las modificaciones solicitadas para este issue.

**Comment by vivikorz** [comment]
Tomé el contrato ya existente 2378 y le agregué escala en 202111 que no existia o sea dentro de modificacion de contrato es entrar a titulo y en escala ya cargada en TITULOCFM se deberia agregar el año 2021 mes 11 valor 404011 y al pulsar boton agregar aparece el error: 
ERROR
ERROR No se realizo el ALTA en TITULOCFM para contrato: 2378 Grupo: 1; ORA-0000: normal, successful completion

**Comment by vivikorz** [comment]
pr_institulocfm1 se ve en el log

**Comment by vivikorz** [comment]
agregado en el EA LA VALIDACION CORRECTA 
Si es un ingreso de un mes ya existente activo es ERROR "Escala para tituloContrato existente" 
Con contrato = cokcon 
grupo= grkgrupo
Señal = SNKCOD
¨Titulo  ttktpotit + mtknrotit
anio mes  inofrmado = ANIOMES
CFEstado = 'A'
ERROR = R "Escala para tituloContrato existente"

**Comment by bernardocamera** [comment]
Fue realizada en DESA la corrección solicitada.

**Comment by vivikorz** [comment]
Se ve correcta la correccion pedida

**Comment by vivikorz** [comment]
trabaje con cto.2378 cargue escala 2020/12 300 y se generó con marca de ajuste en N y contablizado en N eso es correcto

**Comment by vivikorz** [comment]
no veo que grabe en históricos.

Por favor corroborar que está en EA
Grabar en Tabla HISTORICOTítulo CFM

Se deberá grabar para cada  titulo del grupo seleccionado todas las escalas indicadas
COKCON =  ID Contratos(es el mismo que se va a dar a todas las tablas del sistema para TN6001,CO6001 
GRKGRUPO=  Es elID Grupode la tabla GR6001 
SNKCOD = 	Es elID Grupode la tabla GR6001.snkcod
TTKTPOTIT=  Será el tipo de titulo que el sistema le  asigna al TN6001 para ese contrato_grupo_señal
MTKNROTIT	=   Serán los números de titulos que el sistema le asigna al TN6001 para ese contrato_grupo_señal    
MesAño  = Valor mes Ingresado por el usuario  
idMov.Hist  = Numerador  (k)
CFMCanje =Canje Cash Por defual vendrá indicado el de Tipo de Cabecera y el usuario podrá tener la opcion de cambiarlo. Nunca habrá dos tipos de contratos para un mismo titulo
ValorCFM=  ImporteCFM Ingresado por el usuario  
CFMCanje =VALOR CARGADO EN TITULO CFM
AjusteCF     = N
Estado = A
Contabilizado   = N
CFUUSRING  = 	usuario Ingreso
CFFYHING=         DATE
GTUUSRMOD  = bco
CFFYHMOD	= BCO

**Comment by vivikorz** [comment]
POR Favor corroborar que grabe en Tabla HISTORICOTítulo CFM
COKCON =  ID Contratos(es el mismo que se va a dar a todas las tablas del sistema para TN6001,CO6001 
GRKGRUPO=  Es elID Grupode la tabla GR6001 
SNKCOD = 	Es elID Grupode la tabla GR6001.snkcod
TTKTPOTIT=  Será el tipo de titulo que el sistema le  asigna al TN6001 para ese contrato_grupo_señal
MTKNROTIT	=   Serán los números de titulos que el sistema le asigna al TN6001 para ese contrato_grupo_señal    
MesAño  = Valor mes Ingresado por el usuario  
idMov.Hist  = Numerador  (k)
CFMCanje =Canje Cash Por defual vendrá indicado el de Tipo de Cabecera y el usuario podrá tener la opcion de cambiarlo. Nunca habrá dos tipos de contratos para un mismo titulo
ValorCFM=  ImporteCFM Ingresado por el usuario  
CFMCanje =Canje Cash Por defual vendrá indicado el de Tipo de Cabecera y el usuario podrá tener la opcion de cambiarlo. Nunca habrá dos tipos de contratos para un mismo titulo
AjusteCF     = N
Contabilizado   = N
CFUUSRING  = 	usuario Ingreso
CFFYHING=         DATE
GTUUSRMOD  = bco
CFFYHMOD	= BCO
tal como dice ea

**Comment by vivikorz** [comment]
MODIFIQUE contrato 2378 escala del mes 03 contabilizado S puso ajuste en S y contabilizado en N. Correcto

**Comment by vivikorz** [comment]
MOdifiqué el contrato 2378 una escala ya contabilizada y puso ajuste S eso es ok
Modifiqué el contrato 2378 modifiqué escala no contabilizada no puso ajuste S eso es ok
Modiqué contrato 2378 agregando una señal y grupo mixto con sus escalas, ok las marcas No es ajuste
Modiqué contrato 2378 agregando un grupo costo fijo a la señal existente  con sus escalas, ok las marcas No es ajuste

**Comment by bernardocamera** [comment]
Fue creado el tag :

TAG_FILMO_20210518_1-12_PL

**Comment by rscocco** [comment]
Se implementa en la Base Oracle preproductiva el documento descargado de :   **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-05-18)%20-%20%2336%20-%20%2337**  y Registrado con el TAG PL :  **TAG_FILMO_20210518_1-12_PL**
Contiene tambien  :   https://github.com/SistemasArtear/Filmoteca/issues/36

Detalle Ejecucion : 
Package FIL_PKG_ALTA_COSTEOS compilado
Package body FIL_PKG_ALTA_COSTEOS compilado
Package FIL_PKG_MODIF_TIPO_COSTEO compilado
Package body FIL_PKG_MODIF_TIPO_COSTEO compilado

**Comment by vivikorz** [comment]
Tomado cto.2378 agregué grupo con Titulo Mixto con escalas, marca de ajuste en N y contabilizado en N, EN EL mismo contrato agregué grupo Mixto marca de ajuste en N y contabilizado en N, EN EL mismo contrato agregué grupo Mixto.
Modifiqué grupo 1 escala mes 01/2021 y modificó con marcas en S y contabilizado en N, CORRECTO
Grabó en historico CFM

**Comment by vivikorz** [comment]
ok preprod solicito pasaje a produccion en: https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53006

**Comment by rscocco** [comment]
El DBA implementa en la Base Oracle Productiva el documento descargado de : **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-05-18)%20-%20%2336%20-%20%2337** y Registrado con el TAG PL : **TAG_FILMO_20210518_1-12_PL**

Según solicitud :     **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53006**

**Comment by vivikorz** [comment]
El DBA implementa en la Base Oracle Productiva el documento descargado de : https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-05-18)%20-%20%2336%20-%20%2337 y Registrado con el TAG PL : TAG_FILMO_20210518_1-12_PL
