### ISSUE TITLE
Clonador Relaciona TituloRemito con Contrato 

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#39]

**Comment by vivikorz** [comment]
Creado en EA Filmo.Catalogo de casos de USO. Clonador 
FIL01.02 ClonarTiTuloConContrato

**Comment by bernardocamera** [comment]
Fue desarrollado el proceso PR_CLONAR_TIT_CC, el que tiene los siguientes parámetros de entrada : 
tipo título, nro. de título, contrato viejo, grupo viejo, proveedor viejo, contrato nuevo, grupo nuevo, proveedor nuevo.

Un ejemplo de ejecución del mismo, desde pl/sql es:

exec pr_clonar_tit_cc('LA',10186,2350,4,10827,2392,4,979953);

**Comment by vivikorz** [comment]
exec pr_clonar_tit_cc('LA',10186,2350,4,10827,2398,4,979953); probe su ejecucion y se ve adicion en Rc6001. Asigno a Destoc

**Comment by pdestoc** [comment]
Quedó deployado el desarrollo java en jbossdes01 y jbossdes02
TAG_FILMOTECA_V1.7_20210623_1-7-21

**Comment by vivikorz** [comment]
Probado el titulo SE10076 QUE SE ENCUENTRA EN eL contrato 1237 prov.350742 y lo cargue en el contrato nuevo 2401 con proveedor 157484, ADICIONO EN RC6001 pero con el id de remito viejo y deberia haber ejecutado la rutina ya existente: rutina generar nro.de remito en ingreso de materiales, para darle otro id-remito

**Comment by bernardocamera** [comment]
Fue corregido este error a fin de generar registro con el nuevo número de remito.

**Comment by vivikorz** [comment]
Bernardo tomé el contrato 2401 grabando el grupo 2 con SE10838 QUE Ya existia para otro proveedor otro contrato
Cargué 4 originales al entrar en clonar con contrato eligi el titulo y debia grabar teniendo en cuenta los originales cargados y no lo hizo: 
a):
Generará tantos registros como originales haya en tn6001 para ese titulo 
Obtener la cantiadad de originales a ingresar:
Si ttktpotit = 'SE' or  'MS' or 'SU'  cantidad de originales a ingresar de la tabla RC debe ser <=  GR6001GRCNTTIT PARA ESE GRUPO CONTRATO
Actualizar para TN6001 DEL CONTRATO NUEVO TNCNTTRE = TITULOS REGISTROS GRABADOS Y tnnticonc = 'N'
b) No graba en HC6001

**Comment by bernardocamera** [comment]
Fueron efectuadas las correcciones solicitadas.

**Comment by vivikorz** [comment]
https://mvcdes.canal13.artear.com.ar/Filmo/
preferible entrar con ese usuario asi se diferencia de mi prueba 
mescudero portal01
administracion materiales
clonar con contrato
@bernardocamera @yoea13

**Comment by bernardocamera** [comment]
Fue agregado un parámetro adicional en el proceso, para en él devolver los errores que se produzcan, además de éstos ser registrados en la tabla log_procesos.

**Comment by rodrigo-fernandez** [comment]
Se hicieron los cambios para la consulta del punto 4. Y se modificó la llamada al stored procedure para recibir el nuevo parámetro.

Se deployó la nueva versión de Filmoteca en desarrollo.
Tag: **[TAG_FILMOTECA_V1.7_20211217_1-7-25](https://github.com/SistemasArtear/Filmoteca/releases/tag/TAG_FILMOTECA_V1.7_20211217_1-7-25)**

**Comment by vivikorz** [comment]
Los pasos seguidos fueron:
1 Cargue contrato 2464 con proveedor KORZ para SU10298 con 22 originales (alta de contrato)
Voy a CLonar Remito con Contrato Ya que SU10298 PERTENECE A COTO.2439 GRUPO 11
Y CARGO CONTRATO VIEJO :  2439 GRUPO 11 TITULO su10298 proveedor TRINITY 38563
Contrato nuevo 2464 grupo 1     
Arroja el siguiente error
ERROR

Se genero ERROR en el paso: 5 ORA-00001: unique constraint (FILMO.PK_HN6001) violated

**Comment by vilinares** [comment]
Se realizo la corrección en el proceso de clonación

**Comment by vivikorz** [comment]
Continuo con la prueba.
Dio de alta en TN6001 Pero en cantidad de titulos recibidos pone 2 o sea en TN6001.TNNCNTTRE = 2 eso es erroneo son 22 registros recibidos, dado que se puede observar para  SELECT *FROM tp6001 WHERE mtkNROTIT = 10298 AND ttKTPOTIT = 'SU' and cokcon = 2464 ; se puede observar 22 registros o sea 22 recibidos
select *from rc6001 where ttktpotit = 'SU' AND MTKNROTIT = 10298 and rcknumcon = 2464 ; = 22 registros 
Por lo tanto en TN deberia haber grabado el nro.22 en tnncnttre
@vilinares

**Comment by vilinares** [comment]
Se corrigió los errores en el clonador

**Comment by vivikorz** [comment]
Cargo contrato 2465 para INT. Proveedor Korz (157484) para Familia Ingals (SU10298)
Graba en TN.tnncnttre = 22 ok
Graba en HN6001.HNNCNTTRE = 22 ok hnntipmov = A ok
Graba enb Tp6001 22 registros para contrato 2465 SEÑAL INT.
Rc6001 22 registros para  para contrato 2465 SEÑAL INT

**Comment by vivikorz** [comment]
Cargo cto.2468 proveedor 157484 (korz) Como repeticin de SE10902 la jaula que originalmente es  de otro proveedor.
La cargo como REPETICION SIN RECONTRATACION X QUE NO ES RECONTRATACIÓN.
En titulo recibido pone 0 (obvio porque no lo encuentra como recibido para proveedor 157484) para eso debo entrar a clonar

**Comment by vivikorz** [comment]
Se modifico EA FIL01.02 ClonarTiTuloConContrato

**Comment by vilinares** [comment]
Se realizo el cambio solicitado para la señal en ambiente de Desarrollo

**Comment by vivikorz** [comment]
Probado cto 247 grabó correcto RC con la señal correcta. EN hn correcto, pero no en TN la cantidad de titulos recibidos @vilinares

**Comment by vilinares** [comment]
Se realizo el ajuste para TN

**Comment by vivikorz** [comment]
OK GRABACION DESDE CLONAR CONTRATO 2474 TN CON 5 TITULOS RECIBIDOS
HN OK
RC OK

**Comment by vivikorz** [comment]
Realizado precierre del mes de mayo y se puede observar los 5 capitulos  recibidos correctamente (cto.2474) por clonador 
y por recibir los faltantes
[VKORZ_Por_Recibir_2022511_048041.pdf](https://github.com/SistemasArtear/Filmoteca/files/8669478/VKORZ_Por_Recibir_2022511_048041.pdf)
[VKORZ_Recibidos_2022511_048041.pdf](https://github.com/SistemasArtear/Filmoteca/files/8669479/VKORZ_Recibidos_2022511_048041.pdf)
Prueba ok en desarrollo pidos pasaje a integracion  @vilinares @sisva @MBESCUDERO

**Comment by vilinares** [comment]
Se realizo pasaje a Integración

**Comment by vivikorz** [comment]
Doy de alta el contrato 2467 SU 10298 la familia ingals proveedor 1457 como repeticion
Se genera registro en TN con titulos recibidos en 0 es correcto porque para ese proveedor no esta el titulo

**Comment by rodrigo-fernandez** [comment]
Se deployó la nueva versión de Filmoteca en integración.

Tag: **[TAG_FILMOTECA_V1.7_20211217_1-7-25](https://github.com/SistemasArtear/Filmoteca/releases/tag/TAG_FILMOTECA_V1.7_20211217_1-7-25)**

**Comment by vivikorz** [comment]
El error reporteado en la nota anterior era por no estar deployado la nueva version

**Comment by vivikorz** [comment]
Contiuo la prueba: 
select *From tN6001 where mtknrotit = 10298 and ttktpotit = 'SU' AND COKCON = 2467;  TN6001.TNNCNTRE = 22 OK
select *From tp6001 where mtknrotit = 10298 and ttktpotit = 'SU' AND COKCON = 2467; 22 REGISTROS OK
select *From RC6001 where mtknrotit = 10298 and ttktpotit = 'SU' 22 REGISTROS PARA CONTRATO 2467  SEÑAL C13 ID REMITO =  select *From RC6001 where mtknrotit = 10298 and ttktpotit = 'SU'

**Comment by vivikorz** [comment]
SU 10298 PROVEEDOR VIEJO TRINITY LA FAMILIA ING. CTO.2439
Cargo lo mismo en otro contrato como repeticion con proveedor KORZ 157484
SELECT *fROM TN6001 WHERE MTKNROTIT = 10298 AND TTKTPOTIT = 'SU';

**Comment by vilinares** [comment]
Se realizo ajuste en el proceso en ambiente de Integración, luego se llevara a Desarrollo

**Comment by vivikorz** [comment]
Arreglado por @vilinares lo reportado
hago 
SELECT *FROM RC6001 WHERE  MTKNROTIT = 10902 AND TTKTPOTIT = 'SE' ;264120005 viejo 264170003 nuevo 

select *From rt6001 where (rtkidrem =  264120005 or rtkidrem =  264170003); el nuevo corresponde al proveedor 157484  ok

 SELECT *fROM TN6001 WHERE MTKNROTIT = 10902 AND TTKTPOTIT = 'SE'; ok para cokcon =  2464 con 5 recibidos

**Comment by vivikorz** [comment]
[VKORZ_Por_Exhibir_2022513_237516.pdf](https://github.com/SistemasArtear/Filmoteca/files/8688641/VKORZ_Por_Exhibir_2022513_237516.pdf)
[VKORZ_Recibidos_2022513_237516.pdf](https://github.com/SistemasArtear/Filmoteca/files/8688642/VKORZ_Recibidos_2022513_237516.pdf)
[VKORZ_NuevosContratos_2022513_237516.pdf](https://github.com/SistemasArtear/Filmoteca/files/8688643/VKORZ_NuevosContratos_2022513_237516.pdf)

**Comment by vivikorz** [comment]
Desde este issue solamente no influiria en cierres contables pero al hacer prueba integral se ven mov. correctos
select *from pp6003 where ifkint = 231 AND (PPKCON = 2464 or ppkcon = 2465);
select *from pp6003 where ifkint = 231 AND (PPKCON = 2464 or ppkcon = 2465)AND TVKIDMOV = 'R'; SON 49 REGISTROS (22 DEL CONTRATO 2464 GRUPO 1 C13 Y GRUPO 2 M24 PARA SU10298)Y 5 DE SU 10902
Se ven bien las recepciones generadas por estos remitos - señales - grupo contrato importe

Testing en integracion ok pido pasaje a preprod
@rodrigo-fernandez @MBESCUDERO @vilinares @sisva @rscocco

**Comment by vilinares** [comment]
Se crea TAG_FILMO_20220513_1-7_1-15-1_PL para su pasaje a Preprod

**Comment by vilinares** [comment]
Se realizo pasaje Integración

**Comment by vivikorz** [comment]
Probando en integracion solo la correcion que le pedi a @vilinares 
Cargo contrato 2466 proveedor  157657 su10298 
Cargo clonador de remito con contrato con proveedor erroneo arroja el mensaje de error . OK
Cargo clonador de remito con contrato con numero contrato nuevo erroneo arroja el error solicitoado. OK
@vilinares Por favor pasar este arreglo a preprod

**Comment by vilinares** [comment]
Se realizaron ajuste en el script 02, por favor actualizar en Preprod

**Comment by vivikorz** [comment]
Continuo con testing
Cargo contrato 2465 SU10298 PROVEEDOR POLKA 1457 
select *from tn6001 where mtknrotit = 10298 and ttktpotit = 'SU'; RECIBIDOS 0 QUEDO A CONSULTAR ES CORRECTO.
En tp no hay registros es correcto
En RC no hay registros es correcto-.
Entro a clonar remito con contrato 
a) 
 Proveedor origen  38563 grupo 1 cto 2464
Proveedor destino korz (157484) cto 2465 grpo1 Informando proveedor erroneo arroja el error ok
b) 
Proveedor origen  38563 grupo 1 cto 2464
Proveedor destino korz (157484) cto 2463 grpo1 Informando cto  erroneo arroja el error ok

**Comment by vilinares** [comment]
Se realizo la corrección en ambiente de Desarrollo

**Comment by vivikorz** [comment]
POR EL PTO.E vuelvo a probar dicho caso en desa
cargo contrato 2475
SU10298 Proveedor 979255 originales 8 Familia ingals en tn dice 0 regisgtros recibidos es ok

**Comment by vilinares** [comment]
Corregido RM en Desarrollo

**Comment by vivikorz** [comment]
Retomo

**Comment by vilinares** [comment]
Se realizo pasaje a Integración

**Comment by vivikorz** [comment]
Testing en integracion cargo contrato 2467 proveedor abadi  54312
select *from tn6001 WHERE  MTKNROTIT = 10298 AND TTKTPOTIT = 'SU'; se grabo el contrato 2467 con 11 originales
select *from tp6001 WHERE  MTKNROTIT = 10298 AND TTKTPOTIT = 'SU'; sin datos desde alta de contrato ok
Tomo clonador con contrato origen 2439 grupo 11 prv.38563 trinity
select *from tp6001 WHERE  MTKNROTIT = 10298 AND TTKTPOTIT = 'SU' and cokcon = 2467; 11 registros ok
select *from tn6001 WHERE  MTKNROTIT = 10298 AND TTKTPOTIT = 'SU' and cokcon = 2467; titulos recibidos 11 ok
select *from rc6001 where rcknumcon = 2467; 11 registros cuyo id es 264170005
select *from rm6001 WHERE  MTKNROTIT = 10298 AND TTKTPOTIT = 'SU'  ;  11 regisros del cap.1 al 11 ok
 select *From ch6001 WHERE  MTKNROTIT = 10298 AND TTKTPOTIT = 'SU' and rtkidrem =  264170005; = 11 registros ok con id 110383 a 110393

**Comment by vilinares** [comment]
Se agrego modificación al TAG por favor colocar en Preprod de nuevo el script 02

**Comment by vivikorz** [comment]
Testing en preprod cargo contrato 2467 proveedor abadi 54312
select *from tn6001 WHERE MTKNROTIT = 10298 AND TTKTPOTIT = 'SU'; se grabo el contrato 2467 con 8 originales ok 
select *from rc6001 where rcknumcon = 2467; 8 registros cuyo id es 264170004 
select *from rm6001 WHERE MTKNROTIT = 10298 AND TTKTPOTIT = 'SU' ; 8 regisros del cap.1 al 8 ok
select *From ch6001 WHERE MTKNROTIT = 10298 AND TTKTPOTIT = 'SU' and rtkidrem = 264170004; = 8 registros ok con id 110378 a 110385 
select *from sc6001; estan solo los id desde 110378 al 110385 ok 
select *from hn6001 where hokcon = 2467; 2 registros uno con 0 cuando cargue el contrato uno con 8 cuando aplique clonador
select *from hp6001 where hokcon = 2467; ok 8 registros uno x cada capitulo
select *from hc6001 where rtkidrem = 264170004; 8 registros

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=54822
@rscocco @rodrigo-fernandez @vilinares @sisva @MBESCUDERO

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=54822&
