### ISSUE TITLE
Implementacion Filmoteca/issues/3

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#4]

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=44409

**Comment by rscocco** [comment]
Implementacion Productiva correspondiente a  https://github.com/SistemasArtear/Filmoteca/issues/3 

solicitada por :  https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=44409

**Comment by rscocco** [comment]
El Dba implementa  en la base oracle productiva el documento descargado de : https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2020-09-24)%20-%20%233 y registrado con el tag : TAG_FILMO_20200924_1-8_PL

  Según solicitud :    **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=44409**

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/central.php
