### ISSUE TITLE
Confirmacion programacion con Duracion Excedente o Rating

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#40]
S el usuario confirma con borrado de grilla debe revertir el registro tanto de excedente como de rating.

**Comment by vivikorz** [comment]
SE encuentran en EA las modificaciones con color rojo en 
Artear filmoteca - 
      Catalalogo de casos de uso
            Confirmacion de programacion con  costeo
                  CargaDuraciónExcdente
                  Carga Rating

**Comment by bernardocamera** [comment]
Realicé las modificaciones correspondientes a este caso de uso.

**Comment by bernardocamera** [comment]
Fueron realizadas las correcciones en el package para corregir este error.

**Comment by vivikorz** [comment]
Por favor chequear que no graba la duración excedente ni arroja error.
Yo digito 8 y no graba en y en log procesos se puede ver: #40 Se actualizo GRILLA_COSTEOPOREXC con duracion: 0

**Comment by bernardocamera** [comment]
Fue corregida la grabación para actualizar la duración excedente.

**Comment by vivikorz** [comment]
Grabado contrato con rating y otro contrato con excedente, recibido, chequeado y puesto en grilla-
El grabado en tabla grillaexcedente ok
Pero no anda la grilla rating: ejemplo cto 2391 titulo RATING  SE10859 23/3/2021

**Comment by bernardocamera** [comment]
Fue corregido este error incluyendo el campo RATING en el UPDATE, que faltaba.

**Comment by vivikorz** [comment]
OK DESARROLLO, PROBADO TANTO PARA EXCEDENTE COMO RATING, PIDO  PASAJE A INTEGRACION

**Comment by bernardocamera** [comment]
EL package FIL_PKG_CONFIRMAR_PROG fue pasado a Integración.

**Comment by vivikorz** [comment]
Probado duracion excedente titulo LAnoche de mirtha legrand, desconfirmado y vuelto a confirmar. Actualizó registro tal como se pidio y la creacion del programa generó alta del registro en excedente. ok integracion

**Comment by vivikorz** [comment]
[
[VKORZ_F100503_Filmicos_Exhibiciones_CFM_2021518_967204.pdf](https://github.com/SistemasArtear/Filmoteca/files/6503833/VKORZ_F100503_Filmicos_Exhibiciones_CFM_2021518_967204.pdf)
[VKORZ_F100502_Filmicos_Exhibiciones_Rating_2021518_967204.pdf](https://github.com/SistemasArtear/Filmoteca/files/6503834/VKORZ_F100502_Filmicos_Exhibiciones_Rating_2021518_967204.pdf)

](url)

**Comment by vivikorz** [comment]
Confirmaciones correctas adjunto reporte.

**Comment by vivikorz** [comment]
ok integracion.

**Comment by rscocco** [comment]
Se implementa en la Base Oracle preproductiva el documento descargado de :   **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-05-18)%20-%20%2336%20-%20%2337**  y Registrado con el TAG PL :  **TAG_FILMO_20210518_1-12_PL**
Contiene tambien  :   https://github.com/SistemasArtear/Filmoteca/issues/35  ,  ​https://github.com/SistemasArtear/Filmoteca/issues/36
​,  https://github.com/SistemasArtear/Filmoteca/issues/37

Detalle Ejecucion : 
Package FIL_PKG_ALTA_COSTEOS compilado
Package body FIL_PKG_ALTA_COSTEOS compilado
Package FIL_PKG_MODIF_TIPO_COSTEO compilado
Package body FIL_PKG_MODIF_TIPO_COSTEO compilado
Package FIL_PKG_CONFIRMAR_PROG compilado
Package body FIL_PKG_CONFIRMAR_PROG compilado

**Comment by vivikorz** [comment]
Probado Mirta legarand confirmar excedente y ok
Probado un cto.nuevo con rating ok

**Comment by vivikorz** [comment]
[VKORZ_F100501_Filmicos_Exhibiciones_Excedente_Duracion_2021520_169679.pdf](https://github.com/SistemasArtear/Filmoteca/files/6518257/VKORZ_F100501_Filmicos_Exhibiciones_Excedente_Duracion_2021520_169679.pdf)
[VKORZ_F100502_Filmicos_Exhibiciones_Rating_2021520_169679.pdf](https://github.com/SistemasArtear/Filmoteca/files/6518258/VKORZ_F100502_Filmicos_Exhibiciones_Rating_2021520_169679.pdf)

**Comment by vivikorz** [comment]
ok preprod solicito pasaje a produccion en: https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53006

**Comment by rscocco** [comment]
El DBA implementa en la Base Oracle Productiva el documento descargado de : **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-05-18)%20-%20%2336%20-%20%2337** y Registrado con el TAG PL : **TAG_FILMO_20210518_1-12_PL**

Según solicitud :     **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53006**
