### ISSUE TITLE
Copia Titulos 

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#41]
Reporta el usuario que al querer ingresar a relizar una copia en SE10489 CAP.9 (POR EJEMPLO) UNA VEZ FINALIZADA LA COPIA SALE MENSAJE DE ERROR QUE CAP.ESTA RECHAZADO PAR LA SEÑAL VOLVER

Yo en preprod reproduzco ese error y puedo ver que al ejecutar 
PR_VERIFCAR_RECHAZO_CVR p_clave:SE010489 p_senialCVR p_codigo_pantalla:B

POR lo leído por mi en el pl quizas sea porque solo consulta en la tabla TL6001 y no en TJ6001.

**Comment by vivikorz** [comment]
https://mvcdes.canal13.artear.com.ar/Filmo/# (avillegas/portal01)
adeministracion de materiales
trabajar con copias
en clave poner se10489
pasar el muuse y cliclear trabajar con copia
ccapitulo 2(por ejemplo) nro.de rolllos 1
ahi sale el error

**Comment by bernardocamera** [comment]
Ejecutando desde el ambiente de desarrollo, se ha podido reproducir el error, y analizando en el procedure PR_VERIFCAR_RECHAZO_CVR, se observó que el parámetro de código de pantalla nunca era utilizado dentro del mismo, por lo que, agregándoselo, al ejecutar nuevamente la pantalla no dio error.

**Comment by vivikorz** [comment]
Probado en desarrollo TITULO SE10489 CP'.9, cap.2 ok Grabado correctamente en TJ6001
Probado en desarrollo titulo LA3140 Grabado correctamente en TL6001
Por favor pasar a integracion

**Comment by bernardocamera** [comment]
El objeto FIL_PKG_COPIA fue pasado a Integración.

**Comment by vivikorz** [comment]
Probado en desarrollo TITULO SE10489 CP2 ok Grabado correctamente en TJ6001
Probado en desarrollo titulo LA3140 Grabado correctamente en TL6001
Por favor pasar a PREPROD

**Comment by bernardocamera** [comment]
Fue creado el tag :

TAG_FILMO_20210602_1_12_01_PL

**Comment by rscocco** [comment]
se implementa en la base oracle preproductiva el documento descargado de  :  **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-06-02)%20-%20%2341**
Registrado con TAG PL :  **TAG_FILMO_20210602_1_12_01_PL**
Detalle de Ejecución: 
Package FIL_PKG_COPIA compilado
Package body FIL_PKG_COPIA compilado

**Comment by vivikorz** [comment]
Probado en preprod y LA1549 Grabé tanto copia como magister y grabo correcto en TL6001
SE10489 CP.1 TANTO COPIA COMO MAGISTER Y GRABO CORRECTO EN TJ6001

**Comment by rscocco** [comment]
El DBA  implementa en la base Oracle productiva los documentos descargados en el siguiente orden :

1 - **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-06-02)%20-%20%2341**
Registrado con TAG PL : **TAG_FILMO_20210602_1_12_01_PL**
2 - **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-06-28)%20-%20%2343**
registrada con el TAG PL : **TAG_FILMO_20210628_1_12_01_PL**
3 - **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-07-05)%20-%20%2344**
registrados con el TAG PL : **TAG_FILMO_20210705_1_12_01_PL**

DE los Git :  **https://github.com/SistemasArtear/Filmoteca/issues/41**, **https://github.com/SistemasArtear/Filmoteca/issues/43**  y  
**https://github.com/SistemasArtear/Filmoteca/issues/44**

Según solicitud :  **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53258**
