### ISSUE TITLE
Alta de Contratos (ingresar proveedor valido)

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#43]
FIL_PKG_ALTA_CONTRATOS
En alta de contrato si el usuario no ingresa el proveedor por el prompt y lo digita manualmente y es distinto de vacio no valida que el Número de Proveedor exista en tabla PR6001.

**Comment by vivikorz** [comment]
Probando en desarrollo necesito  que el mensaje sea claro para el usuario ya que el mensaje sale
java.sql.SQLException: ORA-20001: Proveedor inexistente ORA-06512: at "FILMO.FIL_PKG_ALTA_CONTRATOS", line 224 ORA-06512: at line 1

**Comment by bernardocamera** [comment]
EL fuente se encuentra en desarrollo

**Comment by vivikorz** [comment]
Probado en desa, graba correcto, y si es erroneo manda mensaje general de ERROR INESPERADO. 
Consultado con pl y Villegas y lo dejaremos asi puede avanzar este error.
Por favor pasar a integracion. Gracias

**Comment by bernardocamera** [comment]
El objeto FIL_PKG_ALTA_CONTRATOS, que fue modificado para este requerimiento, fue pasado a Int

**Comment by vivikorz** [comment]
ok integracion
Probado dar de alta una cabecera con proveedor 888888 y salio SE HA PRODUCIDO UN ERROR INESPERADO, no es mensaje lindo pero se dejará asi para poder avanzar.
Pasar a preprod

**Comment by bernardocamera** [comment]
Fue creado el tag :

TAG_FILMO_20210628_1_12_01_PL

**Comment by rscocco** [comment]
Se implementa en la base preproductiva los documentos descargados de :  **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-06-28)%20-%20%2343**  y registrada con el TAG PL :  **TAG_FILMO_20210628_1_12_01_PL**

Detalle de ejecucion: 
Package FIL_PKG_ALTA_CONTRATOS compilado
Package body FIL_PKG_ALTA_CONTRATOS compilado

**Comment by vivikorz** [comment]
PROBADO EN PREPROD.
Carga de contrato con proveedor inexistente. OK error inesperado, se permite ese tipo de error
Carga de contrato con proveedro correcto grabo bien
Ok preprod pasara a prod con todo el release

**Comment by rscocco** [comment]
El DBA  implementa en la base Oracle productiva los documentos descargados en el siguiente orden :

1 - **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-06-02)%20-%20%2341**
Registrado con TAG PL : **TAG_FILMO_20210602_1_12_01_PL**
2 - **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-06-28)%20-%20%2343**
registrada con el TAG PL : **TAG_FILMO_20210628_1_12_01_PL**
3 - **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-07-05)%20-%20%2344**
registrados con el TAG PL : **TAG_FILMO_20210705_1_12_01_PL**

DE los Git :  **https://github.com/SistemasArtear/Filmoteca/issues/41**, **https://github.com/SistemasArtear/Filmoteca/issues/43**  y  
**https://github.com/SistemasArtear/Filmoteca/issues/44**

Según solicitud :  **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53258**
