### ISSUE TITLE
Modificar Contrato

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#44]
El usuario modifica el atributo TIPO de importe, en un contrato NO CONTABILIZADO
Si la modificacion es permitida debe grabar en CO6001.COMCANJE = NUEVO ATRIBUTO Y EN HO6001 PARA ESE CONTRATO GRABAR TAMBIEN HOMCANJE= NUEVO ATRIBUTO 

Para fijarse SI  el contrato ya está contabilizado, BUSCAR  ese numero de contrato en la CS6001, con marca de contabilizado en 'S'. SI encuentra, no permite modificar en ningun campo y tira ese mensaje lindo. "Sólo se pueden modificar el Monto Total y los importes por señal, ya que el Alta del contrato ya fue contabilizada". Creo yo que en ese punto grabo en las históricos,

**Comment by bernardocamera** [comment]
Fue colocada en el package FIL_PKG_MODIF_CONTRATOS la corrección solicitada.

**Comment by vivikorz** [comment]
Probado en desa cto2397 que tiene marca de contabilizado N en tabla CS6001
CO6001.COMCANJE = N, le pongo S manda mensaje de "Contrato Modificado" pero no graba esa modificacion en CO6001 EN HO6001 GRABA UN REGISTRO NUEVO PERO sigue teniendo tambien la marca de HOMCANJE = N y deberia haber grabado ese nuevo registro en S tal como intento en mi prueba

**Comment by bernardocamera** [comment]
Hice una alteración también en el package FIL_PKG_MODIF_CONTRATOS_0X, que valida las alteraciones en el contrato, para que tome en cuenta el cambio del tipo de contrato y lo grabe.

**Comment by vivikorz** [comment]
@bernardocamera por favor mira que en tabla HO6001 agregaste el registro perfecto, pero en los registros anteriores de ese mismo contrato modificaste x el valor nuevo y ahi perdemos el sentido de lo que se busca porque pierdo la historia. O sea se agrega registro nuevo con los nuevos valores y nada mas los otros registros no se tocan

**Comment by bernardocamera** [comment]
Ahí lo vi y corregí esta actualización en la tabla HO6001.

**Comment by vivikorz** [comment]
dado de alta el contrato 2400 como Canje N y luego desde modif. puse canje S MODIFICO correcto tanto en CO6001 como en HO6001 YA QUE no estaba contabilizado
Probé el 2378 contabilizado anteriormente y no me permitido modificar eso es correcto, salio mensaje de error.
Y segui modificando otra cosa. Modifico todo y no el tipo de importe que no permitia, eso es correcto.
Pido pasaje a integracion @bernardocamera

**Comment by bernardocamera** [comment]
Fue realizado el pasaje a Integración.

**Comment by vivikorz** [comment]
Cargue contrato 2402 tipo importe =  canje 'S' y luego modifique  y modifico correctamente ya que no estaba contabilizado
Modifique contrato 2382 contabilizado y no permitio: OK y ademas segui modificando otra cosa para que de otra solapa intente grabar y nopermitio ok 
OK integracion pero no pido pasaje a preprod x lo expuesto en un mail x german, que se pase a preprod cuando estemos ya por pasar todo el relesase y  O sea la idea es minimizar el tiempo que pasa desde que se hace el deploy en Preprod y su release en produccion. En el caso de que si o si sea necesario probar el release en preprod (sin tener saber cuando se va a deployar en prod) se podria en un caso especial deployarlo sin hacer el tag.

**Comment by bernardocamera** [comment]
Fue creado el tag :

TAG_FILMO_20210705_1_12_01_PL

**Comment by rscocco** [comment]
Se implementa en la base oracle preproductiva los documentos descargados de :   **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-07-05)%20-%20%2344**  y registrados con el TAG PL :   **TAG_FILMO_20210705_1_12_01_PL**

Detalle  de ejecución:  
Package FIL_PKG_MODIF_CONTRATOS compilado
Package body FIL_PKG_MODIF_CONTRATOS compilado
Package FIL_PKG_MODIF_CONTRATOS_0X compilado
Package body FIL_PKG_MODIF_CONTRATOS_0X compilado

**Comment by vivikorz** [comment]
Grabado el cto..2401 para mes de julio al estar sin contabilizar permitio modificar en HO6001 Y CO6001 TAL COMO SE ESPERABA. OK PREPROD
Probado en cto.2398 contabilizado cambio canje N a canje Si y no lo permite por estar contabilizado. Eso es correcto.
O sea ok 
Pido pasaje a produccion.

**Comment by rscocco** [comment]
El DBA  implementa en la base Oracle productiva los documentos descargados en el siguiente orden :

1 - **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-06-02)%20-%20%2341**
Registrado con TAG PL : **TAG_FILMO_20210602_1_12_01_PL**
2 - **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-06-28)%20-%20%2343**
registrada con el TAG PL : **TAG_FILMO_20210628_1_12_01_PL**
3 - **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-07-05)%20-%20%2344**
registrados con el TAG PL : **TAG_FILMO_20210705_1_12_01_PL**

DE los Git :  **https://github.com/SistemasArtear/Filmoteca/issues/41**, **https://github.com/SistemasArtear/Filmoteca/issues/43**  y  
**https://github.com/SistemasArtear/Filmoteca/issues/44**

Según solicitud :  **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53258**
