### ISSUE TITLE
Agregar o Modificar Escala Costo FIJO y Mixto dentro de Modificacion de Contrato 

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#45]
Alta Modificación BAJA CF Mixto
Alta ModificaciónBaja_ CostoFijoMensual (CFM)
EN EA RESALTADA LA MODIFICACION CON AZUL

**Comment by bernardocamera** [comment]
Fue realizada la modificación en "azul" solicitada.

**Comment by vivikorz** [comment]
ok

**Comment by bernardocamera** [comment]
Fue realizado el pasaje a Integración.

**Comment by vivikorz** [comment]
ok integracion

**Comment by bernardocamera** [comment]
Fue creado el tag :
TAG_FILMO_20210728_1-13_PL
Para pasaje a Preproducción

**Comment by vivikorz** [comment]
Tomado en desarrollo el contrato 2395 existente. Agrego mes 12/2021  Grabo marca de ajuste S y contabilizado N
Al mes 05/2021 le modifico importe ya contabilizado y puso marca AJUSTE S contabilizado N

**Comment by vivikorz** [comment]
Por favor @bernardocamera pasar a integracion

**Comment by bernardocamera** [comment]
Los objetos fueron pasados a Integración

**Comment by vivikorz** [comment]
Probado integracion ok

**Comment by rscocco** [comment]
Se implementa en base preproductiva los documentos descargados de : 
 **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-07-05)%20-%20%2344**
Registrados en el TAG PL :   **TAG_FILMO_20210705_1_12_01_PL**
Detalle de Ejecución : 
Package FIL_PKG_ALTA_COSTEOS compilado
Package body FIL_PKG_ALTA_COSTEOS compilado
Package FIL_PKG_MODIF_TIPO_COSTEO compilado
Package body FIL_PKG_MODIF_TIPO_COSTEO compilado

**Comment by vivikorz** [comment]
Probado en preprod.
Cargue contrato 2415 proveedor Korz con dos escalas desde alta grabo TITULCFM SE10873 07/2021 700 y 08/2021 800 Ajuste  N y contabilizado en N OK
Desde modificacion agrego escala 09/2021 900 marca S y modifico 07/2021 de 700 a 707: marca ajuste S contabilizado N OK

**Comment by rscocco** [comment]
El DBA implementa en base Productiva los documentos descargados de :
https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-07-05)%20-%20%2344
Registrados en el TAG PL : TAG_FILMO_20210705_1_12_01_PL

Según solicitud : https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556
