### ISSUE TITLE
Movimiento de alta de valor de escalas en TIPO MOV.A  

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#46]
**Nota: No tener en cuenta la modificación de EA eso no se programa. La modificación de programación que se debe hacer es la definida en nota del dia 10/08, redactada por Escudero**

FIL.10.Cierre Contable Tratamiento de costeo (activity)
   Accion leer TG6001 **(modificacion resaltada en color verde)**
       FIL.10.00.Procesar Alta Escala  CFM o Mixto   **CU.agregado** esto es nuevo

**Comment by axel-miller** [comment]
El objeto en el EA
FIL.10.00.Procesar Alta Escala CFM o Mixto
Esta vacio el Objeto

FIL.10.04.Grabar Temporal
Hay nuevo parametro? no figura como parametro, si lo hay donde y bajo que condiciones se graba?

**Comment by axel-miller** [comment]
desarrollando FIL.10.00.Procesar Alta Escala CFM o Mixto

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb  ALFA
Junto con los cambios por  GIT :   **https://github.com/SistemasArtear/Filmoteca/issues/53, https://github.com/SistemasArtear/Filmoteca/issues/52, https://github.com/SistemasArtear/Filmoteca/issues/51, https://github.com/SistemasArtear/Filmoteca/issues/50, https://github.com/SistemasArtear/Filmoteca/issues/49, https://github.com/SistemasArtear/Filmoteca/issues/48, https://github.com/SistemasArtear/Filmoteca/issues/47, https://github.com/SistemasArtear/Filmoteca/issues/46**

**Comment by vivikorz** [comment]
Cargue contrato 2403 - SE10867 de 1500 valor titulo proveedor KORZ (157484) CABECERA CASH
ES titulo SE con 4 originales o sea 4 capitulos se esperan
Con varias escalas en la tabla titulocfm con cfmcanje = S
añomes 202101 valorcfm 100
añomes 202102 valorcfm 200
añomes 202103 valorcfm 300
añomes 202104 valorcfm 400
añomes 202105 valorcfm 500
añomes 202106 valorcfm 600
añomes 202107 valorcfm 700
añomes 202108 valorcfm 800
Recibo de los 4 originales 3 cap.1 cap 2 cap3, los caules chequeo ok
Luego exhibo 2 cap. 1 el 14/7
cap. 2 1/6
Confirmo dichas exhibiciones

DE LOS reportes enviados a modificar se puede ver
A)  EN GRABACION DE PP6003 SE VE DOS MOV.A con detalle 2 y otro con detalle 3

**Comment by axel-miller** [comment]
Se logra que los mvimientosTipo A esten en el reporte de nuevos contratos. se adjunta documento

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb ALFA

**Comment by vivikorz** [comment]
Probado precierre de 07/21 contrato 2403 con escalas que sumarizan 3600 canje S. En grabacion TG SE VE CORRECTO EL MOV.A CON tgnum15 = 2

**Comment by vivikorz** [comment]
por favor pasar a integracion asi llego a cierre definitivo y no le pierdo los datos a Axel en desarrollo, vi generación en tabla TG6001

**Comment by rscocco** [comment]
https://artear.my.workfront.com/task/view?ID=60d366e5001e3d0c995abbce5c4ead4f&commentID=60fea5760004760db3546440df138bd0&activeTab=tab-task-updates&email-source=comm

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb ALFA
Junto con los cambios por GIT : #53, #52, #51, #50, #49, #48, #47, #46

**Comment by rscocco** [comment]
https://artear.my.workfront.com/task/view?ID=60d366e5001e3d0c995abbce5c4ead4f&commentID=61016360004d493861d1ee6b9e806080&activeTab=tab-task-updates&showCommentBox=true&email-source=comm

**Comment by MBESCUDERO** [comment]
**Se redefinen los cambios. Detallo a continuación lo que se debe modificar en los objetos GX existentes**
En FP40005 generacion PP Alta
Para el tn que esta recorriendo para el reporte
 Sumar en total_cfm  titulocfm.valorcfm donde
 Leer TituloCFM 
		donde cokcon = tn6001.cokcon	
		y Grkgrupo 	 = tn6001.grkgrupo
		y Snkcod	 = tn6001.snkcod
		y ttktpotit  = tn6001.ttktpotit
		y mtknrotit	 = tn6001.mtknrotit

Si total_cfm >0
	registrar en TG del reporte el titulo con el total_cfm acumulando en canje o cash 
	dependiendo si titulocfm.cfmcanje tiene S o N
	
	1- obtener ultimo nro detalle
	2- Insertar PP6001 igual al del alta del contrato pero con importe total_cfm 
		y en PPksnkexh titulocfm.cfmcanje
Finsi

En reporte fp40067 nuevos contratos
Para el tn que esta recorriendo para el reporte
 Sumar en total_cfm  titulocfm.valorcfm donde
 Leer TituloCFM 
		donde cokcon = tn6001.cokcon	
		y Grkgrupo 	 = tn6001.grkgrupo
		y Snkcod	 = tn6001.snkcod
		y ttktpotit  = tn6001.ttktpotit
		y mtknrotit	 = tn6001.mtknrotit

Si total_cfm >0
	registrar en TG del reporte el titulo con el total_cfm acumulando en canje o cash 
	dependiendo si titulocfm.cfmcanje tiene S o N
Finsi

**Comment by MBESCUDERO** [comment]
Se libera para programación 
@axel-miller @vivikorz

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb ALFA
Junto con los cambios por GIT : #53, #52, #51, #50, #49, #48, #47, #46

**Comment by axel-miller** [comment]
https://artear.my.workfront.com/task/view?ID=610af0b4001066d0bc8b92c1343cdd8e

**Comment by axel-miller** [comment]
Realizando cambios según nueva especificación

**Comment by axel-miller** [comment]
se remiten los cambios

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb ALFA

**Comment by vivikorz** [comment]
Se copian los datos de produccion en desarrollo. 
Exise el contrato 2412 con 1 registro en TN6001 y en TITULOCFM 5 escalas de 645.000 cada una. En reporte de alta de contrato RFP40067 se puede ver el registro  con 551300 eso corresponde al alta en el TN falta grabar registro en TG6001 DEL MOV.A con tgk10 = N y por lo tanto no salio el reporte. 
  
Leo nota de especificacion deL 10/8 para seguir el caso y deberia este registro estar dado de alta

**Comment by rscocco** [comment]
Se rectifican por problemas de pasaje,  ya está disponible en Filmo  ALFA

**Comment by vivikorz** [comment]
tomo issue

**Comment by axel-miller** [comment]
Se Remiten los cambios

**Comment by rscocco** [comment]
Se toman Objetos de Alfa  sin OK y se implementan en integración,  para pruebas,  según lo solicitado.

Ya esta disponible, Gx Filmo Integracion.

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb ALFA

**Comment by vivikorz** [comment]
Tomada prueba en desarrollo. 
Veo los reportes correctos.
Pero no veo en TG los movimientos. Cargue  el contrato 2414 proveedor Korz de 1000$ cabecera 2100 sumatoria escalasy tambien el cto.2412 cargado x el usuario en prod.

Pero al realizar alta de contratro veo un tema independiente de esto que es que por error de programacion se toco  PR_INS_COSTEO_MIXTO (que nunca se habia modificado nada en EA) )(INSERT DE TITULOCFM DESDE ALTA DE CONTRATO). DEJANDO  las marcas de ajuste en S de manera erronea.
No obstante ese error y reportado para su correccion a mano deje en TITULOCFM LA MARCA DE AJUSTE EN N para contrato 2414, no lo voe en TG pero si en Reportes como detalle antes.
@MBESCUDERO @sisva @axel-miller

**Comment by vivikorz** [comment]
Por favor @rscocco PASAR A PREPROD
@MBESCUDERO @axel-miller @sisva @yoea13

**Comment by rscocco** [comment]
Se implementa en Filmoweb Pre-productivo-.

**Comment by vivikorz** [comment]
Corrida cierre definitvo en preprod. 
Se puede ver el log que procesa el contrato 2415 que cargue yo con esas escalas
31 Aug 2021 16:12:02,119 DEBUG rfp40005a [VKORZ--&ES_CANJE N &total_cfm  3225000.00..]
31 Aug 2021 16:12:02,151 DEBUG pfp40005  [VKORZ--Graba Alta CFM:M24M24 &TTkTpoTit SE &TCMTkNroTit  10870 Importe: 3225000.00]
31 Aug 2021 16:12:02,245 DEBUG pfp40005  [VKORZ--&Usuario  &COkCon    2415 &GRkGrupo   1 &SNkCod C13 &TTkTpoTit SE &TCMTkNroTit  10873]
31 Aug 2021 16:12:02,245 INFO  rfp40005a [VKORZ--&ES_CANJE N &total_cfm      707.00 Valorcfm:     707.00]
31 Aug 2021 16:12:02,245 INFO  rfp40005a [VKORZ--&ES_CANJE N &total_cfm     1507.00 Valorcfm:     800.00]
31 Aug 2021 16:12:02,246 INFO  rfp40005a [VKORZ--&ES_CANJE N &total_cfm     2407.00 Valorcfm:     900.00]

y el contrato 2412 que se dio de alta en produccion:
31 Aug 2021 16:12:01,471 INFO  ofp45002  [VKORZ--Genera Asiento 36]
31 Aug 2021 16:12:02,117 DEBUG pfp40005  [VKORZ--&Usuario  &COkCon    2412 &GRkGrupo   1 &SNkCod M24 &TTkTpoTit SE &TCMTkNroTit  10870]
31 Aug 2021 16:12:02,119 INFO  rfp40005a [VKORZ--&ES_CANJE N &total_cfm   645000.00 Valorcfm:  645000.00]
31 Aug 2021 16:12:02,119 INFO  rfp40005a [VKORZ--&ES_CANJE N &total_cfm  1290000.00 Valorcfm:  645000.00]
31 Aug 2021 16:12:02,119 INFO  rfp40005a [VKORZ--&ES_CANJE N &total_cfm  1935000.00 Valorcfm:  645000.00]
31 Aug 2021 16:12:02,119 INFO  rfp40005a [VKORZ--&ES_CANJE N &total_cfm  2580000.00 Valorcfm:  645000.00]
31 Aug 2021 16:12:02,119 INFO  rfp40005a [VKORZ--&ES_CANJE N &total_cfm  3225000.00 Valorcfm:  645000.00]
31 Aug 2021 16:12:02,119 DEBUG rfp40005a [VKORZ--&ES_CANJE N &total_cfm  3225000.00..]

**Comment by rscocco** [comment]
Se implementa en Filmoweb Integracion

**Comment by rscocco** [comment]
Se implementa en Filmoweb Integracion

**Comment by rscocco** [comment]
Se implementa en servidores Gxproductivo  según solicitud :   https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556&
