### ISSUE TITLE
Movimiento de Recepcion  de importe de escalas en TIPO MOV.R 

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#47]

**Comment by vivikorz** [comment]
EN FIL.10.01.Procesar Coste CFM o Mixto

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb  ALFA
Junto con los cambios por  GIT :   **https://github.com/SistemasArtear/Filmoteca/issues/53, https://github.com/SistemasArtear/Filmoteca/issues/52, https://github.com/SistemasArtear/Filmoteca/issues/51, https://github.com/SistemasArtear/Filmoteca/issues/50, https://github.com/SistemasArtear/Filmoteca/issues/49, https://github.com/SistemasArtear/Filmoteca/issues/48, https://github.com/SistemasArtear/Filmoteca/issues/47, https://github.com/SistemasArtear/Filmoteca/issues/46**

**Comment by vivikorz** [comment]
Cargue contrato 2403 - SE10867 de 1500 valor titulo proveedor KORZ (157484) CABECERA CASH
ES titulo SE con 4 originales o sea 4 capitulos se esperan
Con varias escalas en la tabla titulocfm con cfmcanje = S
añomes 202101 valorcfm 100
añomes 202102 valorcfm 200
añomes 202103 valorcfm 300
añomes 202104 valorcfm 400
añomes 202105 valorcfm 500
añomes 202106 valorcfm 600
añomes 202107 valorcfm 700
añomes 202108 valorcfm 800
Recibo de los 4 originales 3 cap.1 cap 2 cap3, los caules chequeo ok
Luego exhibo 2 cap. 1 el 14/7
cap. 2 1/6
Confirmo dichas exhibiciones
Salen dos mov.EF correctos yo espero 2 de R y sale uno solo de 600 faltaria el de 700 Rechazo

**Comment by vivikorz** [comment]
Para el contrato 2403 veo en TG por mov.EF los 2 mov. R que esperaba con los importes coincidentes del EF eso es correcto.

**Comment by vivikorz** [comment]
por favor pasar a integracion asi llego a cierre definitivo y no le pierdo los datos a Axel en desarrollo, vi generación en tabla TG6001

**Comment by rscocco** [comment]
https://artear.my.workfront.com/task/view?ID=60d366e5001e3d0c995abbce5c4ead4f&commentID=60fea5760004760db3546440df138bd0&activeTab=tab-task-updates&email-source=comm

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb ALFA
Junto con los cambios por GIT : #53, #52, #51, #50, #49, #48, #47, #46

**Comment by vivikorz** [comment]
OK DESA PASAR A INT

**Comment by rscocco** [comment]
https://artear.my.workfront.com/task/view?ID=60d366e5001e3d0c995abbce5c4ead4f&commentID=60fea5760004760db3546440df138bd0&activeTab=tab-task-updates&email-source=comm

**Comment by vivikorz** [comment]
Prueba realizada en desarrollo con los ultimos cambios.
En precierre los reportes de Recibidos lo generó correcto. 1 Recibido por el contrato 2395 y otro Recibido por el contrato 2378 ademas de los recibidos de siempre.
Por dicho motivo hice cierre definitivo se puede observar que genero 2 movimientos de R y en el reporte. Quise ver TG pero lo borro luego del cierre definitivo.

**Comment by MBESCUDERO** [comment]
En EA se modifica la especificación con el siguiente detalle, los cambios estan en rojo. Tener en cuenta que los reportes de movimientos de recepcion y anulacion de recepción no tienen cambios ya que se usa el mismo formato que las recepciones y anulaciones ya existentes.
- En CU FIL.10.01.Procesar Coste CFM o Mixto se modificaron las siguiente acciones:
Leer TituloCFM
Acción "Procesar movimiento de tipo EF"
Acción "Registrar movimiento EF"
Acción "Procesar anulacion CFM contabilizado"
Acción "Procesar Anulación EF"
Acción "Anulacion Movimiento tipo BF"
- En CU FIL.10.04.Grabar Temporal
Se modificaron los parámetros , se agregó el parametro CFMcanje
Se modificó la acción "Insertar registro en TG6001"
- En CU Procesar CFM se modificaron las siguientes acciones:
Acción Leer TituloCFM
Acción Anular Contabilizacion EF
Acción Generar Movimiento ef

Se libera para programación. 
@axel-miller 
@vivikorz 
Tener en cuenta en las pruebas, de probar primero precierre y pidiendo a Axel que no borre la TG para comprobar la correcta grabación de los movimientos en la tg.
Luego sí en probar el cierre definitivo , ahi si habrá que pedir que se deje con el borrado de la tg como debe ser.

**Comment by axel-miller** [comment]
inicio cambios CU FIL.10.01.Procesar Coste CFM o Mixto

**Comment by axel-miller** [comment]
Se realizan cambios en grabación de temporal

**Comment by MBESCUDERO** [comment]
Aclaración, olvidé informar que también se modificó en el CU FIL.10.Cierre Contable Tratamiento Costeos , la acción "Leer TG6001", por ahora solo cambió la parte de la condición "Si TGK01 es RE", por alta y modificación de alta también cambiarán, pero lo documentaré en el issue correspondiente. Copio a continuación la parte que hay que modificar por este issue.
	Si TGK01 es 'RE'
		Tipo_movimiento = TGK01
		Señal	= TGK02
		Contrato = TGK05
		Grupo 	= TGK06
		Tipo_titulo = TGK07
		Nro_titulo  = TGK08	

@axel-miller 
@vivikorz

**Comment by axel-miller** [comment]
Se realizan cambios en Procesar CFM

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb ALFA
Junto con los cambios por GIT : #53, #52, #51, #50, #49, #48, #47, #46

**Comment by vivikorz** [comment]
En precierre se genera correcto en tg pero no en cierre definitivo ni en tg, ni reportes ni pp

**Comment by axel-miller** [comment]
Los cambios van junto con https://github.com/SistemasArtear/Filmoteca/issues/48

**Comment by rscocco** [comment]
ya esta disponible en Filmoweb ALFA

**Comment by axel-miller** [comment]
Se reenvia objetos con reorden de carpetas

**Comment by vivikorz** [comment]
Tomado los datos de produccion. Se ingreso en prod.para agosto Cto,.2412
Hago precierre se puede ver en reporte de recepcion las R correspondientes a agosto No hay de meses pasadas
2395 SE010862 LA PREVIA DE LA ACADEMIA 0 Cash  440000.00 ok
2378 SE010838 LA JAULA DE LA MODA 2021 0 Cash 400473.00 ok
2412 SE010870 MAÑANISIMAS 2021               Cash 645000.00  ok Todas estas recepciones son Cash ok y la cabecera del contrato Canje y salio ok

**Comment by rscocco** [comment]
Se rectifican por problemas de pasaje,  ya está disponible en Filmo  ALFA

**Comment by rscocco** [comment]
Se toman Objetos de Alfa  sin OK y se implementan en integración,  para pruebas,  según lo solicitado.

Ya esta disponible, Gx Filmo Integracion.

**Comment by vivikorz** [comment]
Tomado testing en integracion.

**Comment by vivikorz** [comment]
Tomo contrato 2412 que fue cargado en el mes de agosto desde produccion.
Le agrego yo una escala de julio. Asi de esta manera tengo un EF a agosto y otro a julio.
Vi los EF en reportes de exhbiciones y en TG
Se pueden ver los R de cto.2378 (agosto) R de 2395 (agosto) R de julio y R de agosto para 2412
Dado que veo bien los datos en precierre y sus reportes tiro Cierre Definitivo Mes de agosto

**Comment by rscocco** [comment]
Se implementa en Filmoweb Pre-productivo-.

**Comment by vivikorz** [comment]
Probado con los datos de preprod mov.R
select *From pp6003 WHERE PPkpRo = 968020 and tvkidmov = 'R' AND IFKINT = 222 AND PPKCON = 2395:  se ve 1 registro de 440000 con N en ppsnkexh OK 
select *From pp6003 WHERE  tvkidmov = 'R' AND IFKINT = 222 AND PPKCON = 2378: se ve 1 registro de 400473 con N en ppsnkexh OK
select *From pp6003 WHERE  tvkidmov = 'R' AND IFKINT = 222 AND PPKCON = 2412: 1 DE 645000 CON PPSNKEXH =N 
Ninguno el contrato 2415 que se dio de alta porque no tiene EF ok 

select *From pp6002 WHERE  tvkidmov = 'R' AND IFKINT = 222 AND PPKCON = 2412 de  733208 ok
 select *From pp6002 WHERE  tvkidmov = 'R' AND IFKINT = 222 AND PPKCON = 2378 de 477018 ok
select *From pp6002 WHERE  tvkidmov = 'R' AND IFKINT = 222 AND PPKCON = 2395; de 517330 ok

**Comment by rscocco** [comment]
Se implementa en Filmoweb Integracion

**Comment by rscocco** [comment]
Se implementa en servidores Gxproductivo  según solicitud :   https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556&
