### ISSUE TITLE
Procesar ANulacion EF con Baja Recepcion escala 

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#48]
**FIL.10.Cierre ContableTratamiento de Costeos SE MODIFICACRON EN LOS CU EXISTENTES CON COLOR VERDE**
    FIL.10.01.Procesar Coste CFM o Mixto   
                            **Procesar anulacion CFM contabilizado (modificaciones en EA con color verde)
                               Generar Anulacion movimiento tipo 'BF' (modificaciones en EA con color verde)
         CU Procesar CFM - Anular Contabilizado EF (modificaciones en EA con color verde)
         CU Procesar CFM  - Generar Movimiento EF (modificaciones en EA con color verde)**

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb  ALFA
Junto con los cambios por  GIT :   **https://github.com/SistemasArtear/Filmoteca/issues/53, https://github.com/SistemasArtear/Filmoteca/issues/52, https://github.com/SistemasArtear/Filmoteca/issues/51, https://github.com/SistemasArtear/Filmoteca/issues/50, https://github.com/SistemasArtear/Filmoteca/issues/49, https://github.com/SistemasArtear/Filmoteca/issues/48, https://github.com/SistemasArtear/Filmoteca/issues/47, https://github.com/SistemasArtear/Filmoteca/issues/46**

**Comment by MBESCUDERO** [comment]
En EA se modifica la especificación con el siguiente detalle, los cambios estan en rojo. Tener en cuenta que los reportes de movimientos de recepcion y anulacion de recepción no tienen cambios ya que se usa el mismo formato que las recepciones y anulaciones ya existentes.

En CU FIL.10.01.Procesar Coste CFM o Mixto se modificaron las siguiente acciones:
Leer TituloCFM
Acción "Procesar movimiento de tipo EF"
Acción "Registrar movimiento EF"
Acción "Procesar anulacion CFM contabilizado"
Acción "Procesar Anulación EF"
Acción "Anulacion Movimiento tipo BF"
En CU FIL.10.04.Grabar Temporal
Se modificaron los parámetros , se agregó el parametro CFMcanje
Se modificó la acción "Insertar registro en TG6001"
En CU Procesar CFM se modificaron las siguientes acciones:
Acción Leer TituloCFM
Acción Anular Contabilizacion EF
Acción Generar Movimiento ef
Se libera para programación.
@axel-miller
@vivikorz
Tener en cuenta en las pruebas, de probar primero precierre y pidiendo a Axel que no borre la TG para comprobar la correcta grabación de los movimientos en la tg.
Luego sí en probar el cierre definitivo , ahi si habrá que pedir que se deje con el borrado de la tg como debe ser.

**Comment by axel-miller** [comment]
Se remiten los cambios por FP40053a FIL.10.01.Procesar Costeo CFM o Mixto, FP40053d Procesar CFM y FP40053w FIL.10.04.Grabar Temporal 
Los cambios van junto con https://github.com/SistemasArtear/Filmoteca/issues/47

**Comment by vivikorz** [comment]
CTO 2378 SEÑAL M24 Tiutlo SE10862 TIENE EF en pp6003  para el mes de abril con 100.000.
Tenia exhibiciones del 26 de abril al 30 de abril, desconfirmo todas las exhbiciones.
 Desde  desconfirmacion de programacion  no deja marca de ajuste en TItulocfm. 
 Pero tanto el precierre  contable como el cierre se tienen que dar cuenta que como desconfirme todas las exhibiciones del mes,  estoy Ejecutando 07/2021 y  desconfirmo 04/2021 sin dejar ninguna exhibicion para el mes de abril
Resultado esperado  debe revertir el EF O SEA hacer BF de las exhibiciones de abril  y como consecuencia un BR por el mismo importe.
Habiendo desconfirmaciones si no queda nada confirmado para el mes se debe revertir el EF si queda al menos una confirmacion no se revirte el mov.EF.

**Comment by rscocco** [comment]
ya esta disponible en Filmoweb ALFA

**Comment by vivikorz** [comment]
@rscocco @MBESCUDERO @axel-miller No puede estar disponible en desa ya que no esta terminado el ajuste de especificacion

**Comment by axel-miller** [comment]
se modifico
Leer TituloCFM                               
Acción "Procesar movimiento de tipo EF"      
Acción "Registrar movimiento EF"             
Acción "Procesar anulacion CFM contabilizado"

**Comment by axel-miller** [comment]
https://artear.my.workfront.com/task/view?ID=611d5a54004b61d752ee379b5488a4da

**Comment by MBESCUDERO** [comment]
Se modifica la especificación por error detectado sobre la generación de BF (producción).
En CU FIL.10.01.Procesar Coste CFM o Mixto: Los cambios se marcan en rojo como git 48
Quitar condición Hay_Cambio ='N' y comentar rama del No 
se modifican las acciones:
	condición: Si Tipo_movimiento='RE'
	acción:  Procesar Anulacion EF 
	accion: Generar Anulacion movimiento tipo 'BF' 
	
@vivikorz @axel-miller  libero para programación

**Comment by MBESCUDERO** [comment]
Tomo esta tarea para programar.

**Comment by MBESCUDERO** [comment]
Terminé la programación de los cambios de especifición que documente ayer: 
Se modifica la especificación por error detectado sobre la generación de BF (producción).
En CU FIL.10.01.Procesar Coste CFM o Mixto: Los cambios se marcan en rojo como git 48
Quitar condición Hay_Cambio ='N' y comentar rama del No
se modifican las acciones:
condición: Si Tipo_movimiento='RE'
acción: Procesar Anulacion EF
accion: Generar Anulacion movimiento tipo 'BF'

No puedo lograr hacer funcionar mi entorno de prueba local, por este motivo paso a Ricardo para que deploye en desarrollo para poder hacer la prueba de programación ahi. Una vez vea ejecuta sin cancelación, lo asignaré a Viviana para que a disposición de su prueba.
@vivikorz

**Comment by rscocco** [comment]
Ya esta disponible en filmoweb Alfa   

Objeto modificado por git   https://github.com/SistemasArtear/Filmoteca/issues/53

**Comment by MBESCUDERO** [comment]
Realice prueba en entorno local y visualizo en TG la generación de movimiento BF y BR. 
Paso cambios a Ricardo para deployar en desarrollo y libero para que Viviana haga la prueba completa
@vivikorz

**Comment by rscocco** [comment]
Ya esta disponible en filmoweb Alfa

Objeto FP40053a modificado por git #53

**Comment by vivikorz** [comment]
Tomada la prueba en desarrollo para contrato 2395 que desconfirme todas sus exhibiciones del mes de julio
Se ve:
21 REGISTROS de RE para las exhibiciones del mes de julio del cto 2395 
1 BF con fecha 31/07/2021 ok 
Grabacion en TG de un registro tgk01 = BR por 440000 con TGK10 = N

**Comment by MBESCUDERO** [comment]
Se corrige y verifica el error reportado en entorno local.
Paso a Ricki la corrección para su deploy en desarrollo
@vivikorz

**Comment by rscocco** [comment]
Se toman Objetos de Alfa  sin OK y se implementan en integración,  para pruebas,  según lo solicitado.

Ya esta disponible, Gx Filmo Integracion.

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb ALFA

**Comment by vivikorz** [comment]
Probado en desarrollo para contrato 2395

    Desconfirme TODAS sus exhibiciones del mes de julio y desconfirmo exhibiciones de junio (no todas)
     para junio  1 2 3 (no son todas)
    Se ve en tg6001:
       1 BF con fecha 31/07/2021 ok  
      1 BR EN tg6001 de 440000 con TGK10 = N
    El reporte de anulacion por CFM tambien se ve correcto en desarrollo 
OK DESARROLLO.

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb Integracion

**Comment by vivikorz** [comment]
Comienzo prueba en integracion

**Comment by vivikorz** [comment]
Por favor @rscocco pasar a PREPROD
@MBESCUDERO @axel-miller @sisva @yoea13

**Comment by rscocco** [comment]
Se implementa en Filmoweb Pre-productivo-.

**Comment by vivikorz** [comment]
Tomados datos nuevos de preprod pero como no hay anulacion de EF desconfirme a mano todo el mes de junio del titulo SE10862 CTO.2395 
Corro precierre.
Espero BF y BF

**Comment by rscocco** [comment]
Se implementa en Filmoweb Integracion

**Comment by rscocco** [comment]
Se implementa en servidores Gxproductivo  según solicitud :   https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556&
