### ISSUE TITLE
FIL10.04 Grabar temporal

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#49]
Se incluye en la grabacion del temporal el atributo PPNNRODET, detalle (se utilizara con valor 2 PARA LOS MOVIMIENTOS DE ALTA DE ESCALA Y RECEPCION DE ESCALAS), en los mov.EF sigue con 1 TAL COMO VENIA HACIENDOSE HASTA AHORA
**VER EA modificacion realizada en verde**
Se incorporan tambien los mov.MA con ppnnrodet = 2 (Modificacion de escalas)
 Se incorporan tambien los mov.BR con ppnnrodet = 2 (SI se anula un EF de la mano iria un BR)

**Comment by vivikorz** [comment]
ACTION : Insertar registro en TG6001 EN VERDE

**Comment by axel-miller** [comment]
No se realizarian cambios en FIL10.04 Grabar temporal

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb  ALFA
Junto con los cambios por  GIT :   **https://github.com/SistemasArtear/Filmoteca/issues/53, https://github.com/SistemasArtear/Filmoteca/issues/52, https://github.com/SistemasArtear/Filmoteca/issues/51, https://github.com/SistemasArtear/Filmoteca/issues/50, https://github.com/SistemasArtear/Filmoteca/issues/49, https://github.com/SistemasArtear/Filmoteca/issues/48, https://github.com/SistemasArtear/Filmoteca/issues/47, https://github.com/SistemasArtear/Filmoteca/issues/46**

**Comment by vivikorz** [comment]
por favor pasar a integracion asi llego a cierre definitivo y no le pierdo los datos a Axel en desarrollo, vi generación en tabla TG6001

**Comment by rscocco** [comment]
https://artear.my.workfront.com/task/view?ID=60d366e5001e3d0c995abbce5c4ead4f&commentID=60fea5760004760db3546440df138bd0&activeTab=tab-task-updates&email-source=comm

**Comment by vivikorz** [comment]
Probado en desarrolo contrato 2378, 2395 2410 en TG veo la grabacion de los R nuevos igual que los R viejos eso es correcto mas en los nuevos en TG6001.TGK10 S o N segun corresponda y fue correcto

**Comment by vivikorz** [comment]
No corresponde este arreglo, se contempla la grabacion del TG6001, con tgk10 = cfmcanje y no con numero detalle en 2 en  issue https://github.com/SistemasArtear/Filmoteca/issues/47
Procedo a cerrarlo.
