### ISSUE TITLE
FIL.10.06.Generar PP Movimientos Costeo

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#50]
Se incorporó en la grabacion de los PP'S el  insert de los movimientos contables para A (haciendo referencia a los valores cfm)
R (UNA vez que se registra el EF debe hacer referencia a su Recepcion
**NOTA: Agregada la modificacion en EA en color verde en FIL10.06****

**Comment by vivikorz** [comment]
FIL.10.06.Generar PP Movimientos Costeo AGREGADO EN VERDE

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb  ALFA
Junto con los cambios por  GIT :   **https://github.com/SistemasArtear/Filmoteca/issues/53, https://github.com/SistemasArtear/Filmoteca/issues/52, https://github.com/SistemasArtear/Filmoteca/issues/51, https://github.com/SistemasArtear/Filmoteca/issues/50, https://github.com/SistemasArtear/Filmoteca/issues/49, https://github.com/SistemasArtear/Filmoteca/issues/48, https://github.com/SistemasArtear/Filmoteca/issues/47, https://github.com/SistemasArtear/Filmoteca/issues/46**

**Comment by vivikorz** [comment]
por favor pasar a integracion asi llego a cierre definitivo y no le pierdo los datos a Axel en desarrollo, vi generación en tabla TG6001

**Comment by rscocco** [comment]
https://artear.my.workfront.com/task/view?ID=60d366e5001e3d0c995abbce5c4ead4f&commentID=60fea5760004760db3546440df138bd0&activeTab=tab-task-updates&email-source=comm

**Comment by vivikorz** [comment]
Tipo Movimiento R en PP6003 GRABO OK EN PP6002  NO LO GRABO
Tipo Movimiento A en PP6003 NO LO GRABO Y EN PP6002 LO GRABO SIN CONTRATO Y SIN SEÑAL

**Comment by axel-miller** [comment]
No se generan los pp6001 y pp6002 porque los movimientos R y A generados por costeo son distintos de los generados habitualmente por ejemplo: para los movimientos de costeo la señal se registra en TG6001.TGK05 mientras que en el resto se registra en TG6001.TGK02.
Por esto sugiero
construir una rutina que genera nuevos registros  A y R en TG6001 a partir de los de costeo
En la actualización de los pp exliuir explícitamente los generados por costeo
Ajustar la especificación al respecto si corresponde

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb ALFA
Junto con los cambios por GIT : #53, #52, #51, #50, #49, #48, #47, #46

**Comment by axel-miller** [comment]
Tambien  hay diferencia donde de graba SNKCOD en los registros, que no son de costeo, con TG6001.TGK01='A' y TG6001.TGK01='R'

**Comment by MBESCUDERO** [comment]
Modifiqué la especificación en Alfresco del FP600 para la busqueda de cuenta contable con canje o no dependiendo en los casos te titulocfm. Como la generación del asiento es común tanto para las altas como para las recepciones y anulaciones de recepción, este cambio abarca estos puentos. El cambio se verá en el documento en la parte de la subrutina FP6003
@axel-miller

**Comment by MBESCUDERO** [comment]
Para la generación de los pp's de movimientos 'A','R','BR' y 'MA' sigue siendo válido el modo en que se genera en la actualidad con la única salvedad de tener en cuenta al insertar en la tabla PP6003 en el atributo PPksnkexh el valor del TGK010 siempre que TGK10 del registro que se esta procesando tenga valor 'S' o 'N'

@axel-miller @vivikorz

**Comment by axel-miller** [comment]
Se remiten cambios respecto a movimientos R y BR

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb ALFA

**Comment by vivikorz** [comment]
Cto 2410 C13 4 ESCALAS DE 100$ 1 Exhibicion (canje S cabecera con canje N)
Cto.2378 M24 Escala de 400473 canje N cabecera Canje S
Cto.2395 M24 Escala de 440.000 Canje N cabecera canje S

Grabacion en PP6003:
select *From pp6003 WHERE IFKINT = 221 AND PPKCON = 2410;

**Comment by vivikorz** [comment]
hoy 19/8 Tomado los datos de produccion. 
Se toma como prueba básica EF del mes en curso y su correspondiente R (no incluye  tener EF de meses anteriores)
Se ingreso en prod.para agosto Cto,.2412
Hago precierre se puede ver en reporte de recepcion las R correspondientes a agosto No hay de meses pasadas
1 -
Hago precierre se puede ver en reporte de recepcion las R correspondientes a agosto No hay de meses pasadas
2395 SE010862 LA PREVIA DE LA ACADEMIA 0 Cash 440000.00 ok
2378 SE010838 LA JAULA DE LA MODA 2021 0 Cash 400473.00 ok
2412 SE010870 MAÑANISIMAS 2021 Cash 645000.00 ok Todas estas recepciones son Cash ok y la cabecera del contrato Canje y salio ok

2 -Hice cierre definitivo
a) Para contrato 2412 EN PP6003 grabo 5 R de los recibidos de manera tradicional y un R de 645000 valor escala con N en PPSNKEXH agosto. En pp6002 grabo un registro R 672565 correcto la sumatoria de todos los R. En pp6001 proveedor 14938 1.109488 IMPORTE QUE SALE DE SUMAR LOS R para ese proveedor. Por lo tanto para contrato 2412 los mov.R estan bien en las 3 tablas
b) Para contrato 2378 10 R DE 3545 TRADICIONALES Y 1 R con N en ppsnkexh de 400473 se ve correcto.
En pp6002 se ve un registro de 436923 ok
En pp6001 se ve la sumatoria tal como escribi en el caso del cto.2412 ya que es el mismo proveedor y hace sumatoria por proveedor
c) Para contrato 2395 1 registro de 440000 con N en ppsnkexh y sus restantes recepciones comunes 10 DE 3515
Para pp6002 la sumatoria de los R para ese contrato que es al momento: 475150
Para pp6001 R para esa señal M24 DE 475150 SE VE CLARAMENTE QUE toma x señal.
La recepcion comun tal como esta hoy en produccion cargado sin bajas, ni EF de meses anteriores ni modificaciones x EF lo veo bien. @sisva @MBESCUDERO @axel-miller

**Comment by rscocco** [comment]
Se toman Objetos de Alfa  sin OK y se implementan en integración,  para pruebas,  según lo solicitado.

Ya esta disponible, Gx Filmo Integracion.

**Comment by vivikorz** [comment]
ok integracion mov. R EN PP'S
Resultado de TESTING INTEGRACION PARA MOVIMEINTO R
Grabacion PP'S OK
Tomo contrato 2412 que fue cargado en el mes de agosto desde produccion.
Le agrego yo una escala de julio. Asi de esta manera tengo un EF a agosto y otro a julio.
Realizado cierre definitivo de agosto en integracion.
Se ve en pp6003 los mov R con ppsnkexh = N, UNO DE 100$ y otro de 645000 ok
Tengo 5 mov.R de 5513 1 de 645000 y 1 de 100 , estos 2 ultimos x cfm
En pp6002 tengo un EF de 645100 es correcto x que es la sumatoria de los 2 EF (645000 +100)
En PP6002 para contrato 2412 un Mov R de 672665 ok (sum de 5 * 5513 + 100 +645000) OK
En pp6002 para contrato 2412 un Mov E de 22052 ok (sum de 4 * 5513) OK

SELECT sum (ppnimpexh) from pp6003 where tvkidmov = 'R' AND IFKINT = 222 AND SNKCOD = 'M24' AND PPKPRO = 14938 = 1109588;
select *From PP6001 WHERE TVKIDmov = 'R' AND IFKINT = 222 AND SNKCOD = 'M24' AND PPKPRO = 14938 = 1109588;

@MBESCUDERO @axel-miller @sisva @yoea13 
Me quedan por probar los demas movimientos A, MA, MR

**Comment by vivikorz** [comment]
Probado cierre definitivo mov.A en desarrollo 25/8

En en pp6003 para el cto.2414 que tiene 2100 para grabar con PPSNKEXH = 'S'' no está grabando este atributo ERROR
En pp6002 espero para este contrato un registro de 3100 y graba solo 1000 o sea no suma lo de cfm
En pp6001 tampoco incluye la sumatoria del importe de cfm

Rechazo @MBESCUDERO @axel-miller

**Comment by vivikorz** [comment]
25/8 hasta hoy ok integracion generacion registros en PP6001 PP6002 Y PP6003 DE BR y R CON PPSNKEXH = N o S segun corresponda

**Comment by MBESCUDERO** [comment]
La nota del error reportado por movimiento A  en cierre definitivo , esta reportado en git 46 que es el que corresponde a la generación de los movimientos de alta. Devuelvo este issue, ya que la corrección va por issue 46
@vivikorz

**Comment by vivikorz** [comment]
Probado cierre definitivo en  integracion. OK 
cto.2395 nace en mes de abril su cabecera x 246050
y sumatoria de escalas 1420000
En agosto su cabecera pasa a 491100
y sus escalas con 1760000 mas ya que agregaron escalas
Se ven los MA uno de 246050 comun p cto2395 y el de la escala 1.760.000 grabados en pp6003, en pp6002 ok 2.006.050 y pp6001 = 2.006.050 ok cierre definitivo y grabacion tablas
@MBESCUDERO @axel-miller @sisva @yoea13

**Comment by vivikorz** [comment]
Por favor @rscocco pasar a PREPROD
@MBESCUDERO @axel-miller @sisva @yoea13

**Comment by rscocco** [comment]
Se implementa en Filmoweb Pre-productivo-.

**Comment by vivikorz** [comment]
Testing PREPROD MOVIMIENTO BR OK
1 - Tomados datos nuevos de preprod pero como no hay anulacion de EF desconfirme a mano todo el mes de junio del titulo SE10862 CTO.2395
Corro precierre.
Espero BF y BR
2- Con esos mismos datos sigo desconfirmando el mes de julio pero solo 2 dias o sea no es todo el mes
Desde reporte de anulacion de Ef o sea el reporte de BF sigue solo con junio eso es correcto
Y el reporte de mod.y baja de recibidos sigue con el de junio ya que no hay BR por julio x que no hubo BR
Eso es correcto
Procedo a realizar cierre definitivo para chequear mov.BR
select *from pp6003 where ppkcon = 2395 and ppKsnkexh = 'N' AND IFKINT = 222; SE OBSERVA REGISTRO BR X 440.000
select *from pp6002 where ppkcon = 2395 and IFKINT = 222; ok un registro de 440.000
select *from pp6001 where ppkpro = 968020 and IFKINT = 222; ok 1 registro de 440.000
Ademas se ve en cierre definitivo el reporte de BF OK
En definitivo se ve correcto tambien el reporte de baja y mod.de recibidos. Tal como en el precierre.

TESTING ALTA 
Corrida cierre definitvo en preprod.
Cargo contrato 2415 que cargue yo con esas escalas
y el contrato 2412 que se dio de alta en produccion:
Grabado en pp6003 contrato 2412 MOV A comun de 551300 y A con ppsnkexh = N DE 3225000 Y EL 2412 DE MOV.A comun de 1800 y la otra pata de 2407.
EN tabla pp6002 contrato 2415 de 4207 y el 2414 de 3776300
En tabla pp6001 PARA PROVEEDOR 149318 UN TOTAL 3776300 Y PARA PROVEEDOR 157484 SEÑAL C13 4207
OK PREPROD.

TESTING PREPROD DE MOV.R
Probado con los datos de preprod mov.R
select *From pp6003 WHERE PPkpRo = 968020 and tvkidmov = 'R' AND IFKINT = 222 AND PPKCON = 2395: se ve 1 registro de 440000 con N en ppsnkexh OK
select *From pp6003 WHERE tvkidmov = 'R' AND IFKINT = 222 AND PPKCON = 2378: se ve 1 registro de 400473 con N en ppsnkexh OK
select *From pp6003 WHERE tvkidmov = 'R' AND IFKINT = 222 AND PPKCON = 2412: 1 DE 645000 CON PPSNKEXH =N
Ninguno el contrato 2415 que se dio de alta porque no tiene EF ok

select *From pp6002 WHERE tvkidmov = 'R' AND IFKINT = 222 AND PPKCON = 2412 de 733208 ok
select *From pp6002 WHERE tvkidmov = 'R' AND IFKINT = 222 AND PPKCON = 2378 de 477018 ok
select *From pp6002 WHERE tvkidmov = 'R' AND IFKINT = 222 AND PPKCON = 2395; de 517330 ok PP6001 CON MISMO IMPORTE PARA MISMO PROVEEDOR.OK
Y EL CONTRATO 2412 Y 2378 SON DEL PROVEEDOR 14938 POR LO TANTO SE VE 1210226 SELECT *FROM PP6001 WHERE tvkidmov = 'R' AND IFKINT = 222 and snkcod = 'M24' AND PPKPRO = 14938;
Por lo tanto graba bien sus movimientos en las 3 tablas que se actualizan en cierre definitivo
Ok PREPROD SE pasar a prod.con todo el release

TESTING PREPROD MOV.MA X CAMBIO DE ESCALAS
Probado en preprod cierre definitivo se puede ver el contrato 2395
Su cabecera enterfaces anteriores valor 246050 a agosto 491100
Sus esclas de tener sumatoria 1.420.000 pasa a tener 1760.000 5 escalas mas de 440.000 cada una.
Esto genera un A de 246050 por cabecera y un MA de 1760.000 por las escalas agregadas
Se ven 2 registros en PP6003 PARA PROVEEDOR 968020 Y PPKCON = 2395
pp6002 1 solo registro para proveedor 968020y contrato 2395 de 2006050 su registro es correcto ya que es sumatoria de los 2 registros encontrados en pp6003
select *From pp6001 WHERE PPkpRo = 968020 and tvkidmov = 'MA' AND IFKINT = 222; SE VE 1 REGISTRO DE 2006050 CORRECTO.
ok preprod se pasara a prod con todo el release.
@rscocco @MBESCUDERO @axel-miller @sisva @yoea13

**Comment by rscocco** [comment]
Se implementa en Filmoweb Integracion

**Comment by rscocco** [comment]
Se implementa en servidores Gxproductivo  según solicitud :   https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556&
