### ISSUE TITLE
Generacion de asiento para llevar a sap

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#51]
[FP600_IFZ(15).odt](https://github.com/SistemasArtear/Filmoteca/files/6787118/FP600_IFZ.15.odt)
Especificacion en alfresco

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb  ALFA
Junto con los cambios por  GIT :   **https://github.com/SistemasArtear/Filmoteca/issues/53, https://github.com/SistemasArtear/Filmoteca/issues/52, https://github.com/SistemasArtear/Filmoteca/issues/51, https://github.com/SistemasArtear/Filmoteca/issues/50, https://github.com/SistemasArtear/Filmoteca/issues/49, https://github.com/SistemasArtear/Filmoteca/issues/48, https://github.com/SistemasArtear/Filmoteca/issues/47, https://github.com/SistemasArtear/Filmoteca/issues/46**

**Comment by vivikorz** [comment]
por favor pasar a integracion asi llego a cierre definitivo y no le pierdo los datos a Axel en desarrollo, vi generación en tabla TG6001

**Comment by rscocco** [comment]
https://artear.my.workfront.com/task/view?ID=60d366e5001e3d0c995abbce5c4ead4f&commentID=60fea5760004760db3546440df138bd0&activeTab=tab-task-updates&email-source=comm

**Comment by vivikorz** [comment]
Probado pero como sale mal sin señal en pp6002 ni cto. obvio aca hubo problemas

**Comment by vivikorz** [comment]
En el testing en integracion intenté dejar los datos correctos para llegar a ofcablote (pero no me puso en contrato que en co6001. tiene canje N y en titulocfm s Y LO DEJO EN LAS MISMAS CUENTAS-

**Comment by vivikorz** [comment]
Necesitaria seguir o ver en log si x dos regisros de alta en pp6003  uno cta canje (TITULOCFM)  y otro cuenta no canje (CO6001)  las va a buscar o se queda con lo encontrado en CO6001

**Comment by vivikorz** [comment]
[](url)

**Comment by vivikorz** [comment]
ESPECIFICACION CORREGIDA SE VE RESALTADA EN ROJO
 https://artear.my.workfront.com/task/view?ID=60ff278c0006fccc88ca622fbc585fa6&activeTab=tab-task-updates&commentID=60ff27a200070b3e57974bd051a04dd0&showCommentBox=true


Consiste en que la cuenta contable la tiene que buscar cuando accede a pp6003 y encuentra un 2 ppnumdet y sino en co6001, lo estaba haciendo al final y si habia apertura de tipo 2 registrs de tipo mov.A uno canje en tipocfm y otro no canje en co6001 se quedaba con el último y no se veia la diferencia de cuenta

**Comment by MBESCUDERO** [comment]
Modifiqué la especificación en Alfresco del FP600 para la busqueda de cuenta contable con canje o no dependiendo en los casos te titulocfm. Como la generación del asiento es común tanto para las altas como para las recepciones y anulaciones de recepción, este cambio abarca estos puentos. El cambio se verá en el documento en la parte de la subrutina FP6003
https://apps.canal13.artear.com.ar/share/page/site/Artear/document-details?nodeRef=workspace://SpacesStore/39179570-38d9-40d6-819e-4b3a5f629647
@axel-miller
@vivikorz

**Comment by MBESCUDERO** [comment]
Inicio programación

**Comment by MBESCUDERO** [comment]
Paso para deploy en alfa la programación correspondiente a la interfaz a Sap por recepción. 
La prueba no lo hice en local, se hará en desarrollo

**Comment by vivikorz** [comment]
Se realizo la prueba en desarrollo con interfaz de 2021/06 (ifz =220) se agregaron los registros de cfm en ifz 220 para cto.2378 y 2395 en pp6001/2/3.
[ERROR SAP .txt](https://github.com/SistemasArtear/Filmoteca/files/6985113/ERROR.SAP.txt)
Se envio txt a Mabel reportando el error visto y charlado via telefonia, Mabel procedio al arreglo el cual estará enviando nuevamente en desarrollo.

**Comment by rscocco** [comment]
a esta disponible en Filmo web Alfa

**Comment by vivikorz** [comment]
Probaré ifz con alta de contrato mes 06/2021 ifz 220.
Pongo marca de if6001.iffmescie = N
Modifico en cb6001 para señal M24 MOV.A que tengan para canje una cuenta y para no canje otra cuenta ya que hoy tienen ambos tipos de contrato la misma cuenta contable y entonces no se veria el arreglo realizado por Mable.

**Comment by vivikorz** [comment]
[
[IFZALTA.txt](https://github.com/SistemasArtear/Filmoteca/files/7000551/IFZALTA.txt)
](url)
@MBESCUDERO @axel-miller @sisva Probado en desarrolo creando para ifz 220 (06/202) los mov.de alta de contrato para sap se ve correcto. Pero no tengo otro mov.de alta comun en precierre junio para M24.

**Comment by vivikorz** [comment]
[IFZALTAREC.txt](https://github.com/SistemasArtear/Filmoteca/files/7000725/IFZALTAREC.txt)
@MBESCUDERO @sisva Probado recepcion se ve correcto y ademas comparé la parte el renglon comun con el de producion y estan igual en importe las cuentas estan correctas en funcion a las que puse  adjunto doc,
Cuando no tuvo cuenta hubo reporte de error

**Comment by rscocco** [comment]
Ya esta disponible en Filmo web Alfa

**Comment by vivikorz** [comment]
Inserto en pp6003/2/1 para contrato  2378 en ifz = 216 el alta de la sumatoria de escalas de 4805676 con ppsnkexh = N Y detalle en 2  y ademas tiene de corrida de esa fecha el mov.de A de 951345
Al ejecutar la ifz a sap de 02/2021 da erro de cta contable para alta de contrato  y segun lo que veo en CB6001 estan para tipo de MOV.A dolar FIjo  dadas de alta TANTO para canje N como canje S. O sea no deberia pedir cuenta.

Ademas sale como cuenta contable indefinida para BR ANULACION RECEPCION DE TITULOS M24 y en este caso para ninguna señal hay un mov.BR. Miro en tabla pp6003 y la ultima vez que hubo BR fue en ifz 171 y estamos en 216

**Comment by MBESCUDERO** [comment]
Ejecute en local 2 veces y no pude replicar el error , generó correctamente los asientos.
De todas formas le paso a Ricardo para deployar con mejora de logs para poder seguirlo.
Al ejecutar la interfaz a Sap, entiendo que el periodo que se indica es el 2021/02 que es el que corresponde al periodo 216 , de este modo lo ejecute y funciona.
Envío por mail mi log de ejecución local

**Comment by rscocco** [comment]
Ya esta disponible en Filmo Alfa

**Comment by vivikorz** [comment]
Preparé en pp6003 para IFZ 216 EL REGISTRO DE ALTA DEL CONTRATO 2378 TANTO PARA NO CANJE SEGUN SU CABECERA POR 951345  Y PARA LA PARTE DE CFM QUE corresponde cash 4805676
Probaré ifz con alta de contrato mes 02/2021 ifz 216.
Pongo marca de if6001.iffmescie = N
Modifico en cb6001 para señal M24 MOV.A que NO encuentre cuenta de canje y obvio no la encontro y salio reporte informando A ALTA DE CONTRATOS M24.

**Comment by vivikorz** [comment]
Probado en desarrollo interfaz de alta y recepcion estan ok cerre tareas de testing en desarollo ya que para int.y preprdo se crearan otras tareas.
Continuo generando a mano registros en tablas PP6003, PP6002 Y PP6001 DE MOV.MA para poder probar su interfaz.

**Comment by vivikorz** [comment]
Genero un MOV.MA DE 150 PARA CTO.2395
1- INSERT INTO "FILMO"."PP6003" (IFKINT, SNKCOD, PPKPRO, TVKIDMOV, PPKCON, GRKGRUPO, TTKTPOTIT, MTKNROTIT, TOKNROCAP, TOKPARTE, PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, PPNIMPEXH, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH, PPNDURMIN) VALUES ('221', 'M24', '968020', 'MA', '2395', '1', 'SE', '10862', '0', '0', '1', 'A', '0', '58', '150', '0', '0', 'A', 'CFM', '0', TO_DATE('2001-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'N', '0')

**Comment by vivikorz** [comment]
[
[ifzMACFM.txt](https://github.com/SistemasArtear/Filmoteca/files/7022575/ifzMACFM.txt)
](url)

Realizada una segunda prueba con un registro MA (normal) y otro MA con ppsnkexh = N, hace la sumatoria peroyo esperaba separacion de registros porque ademas tiene cuentas diferentes
Toda la  prueba fue hecha generando a mano para ifz 221 los registros en pp6003 (2 registros ) pp6002(1 registro) y pp6001 1 registro.
Interpreto que mi insert es correcto.

**Comment by vivikorz** [comment]
DETALLE DE PRUBA EN DESARROLLO DE BR

INSERT INTO "FILMO"."PP6003" (IFKINT, SNKCOD, PPKPRO, TVKIDMOV, PPKCON, GRKGRUPO, TTKTPOTIT, MTKNROTIT, TOKNROCAP, TOKPARTE, PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, PPNIMPEXH, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH, PPNDURMIN) VALUES ('221', 'M24', '968020', 'BR', '2395', '1', 'SE', '10862', '0', '0', '1', 'A', '0', '58', '300000', '1', '0', 'A', 'CFM', '0', TO_DATE('2001-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'N', '0')

**Comment by MBESCUDERO** [comment]
Me asigno esta tarea para corregir el error de en la interfaz a Sap correspondiente a modificación de contrato

**Comment by MBESCUDERO** [comment]
Corrijo el error y pruebo en local , funcionando bien.
Paso a Ricki para su deploy en desarrollo.
@vivikorz

**Comment by rscocco** [comment]
Ya esta disponible en Filmo Alfa

**Comment by vivikorz** [comment]
Tomado testing.
1era. Preuba Modificacion por incremento
PP6003 MA DE 150 COMUN y pp6003 MA de 100 con ppsnkexh = N  
SE VE apertura de cuentas ok. (adjunto txt)
[MAXINCREMENTO.txt](https://github.com/SistemasArtear/Filmoteca/files/7033960/MAXINCREMENTO.txt)

**Comment by vivikorz** [comment]
Interfaz Mov.A OK 
Interfaz Mov.MA OK
Interfaz Mov.R ok
Interfaz Mov.MR OK 
El detalle de las pruebas y sus txt de los ofcablotes correspondintes estan detalladas en notas anteriors
Issue ok desarrollo pero pasara a integracion junto con todo el release
@MBESCUDERO @axel-miller @sisva

**Comment by vivikorz** [comment]
OK DESARROLLO.
Pido pasaje a integración

**Comment by rscocco** [comment]
Se toman Objetos de Alfa  sin OK y se implementan en integración,  para pruebas,  según lo solicitado.

Ya esta disponible, Gx Filmo Integracion.

**Comment by vivikorz** [comment]
Luego de trabajar con cierre contable en integracion para el mes de agosto cuya interfaz es 222  corro interfaz a sap.
Salen los reportes de cuentas erróneas y le doy de alta a todas las cuentas.
Excpeto que constantemete me da error de cuenta contable para mov.BR señal M24. 
A pesar de que no hay mov.BR para ninguna señal desde ifz 171 intento dejar tal como esta en desarrollo la tabla de cuentas.
(En desarrollo no me paso estes error porque hice la generacion a mano de todo y me genere para un mes todos los mov.)
La diferencia con la corrida en integracion es que solo hice interfaz con lo creado en produccion 

 24 Aug 2021 13:22:32,278 INFO  pfp60035  [VKORZ--Tipo de Movimiento:R No CFM:     93833.00 Contrato:   2392]
24 Aug 2021 13:22:32,280 INFO  pfp60035  [VKORZ--Tipo de Movimiento:R No CFM:     29140.00 Contrato:   2372]
24 Aug 2021 13:22:32,283 DEBUG pfp60011b [VKORZ--inicio Graba cabecera, asientos sin orden de costo]
24 Aug 2021 13:22:32,283 DEBUG pfp60011b [VKORZ--Fin Graba cabecera, asientos sin orden de costo]
24 Aug 2021 13:22:32,285 DEBUG ofp60002  [VKORZ--Anulacion Titulos Recibidos BR]
24 Aug 2021 13:22:32,299 INFO  pfp60010  [vkorz--Registra errorCuenta Contable no Definida sn:M24 pgm:        0]
24 Aug 2021 13:22:32,313 DEBUG pfp60011a [VKORZ--inicio Genera_posiciÃ³n]
24 Aug 2021 13:22:32,313 DEBUG pfp60011a [VKORZ--primer new]
24 Aug 2021 13:22:32,314 DEBUG pfp60011a [VKORZ--segundo new]
24 Aug 2021 13:22:32,314 DEBUG pfp60011a [VKORZ--Fin Genera_posiciÃ³n]
24 Aug 2021 13:22:32,315 DEBUG pfp60011b [VKORZ--inicio Graba cabecera, asientos sin orden de costo]
24 Aug 2021 13:22:32,315 DEBUG pfp60011b [VKORZ--Fin Graba cabecera, asientos sin orden de cost

**Comment by rscocco** [comment]
Se Verificaron todos los objetos de FP600 se Deployaron en integración Queda Disponible para pruebas.

**Comment by MBESCUDERO** [comment]
Se verifica el pasaje a integración y se observa que hay un objeto que no corresponde a este desarrollo sino a la  definición previa  que no prosperó. Se deshicieron los cambios que no habian prosperado en su momento y quedaron solo los correspondientes a la nueva definición.
Queda liberado para probar en integración
@vivikorz

**Comment by vivikorz** [comment]
Retomado testing de interfaz a sap en INTEGRACION de los movimientos R de los contratos 2395 - 2412 - 2378 todos con parte cash y parte canje que generé cuentas diferentes en CB6001 para poder observar que asigna a cuentas correctas
M24	40	105040016 canje N
M24	50	105040015 canje N
M24	40	105040015 canje S
M24	50	105040016 canje S
[IFZRECEP.txt](https://github.com/SistemasArtear/Filmoteca/files/7041926/IFZRECEP.txt)
Adjunto TXT
Concluyo solo la parte de Recepcion

**Comment by vivikorz** [comment]
Tomo interfraz a sap de movimientos BR que suergieron a partir de desconfirmar todass las exhibiciones y de SE10862 CTO,.2395 Y POR LO TANTO HUBO BF y BR Con ppsnkexh = N

**Comment by vivikorz** [comment]
En síntesis al 25/8 OK INTEGRACION interfaz a sap de R y BR

**Comment by vivikorz** [comment]
[IFZAGOSTOINTEGRACION.txt](https://github.com/SistemasArtear/Filmoteca/files/7079966/IFZAGOSTOINTEGRACION.txt)
Con los datos de produccion habiendo hecho cierre completo e interfaz a sap. Adjunto txt.
Se ve apertura de cuentas. COmo el usuario tiene la misma cuenta se ve la apertura pero sin modf.de ctas-
Se ve tambien el asiento de MA que hasta ahora era el que faltaba
@sisva @MBESCUDERO @axel-miller @rscocco @yoea13

**Comment by vivikorz** [comment]
[DetalleImplementacionFIlmo31.8.odt](https://github.com/SistemasArtear/Filmoteca/files/7084583/DetalleImplementacionFIlmo31.8.odt)
Probdo en integracion todos los movimientos agregado tambien los de enero a julio para que se interfaceen junto al cierre de agosto.
Adjunto txt
Le modifique a mano cuentas contables en tabla CB6001 para M24 que los mov.A y Mov.Re canje vayan a una cuenta y los cash a otra asi se ve bien la diferencia, en produccion tienen todo seteado a la misma cuenta excepto los EF CON LOS E
DOY OK EN INTEGRAGRACION. @axel-miller @MBESCUDERO @rscocco @sisva @yoea13

**Comment by vivikorz** [comment]
Por favor pasar a PREPRODUCION.
@rscocco @MBESCUDERO @axel-miller @sisva @yoea13

**Comment by rscocco** [comment]
Se implementa en Filmoweb Pre-productivo-.

**Comment by vivikorz** [comment]
[preprodifz.txt](https://github.com/SistemasArtear/Filmoteca/files/7086902/preprodifz.txt)
REALIZADA PRIMERA INTERFAZ A SAP CON Recepciones, ALTAS CON CFM dado que en prod tienen las mismas cuentas se puede observar la apertura pero la misma cuenta, la modificacion del contrato 2395 que detalle en el issue de MA y ademas el contrato cargado por mi para señal C13 con CFM o sea hay CFM para diferentes señales
@MBESCUDERO @axel-miller @sisva @yoea13

**Comment by vivikorz** [comment]
Hare prueba en preprod con los datos tomados de produccion pero agregando BR producido por BF

**Comment by rscocco** [comment]
Se implementa en Filmoweb Integracion

**Comment by vivikorz** [comment]
[IFZAGOSPREPROD.txt](https://github.com/SistemasArtear/Filmoteca/files/7105179/IFZAGOSPREPROD.txt)
Probado interfaz a sap con cuentas de alta y recepcion que canje no sea igual a cash, las modifique ya que en prod si estan igual seteadas.
Di de alta a todas las cuentas que pedia la interfaz de otras señales, CAA, C13.
SE ADJUNTA TXT NRO.DE LOTE EN OFCABLOTE EN PREPROD: FI016538, FI016537 ESTE ULTIMO ES EL QUE SALIO SIN APERTURA TAL CUAL ESTARIA EN PROD. PERO CON EL 37 SE VEN LAS APERTURAS.
ok PREPROD PEDIRE PASAJE JUNTO A TODO RELEASE
@rscocco @sisva @MBESCUDERO @axel-miller @yoea13

**Comment by rscocco** [comment]
Se implementa en servidores Gxproductivo  según solicitud :   https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556&

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53559
