### ISSUE TITLE
Reportes a modificar por incluir NTC en todos los tipos de movimientos contables

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#52]
Incorporar en los siguientes reportes existentes 
Si el TituloContrato que se está leyendo tiene 

******************************
Si TGDNUM15=2
	ES_comcanje=TituloCFM.CFMCANJE
SiNo
	ES_comcanje=CO6001.comcanje
FinSi
*************************************

RFP40067 Listado de Nuevos Contratos Señal:

RFP40089  Listado de Fílmicos por Recibir -  Son aquellos titulos que fueron dados de alta Al cargar las escalas y todavia no tienen su EF  o sea se suma a por recibir los A con pprnodet = 2  
RFP40068 Listado de Fílmicos Recibidos se incorporaran los R con ppnnrodet =  2 o sea el mov.que es parejo con el EFl
RFP40092 Listado de Fílmicos por ExhibirSeñal  Son aquellos titulos que fueron dados de alta Al cargar las escalas y todavia no tienen su EF  
RFP40083 Listado de Baja / Modificación de Fílmicos Recibidos -Movimientos BR o MR  con numero detalle > 1 que se genera al realizar modificaciones en escalas de  TITULOCFM

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb  ALFA
Junto con los cambios por  GIT :   **https://github.com/SistemasArtear/Filmoteca/issues/53, https://github.com/SistemasArtear/Filmoteca/issues/52, https://github.com/SistemasArtear/Filmoteca/issues/51, https://github.com/SistemasArtear/Filmoteca/issues/50, https://github.com/SistemasArtear/Filmoteca/issues/49, https://github.com/SistemasArtear/Filmoteca/issues/48, https://github.com/SistemasArtear/Filmoteca/issues/47, https://github.com/SistemasArtear/Filmoteca/issues/46**

**Comment by vivikorz** [comment]
Cargue contrato 2403 - SE10867 de 1500 valor titulo proveedor KORZ (157484) CABECERA CASH 
ES titulo SE con 4 originales o sea 4 capitulos se esperan
Con varias escalas en la tabla titulocfm con cfmcanje = S
añomes 202101 valorcfm   100  
añomes 202102 valorcfm   200  
añomes 202103 valorcfm   300  
añomes 202104 valorcfm   400  
añomes 202105 valorcfm   500  
añomes 202106 valorcfm   600  
añomes 202107 valorcfm   700  
añomes 202108 valorcfm   800  
Recibo de los 4 originales 3 cap.1 cap 2 cap3, los caules chequeo ok
Luego exhibo 2 cap. 1 el 14/7
cap. 2 1/6






Reporte de Nuevos contratos:

**Comment by vivikorz** [comment]
Con los datos cargados y mencionados en nota anterior se puede observar:
Reporte de alta de contrato 40067

**Comment by vivikorz** [comment]
Para los reportes 
RFP40089 Listado de Fílmicos por Recibir - Tienen registro en cfm y todavia no tienen su EF 
RFP40092 Listado de Fílmicos por Exhibir - - Tienen registro en cfm y todavia no tienen su EF

**Comment by vivikorz** [comment]
RFP40089 Listado de Fílmicos por Recibir -

AL reportes existentes luego de los totales generales y antes que termine incorporar

TotalCFM= 0

Leer  Tabla Titulo CFM
Por cada Contrato+ TipoTitulo+Nro.Titulo sumar TotalCFM = ValorCFM + TotalCFM 

Una vez leida la tabla CFM para ese titulo contrato  
acceder con ese titulo Contrato  a PP6003 (ifz anteriores)
pp6003.mtknrotit =titulocfm.mtknrotit 
pp6003.ttktpotit = titulocfm.ttktpotit
para  tvkidmov = 'EF' o sea PPNMIMPEXTOT = PPNMIMPEXTOT + PPNIMPEX   

ademas (Esto se realiza para tener en cuenta tambien los EF del mes) 
Leer tabla tg para ese titulo contrato 
y si hubiera un EF en Tabla TG6001 para 
Cod Proveedor = TGk02
Contrato = Tgk03
Grupo = Tgdnum03
Tipo y nro se obtiene de Tgk06 y Tgk07.
Tgdnum01TOT =  Tgdnum01´+ Tgdnum01TOTI  

Una vez leido todos los registros para ese titulo contrato 
(ppnMIMPEXTOT + Tgdnum01TOT)  -( TOTALCFM) = IMPORTE POR RECIBIR 



FIL.10.05.07.89 Reporte Por Recibir

En el EA en propertis general escribi:
Detalle de columnas:
Cod Proveedor = TGk02
Nombre Proveedor = PRdRazSoc obtenido de PR6001 para el código de proveedor 
Contrato = Tgk03
Grupo = Tgdnum03
Titulo = Tipo y Nro de titulo completando con 0 a izquierdo y la descripcion del titulo. Tipo y nro se obtiene de Tgk06 y Tgk07. y la descripción del titulo de MT6001.MTdTitCas para tipo y nro de titulo
Fecha exhibición = Tgk09
Dolar = Tgdnum01 si moneda no es 'ARS' , moneda esta en el atributo Tgk04
Pesos = Tgdnum01 si moneda es 'ARS' , moneda esta en el atributo Tgk04

**Comment by vivikorz** [comment]
RFP40092 Listado de Fílmicos por Exhibir -

AL reportes existentes luego de los totales generales y antes que termine incorporar

TotalCFM= 0

Leer  Tabla Titulo CFM
Por cada Contrato+ TipoTitulo+Nro.Titulo sumar TotalCFM = ValorCFM + TotalCFM 

Una vez leida la tabla CFM para ese titulo contrato  
acceder con ese titulo Contrato  a PP6003 (ifz anteriores)
pp6003.mtknrotit =titulocfm.mtknrotit 
pp6003.ttktpotit = titulocfm.ttktpotit
para  tvkidmov = 'EF' o sea PPNMIMPEXTOT = PPNMIMPEXTOT + PPNIMPEX   


Leer tabla tg para ese titulo contrato 
y si hubiera un EF en Tabla TG6001 para 
Cod Proveedor = TGk02
Contrato = Tgk03
Grupo = Tgdnum03
Tipo y nro se obtiene de Tgk06 y Tgk07.
Tgdnum01TOT =  Tgdnum01´+ Tgdnum01TOTI  

Una vez leido todos los registros para ese titulo contrato 
(ppnMIMPEXTOT + Tgdnum01TOT)  -( TOTALCFM) = IMPORTE POR RECIBIR 






Detalle de columnas:
Cod Proveedor = TGk02
Nombre Proveedor = PRdRazSoc obtenido de PR6001 para el código de proveedor 
Contrato = Tgk03
Grupo = Tgdnum03
Titulo = Tipo y Nro de titulo completando con 0 a izquierdo y la descripcion del titulo. Tipo y nro se obtiene de Tgk06 y Tgk07. y la descripción del titulo de MT6001.MTdTitCas para tipo y nro de titulo
Fecha exhibición = Tgk09
Dolar = Tgdnum01 si moneda no es 'ARS' , moneda esta en el atributo Tgk04
Pesos = Tgdnum01 si moneda es 'ARS' , moneda esta en el atributo Tgk04

**Comment by axel-miller** [comment]
Se logra generar el registro para los movimientos A... sale también en el reporte de nuevos contratos .... aunque hay que ajustar el valor informado que es incorrecto

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb ALFA
Junto con los cambios por GIT : #53, #52, #51, #50, #49, #48, #47, #46

**Comment by vivikorz** [comment]
por favor pasar a integracion asi llego a cierre definitivo y no le pierdo los datos a Axel en desarrollo, vi generación en tabla TG6001

**Comment by rscocco** [comment]
https://artear.my.workfront.com/task/view?ID=60d366e5001e3d0c995abbce5c4ead4f&commentID=60fea5760004760db3546440df138bd0&activeTab=tab-task-updates&email-source=comm

**Comment by vivikorz** [comment]
DE LOS DESARROLLADOS Y PROBADOS EN INTEGRACION  ESTAN CORRECTOS EL DE ALTA DE CONTRATO, POR RECIBIR  Y POR EXHIBIR ESTAN CORRECTOS.
FALTAN PASAR A TESTING EL RECEPCION Y MODIFICACION ( IGUALMENTE ES MAS URGENTE EL RECEPCION)

**Comment by vivikorz** [comment]
AL REALIZAR CIERRE DEFINITIVO SE PUEDE VER QUE EL REPORTE EN ALTA DE CONTRATO EN VEZ DE IMPRIMIR BIEN REPITE EL IMPORTE DEL ALTA DE CONTRATO COMUN PERO QUIZAS ESO SEA POR EL MISMO MOTIVO QUE NO ESTA grabando correcto en  pp6003

**Comment by vivikorz** [comment]
Por un lado probe lo del cierre definitivo en integracion e ímprimio bien los dos renglones con el importe correcto
Veo en desarrollo ok reporte de recibidos
Con esto tengo lo basico para el cierre de julio.
Pido pasaje a integracion para poder seguir con la prueba y no modificar los datos para que axel siga con otro issue.

**Comment by rscocco** [comment]
https://artear.my.workfront.com/task/view?ID=60d366e5001e3d0c995abbce5c4ead4f&commentID=60fea5760004760db3546440df138bd0&activeTab=tab-task-updates&email-source=comm

**Comment by vivikorz** [comment]
Grabado contrato 2411 con SE10870 4 CAPITULOS RECIBIDOS. Exhibido 1 
Escalas desde junio a noviembre cargadas 2021 cargadas
Espero alta de contrato 5100 ok + 1800 clasicos OK
Recepcion 1 
Por recibir (3)
Por exhibir (3)

**Comment by vivikorz** [comment]
en el caso de reporte de Recibidos me pone tantos recibidos como exhibiciones tenga, Yo en junio hice 3 exhibiciones pero obvio en reporte de EXHIBICIONES POR COSTO FIJO HAY UNA ESO ES CORRECTO, Por lo tanto yo espero una recepcion por esa EF, y por lo que veo a medida que aumento exhibiciones aumenta la recepcion pero no son EF son E
@axel-miller . veras en mis reportes de integracion lo que detallo. EF pone 1 y es correcto. No se como saca las 3 recepciones.

**Comment by axel-miller** [comment]
Agregar a especicacion FIL.10.04.Grabar Temporal(FP40053w) 
Modificaciones  por https://github.com/SistemasArtear/Filmoteca/issues/31

Esto es buscar si el movimiento a grabar no esta previamente generado
HAY_Previos='N'
If &Tipo_movimiento='EF' or &Tipo_movimiento='BF'or &Tipo_movimiento='R'// agrego 'R' Filmoteca_0049_20210729_ACM//Filmoteca 0031 ACM 20210319
    Buscar_Registros_Previos
Endif

If HAY_Previos='N'
	GRABAR Nuevo registro
Endif

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb ALFA
Junto con los cambios por GIT : #53, #52, #51, #50, #49, #48, #47, #46

**Comment by rscocco** [comment]
https://artear.my.workfront.com/task/view?ID=60d366e5001e3d0c995abbce5c4ead4f&commentID=60fea5760004760db3546440df138bd0&activeTab=tab-task-updates&email-source=comm

**Comment by axel-miller** [comment]
cambios incluidos en ultimo pasaje

**Comment by vivikorz** [comment]
Por Recibir:
Por cada titulo_contrato_grupo_Señal cuyo TituloCFM.cfmestado = A 
  TotalEscala = VALORCFM+ TOTALESCALA
  Con ese TITULOESCALA INGRESAR A PP6003 Y Sumar los ttktpoti = EF y restar los BF  DE INTERFACES  ANTERIORES  O (TG6001.TTKTPOMOV = EF OR RESTAR SI EN tg6001 hubiera un BF) ESTO LLEVARLO A TOTALXRECIBIR
Una vez leidos todos los registros de titulocontratoseñalgrupo
TotalEscala- TotalxRECIBIR = total importe a imprimir

**Comment by MBESCUDERO** [comment]
Documento los cambios que se deben programar en reporte de por recibir (FP40089) y por exhibir (FP40090)
[Cambios_reporte_FP40089.txt](https://github.com/SistemasArtear/Filmoteca/files/6946843/Cambios_reporte_FP40089.txt)
[Cambios_reporte_FP40090.txt](https://github.com/SistemasArtear/Filmoteca/files/6946844/Cambios_reporte_FP40090.txt)
@axel-miller 
@vivikorz 
Libero para programación

**Comment by vivikorz** [comment]
Se modifican txt.para que tome  tg6001.tgk10 ='S' o 'N' 
[Cambios_reporte_FP40090.txt](https://github.com/SistemasArtear/Filmoteca/files/6955792/Cambios_reporte_FP40090.txt)

**Comment by vivikorz** [comment]
Se modifican txt ya que al buscar tipo movimiento A en TG6001 
[Cambios_reporte_FP40089-2.txt](https://github.com/SistemasArtear/Filmoteca/files/6968989/Cambios_reporte_FP40089-2.txt)
[Cambios_reporte_FP40090.txt](https://github.com/SistemasArtear/Filmoteca/files/6968990/Cambios_reporte_FP40090.txt)
 por error dice TGK01'R' Y DEBE decir A'

**Comment by axel-miller** [comment]
Se remiten cambios respecto a Filmicos por recibir y Recibidos

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb ALFA
Junto con los cambios por GIT : #53, #52, #51, #50, #49, #48, #47, #46

**Comment by vivikorz** [comment]
Datos de prueba
Contrato 2378 mov.de A 4805676 EN PP6003 
Hasta junio ingresado mov.R 2402838 A en pp6003 mov.ingresados directamente para ifz.anteriores

Otro contrato ingresado en el mes es el 2410 con sumatoria de 4 escalas cada una de  100 canje SI   
En julio hay mov.de EF para cto.2378 (400473) y para cto.2410 (100)


El titulo contratado en 2378  tiene mov.EF y R con tkg10 = N  ok

El titulo contratado en 2410 tiene mov.EF y R con tkg10= S OK 
(No tiene mov.A x que no esta hecho pero igual deberia funcionar).  

Resultado de las pruebas en desarrollo del reporte 40089(por recibir) 
Para contrato 2378 espero 2002365 y dice 2402839 (o sea no incorpora el R de 400473 del mes de julio.
Contrato 2410 deberia poner 300 y pone 400 o sea no estaria restando el R del TG 
No estaría incluyendo el mov.R con tkg10= N o S segun corresponda

En reporte Por Exhibir
Contrato 2410  el titulo SE010870 V1.13 dice cash y la parte que corsesponde al titulocfm es canje (EN TG lo veo bien grabado)
Contrato 2378 el mismo problema dice en 0 en la parte de titulocfm y deberia tener 2002365

El reporte RFP40068 de titulos recibidos ok

**Comment by axel-miller** [comment]
Se avanzó con el reporte Por Recibir... se continua con el reporte Por Exhibir

**Comment by axel-miller** [comment]
Se remiten los Cambios a Alfa para su verificacion

**Comment by vivikorz** [comment]
1 Reportes titulos por exhibir el importe sale bien pero lo que no esta tomando es el atributo de tituloCFM.cfmcanje = N ya que en el reporte se ve que dice canJE y es cash.

**Comment by axel-miller** [comment]
Se remiten los Cambios

**Comment by rscocco** [comment]
ya esta disponible en filmoweb Alfa

**Comment by vivikorz** [comment]
Trabajando con:  http://jbossdes.artear:8080/Filmo/#

**Comment by vivikorz** [comment]
Vi correcto el reporte de Por Recibir - Por Exhibir  y Recibidos (pero todo queda sujeto a que si hago cierre definitivo y con 2EF de meses diferentes solo graba una y x lo tanto ahi se altera el reporte, se come una R x que no registra el Mov.EF)
@MBESCUDERO @axel-miller depende de  https://github.com/SistemasArtear/Filmoteca/issues/47 para que todo ande correcto

**Comment by vivikorz** [comment]
Tomado los datos de produccion. Se ingreso en prod.para agosto Cto,.2412
Hago precierre se puede ver en reporte de recepcion las R correspondientes a agosto No hay de meses pasadas
Se visualizan en TG6001 los 3 registros R con grabacion en tgk10= N y es correcto ya que esta parte del contrato es cash o sea canje = N

1 -
Hago precierre y cierre se puede ver en reporte de recepcion las R correspondientes a agosto No hay de meses pasadas
2395 SE010862 LA PREVIA DE LA ACADEMIA 0 Cash 440000.00 ok
2378 SE010838 LA JAULA DE LA MODA 2021 0 Cash 400473.00 ok
2412 SE010870 MAÑANISIMAS 2021 Cash 645000.00 ok Todas estas recepciones son Cash ok y la cabecera del contrato Canje y salio ok

**Comment by vivikorz** [comment]
[Cambios_reporte_FP40089-(3).txt](https://github.com/SistemasArtear/Filmoteca/files/7039330/Cambios_reporte_FP40089-.3.txt)
[Cambios_reporte_FP40090(3).txt](https://github.com/SistemasArtear/Filmoteca/files/7039332/Cambios_reporte_FP40090.3.txt)

**Comment by axel-miller** [comment]
Se remitencambios respecto Cambios_reporte_FP40090(3).txt y Cambios_reporte_FP40089-(3).txt

**Comment by rscocco** [comment]
ya esta disponible en filmoweb Alfa

**Comment by vivikorz** [comment]
Probado en desarrollo Alta de contrato existe un contrato 2412 cargado por el usuario y se ve correcto tanto la parte de canje como cash
Y cargue un contrato proveedor Korz nro.2414 2100 SUM ESCALAS EN TABLA TITULOCFM CORRECTO Y 1000 CORRESPONDIENTE A ALTA DEL TITULO CONTRATO 

[VKORZ_NuevosContratos_2021824_249337.pdf](https://github.com/SistemasArtear/Filmoteca/files/7041824/VKORZ_NuevosContratos_2021824_249337.pdf)

**Comment by axel-miller** [comment]
Se remiten los cambios para Alfa e Integracion

**Comment by rscocco** [comment]
​ya esta deployado en ALFA

**Comment by vivikorz** [comment]
@rscocco por favor pasar a integracion este útlimo cambio que te remitio @axel-miller asi yo sigo en integracion. Y el y @MBESCUDERO

**Comment by MBESCUDERO** [comment]
Se corrige solo lo referido a los importes del contrato 2395 en reporte de Baja y Modificacion Contrato.
Se pasa la corrección a Ricki para su deploy en alfa e integración 
@rscocco @vivikorz

**Comment by rscocco** [comment]
​ya esta deployado en ALFA e  Integracion.

**Comment by vivikorz** [comment]
Reporte de nuevos contratos de precierre  OK en integracion
Adjunto pdf.  
[VKORZ_NuevosContratos_2021830_727973.pdf](https://github.com/SistemasArtear/Filmoteca/files/7079723/VKORZ_NuevosContratos_2021830_727973.pdf)

**Comment by vivikorz** [comment]
Pasar a PREPROD.
@rscocco @MBESCUDERO @axel-miller @sisva @yoea13

**Comment by rscocco** [comment]
Se implementa en Filmoweb Pre-productivo-.

**Comment by vivikorz** [comment]
Tomados datos de produccion. 
PRECIERRE AGOSTO 
Cargue un nuevo contrato : Señal C13 2415 SE10873 Proveedor Korz 3 escalas 707 800 900 = 2407  y su cabecera 1800 se ve correcto en reporte Ademas del contrAto 2412 que viene de produccion se ve correcto. 
a) Reporte alta de contrato produccion contra preproduccion se ve correcte mas lo de cfm  
b) Reporte Titulos por Recibir se ve correcto cto 2415  que cargue recien y no tuvo EF ni recepciones comunes  tiene en por recibir el importe de 1800 + 2407 de escalas.
Cto.2378 saldo por recibir de CFM correcto alta 4805676 a julio - recepciones x EF 2803311 - la recepcion x ef de agosto 400473 arroja total de 1601892 la pata de x recibir comun da igual que en el reporte sacado por la mañana en produccion
CTO.2395 1760000 DE LA MODIFICACION  YA QUE NO HABIA POR RECIBIR A JULIO CONSUMIDO - 440000= 1.320.000OK Y LA PARTE DE COMUN DA IGUAL QUE EL REPORTE DE PRODUCCION SACADO ESTA MAÑANA
CTO 2412 OK 2580000 PATA CFM Y LA PATA NO CFM DA IGUAL QUE EL DE PRODUCCION
c) Reporte Titulos x Exhibir, contrato 2415 solo la pata de cfm 2407 ya que no fue recibido y por lo tanto no en sus saldos por exhibir sin cfm no hay
2395 y 2378 los saldos por exhibir de pata cfm se ven bien y los no cfm tienen diferencia con produccion pero es logico porque se ve que confirmaron algunos capitulos y por eso ahora en preprod no los tengo por exhibir y si hoy temprano en produccion  
Reporte baja y modificacion de contrato para Canal 13 que no hice nada en especial en preprod se ve igual que en prod y en M24 la diferencia es por el contrato2395 que ademas de tener modificacion de cabecera contrato tiene Modificacion x agregar escalas 1760000 5 de 440000 ok

**Comment by vivikorz** [comment]
Reporte por recibir y por exhibir sale en cierre definitivo mal y bien en precierre
[PRECIERRE_Por_Exhibir_2021831_790266.pdf](https://github.com/SistemasArtear/Filmoteca/files/7086520/PRECIERRE_Por_Exhibir_2021831_790266.pdf)
[DefintivoKORZ_Por_Exhibir_2021831_451328.pdf](https://github.com/SistemasArtear/Filmoteca/files/7086521/DefintivoKORZ_Por_Exhibir_2021831_451328.pdf) LO MISMO SUCEDE CON LOS POR RECIBIR
PODRAN VER EN CONTRATO 2.395 DEFINITIVO DICE 880000
Y EN PRECIERRE 1320000
El correcto es el precierre 
Por ejemplo tengo EN PP6003 mov.A 1420000 con snkexh = N  y R de 1420000
este mes ingresan MA 1.760.000 y tiene un EF de 440.000 o sea en precierre sale  1320.000 correcto pero en cierre definitivo pone 880.000 como si estuviera otra vez restando 440.000

en cto 2378 tiene su A a julio de 4805676 y R a julio de 2803311 en agosto hay un EF 400473 en precierre sale 1601892 correcto y en cierre definitivo sale 1,201,419.00 que como podran calcular es lo que salia en precierre bien menos otra vez un EF de 400473 (quizas este tomando el tg y ya tuvo grabado en pp lo de agosto)
@MBESCUDERO @axel-miller 
Es

**Comment by vivikorz** [comment]
hoy 1/9 copio datos en preprod desconfirmando todas las exhibiciones de junio de SE10862 CTO.2395 de esta forma obtendre BR originados de BF o sea de anulacion de Ef
Corro precierre adjunto Reporte
[VKORZ_Baja_Mod_Recibidos_202191_434812.pdf](https://github.com/SistemasArtear/Filmoteca/files/7090691/VKORZ_Baja_Mod_Recibidos_202191_434812.pdf)

**Comment by axel-miller** [comment]
Se remiten cambios a ALFA

**Comment by rscocco** [comment]
​ya esta deployado en ALFA

**Comment by vivikorz** [comment]
TOMO TESTING EN DESA.

**Comment by vivikorz** [comment]
Probando en desa.
Hoy copie datos en preprod. 8.00 Tire precierre. Para obtener los reportes
Tire precierre en prod.  Para obtener Reportes
Copie datos en desa y tire precierre.
Comparo en Precierre el reporte Por Recibir. Se ven las señales C13, INT, CVR igual. Comparé produccion, lo sacado esta mañana en preprod y lo sacado en desa
Además se ven agregados en desa los tres tituloscontratoados  con sus saldos: 

2395 debe tener 1.320.000 ok
2378 debe tener 1.601.892 ok
2412 debe tener 2.580.000 ok
Estos saldos corresponden a su alta + modificacion - R tanto del tg como del pp.con tgk10 = N

**Comment by rscocco** [comment]
​ya esta deployado en  INTEGRACION

**Comment by vivikorz** [comment]
Copiados datos en integracion corrridos sql de implementacion. Comienzo  testing en integracion corriendo precierre

**Comment by vivikorz** [comment]
Copiados los datos nuevamente en integracion corridos los sql de implementacion
Triro precierre en integr

**Comment by rscocco** [comment]
Se implementa en Filmoweb Integracion

**Comment by vivikorz** [comment]
[VKORZ_Por_Recibir_202192_519474int def.pdf](https://github.com/SistemasArtear/Filmoteca/files/7101894/VKORZ_Por_Recibir_202192_519474int.def.pdf)
[VKORZ_Por_Exhibir_202192_519474.pdf](https://github.com/SistemasArtear/Filmoteca/files/7101895/VKORZ_Por_Exhibir_202192_519474.pdf)

**Comment by vivikorz** [comment]
[VKORZ_Por_Recibir_202192_519474int def.pdf](https://github.com/SistemasArtear/Filmoteca/files/7101896/VKORZ_Por_Recibir_202192_519474int.def.pdf)
[VKORZ_Por_Exhibir_202192_519474.pdf](https://github.com/SistemasArtear/Filmoteca/files/7101897/VKORZ_Por_Exhibir_202192_519474.pdf)
[VKORZ_Recibidos_202192_519474.pdf](https://github.com/SistemasArtear/Filmoteca/files/7101898/VKORZ_Recibidos_202192_519474.pdf)
[VKORZ_Por_Recibir_202192_519474.pdf](https://github.com/SistemasArtear/Filmoteca/files/7101899/VKORZ_Por_Recibir_202192_519474.pdf)
[VKORZ_Por_Exhibir_202192_575852.pdf](https://github.com/SistemasArtear/Filmoteca/files/7101900/VKORZ_Por_Exhibir_202192_575852.pdf)

**Comment by vivikorz** [comment]
[preproprecierre_Por_Exhibir_202192_736746.pdf](https://github.com/SistemasArtear/Filmoteca/files/7102107/preproprecierre_Por_Exhibir_202192_736746.pdf)
[preproprecierre_Por_Recibir_202192_736746.pdf](https://github.com/SistemasArtear/Filmoteca/files/7102108/preproprecierre_Por_Recibir_202192_736746.pdf)
Reportes en preprod adjunto los del problema. El resto siguen bien
Ejecuto cierre definitivo

**Comment by rscocco** [comment]
ya esta en filmo alfa

**Comment by rscocco** [comment]
Ya esta en integracion

**Comment by rscocco** [comment]
Ya esta en preprod

**Comment by rscocco** [comment]
Se implementa en servidores Gxproductivo  según solicitud :   https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556&
