### ISSUE TITLE
Trabajar con modificacion de valores escalas para MA

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#53]
En FIL.10.Cierre Contable Tratamiento de Costeos 

* **SE CREO FIL.10.00.00 Procesar modificacion Valor Escalas CFM****

**Comment by vivikorz** [comment]
CASO DE USO NUEVO ESCRITO EN NEGRO PORQUE ES NUEVO

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb  ALFA
Junto con los cambios por  GIT :   **https://github.com/SistemasArtear/Filmoteca/issues/53, https://github.com/SistemasArtear/Filmoteca/issues/52, https://github.com/SistemasArtear/Filmoteca/issues/51, https://github.com/SistemasArtear/Filmoteca/issues/50, https://github.com/SistemasArtear/Filmoteca/issues/49, https://github.com/SistemasArtear/Filmoteca/issues/48, https://github.com/SistemasArtear/Filmoteca/issues/47, https://github.com/SistemasArtear/Filmoteca/issues/46**

**Comment by vivikorz** [comment]
por favor pasar a integracion asi llego a cierre definitivo y no le pierdo los datos a Axel en desarrollo, vi generación en tabla TG6001

**Comment by rscocco** [comment]
https://artear.my.workfront.com/task/view?ID=60d366e5001e3d0c995abbce5c4ead4f&commentID=60fea5760004760db3546440df138bd0&activeTab=tab-task-updates&email-source=comm

**Comment by MBESCUDERO** [comment]
**Se redefine la modificación , se detalla a continuación los cambios en EA:**
En CU FIL.10.Cierre Contable Tratamiento de Costeos:
Se agregan los CU:
CU FIL.10.04.Grabar Temporal
CU FIL.10.07.Modificacion CFM
También se debe comentar la lógica de la acción Procesar CFM

CU FIL.10.01.01.Procesar CFM o Mixto se modifican las siguientes acciónes, ver que esta indicado en rojo el cambio con el nro de git53
Cambios en acción "Procesar movimiento de tipo 'EF'"
La acción "Actualizar Marcas ajuste y Contabilizado" no va, se deshace en este punto.
Cambios en acción "Generar Anulación movimiento tipo BF"

Se libera para programación
@axel-miller @vivikorz

**Comment by axel-miller** [comment]
los cambios aqui realizados afectan a 
https://github.com/SistemasArtear/Filmoteca/issues/47
https://github.com/SistemasArtear/Filmoteca/issues/48

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
ya esta disponible en Filmoweb ALFA

**Comment by axel-miller** [comment]
En CU FIL.1O.Cierre Contable se agrega acción "Actualizar marcas Titulocfm"
En CU FIL.10.01.Procesar Coste CFM o Mixto, en las acciones siguientes ver donde dice git 53 no va
- Registrar Movimiento EF
- Generar Anulacion movimiento tipo 'BF'
-

**Comment by axel-miller** [comment]
Se remiten a Alfa Los cambios Por
En CU FIL.1O.Cierre Contable se agrega acción "Actualizar marcas Titulocfm"
En CU FIL.10.01.Procesar Coste CFM o Mixto, en las acciones siguientes ver donde dice git 53 no va
    Registrar Movimiento EF
    Generar Anulacion movimiento tipo 'BF'
Queda pendiente el resto

**Comment by rscocco** [comment]
Ya esta disponible en Filmoweb ALFA

**Comment by vivikorz** [comment]
Tomo la prueba  con datos copiados de produccion. Habiendo agregado los datos de implementacion para ctos.2378 y 2395
Hay de produccionun nuevo cto.2412 con TituloCFMpara agosto.

**Comment by axel-miller** [comment]
Se remiten cambios por 
CU FIL.10.01.01.Procesar CFM o Mixto 
Cambios en acción "Procesar movimiento de tipo 'EF'"
La acción "Actualizar Marcas ajuste y Contabilizado" no va, se deshace en este punto.
queda pendiente el resto

**Comment by rscocco** [comment]
Se implementan cambios en Filmoweb ALFA

**Comment by vivikorz** [comment]
Tomo testing en desarrollo, no cargo nada ya que los datos de produccion tienes valores que me sirven para probar.

**Comment by rscocco** [comment]
Se rectifican por problemas de pasaje,  ya está disponible en Filmo  ALFA

**Comment by vivikorz** [comment]
continuo con prueba solo de los CU especificados en pasaje

**Comment by vivikorz** [comment]
Tomado en desa Registrar Movimiento EF
Tomo datos de produccion y al cto.2412 que fue creado para agosto le cargo escala en julio y exhibicion en julio asi tengo EF de Julio y AGosto
En TG se pueden ver 2 EF y 2 R para julio y agosto respectivamente
Me queda correr  CU FIL.1O.Cierre Contable se agrega acción "Actualizar marcas Titulocfm"

**Comment by axel-miller** [comment]
luego de
CU FIL.10.04.Grabar Temporal
CU FIL.10.07.Modificacion CFM
También se debe comentar la lógica de la acción Procesar CFM


Por los cambios en 
FP40053w FIL.10.04.Grabar Temporal
tembien se actualizo
FP40053 FIL.10.Cierre Contable Tratamiento de Costeos
FP40053a FIL.10.01.Procesar Coste CFM o Mixto
FP40053b FIL.10.02.Procesar Costeo Rating
FP40053c FIL.10.03.Procesar Costeo Excedente Duracion
FP40053f Procesar Excedente Duracion
FP40053k FIL.10.07.Modificacion CFM
FP40053y Actualizar Marcas de TituloCFM

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
ya está disponible en Filmo ALFA

**Comment by vivikorz** [comment]
Tomo issue. 
Caso prueba contrato 2395 al  mes de julio y forzado en pp6003 Mov.A con  ppsnkexh = N de  1420000 en ifz 221 
Su alta de contrato fue en ifz 219 Mov.A comun de 246050
En agosto se agregan 20210/08 2021/09 al 2021/11 por 440000

**Comment by axel-miller** [comment]
Se remiten Cambios

**Comment by rscocco** [comment]
Ya esta disponible en Filmoweb ALFA

**Comment by vivikorz** [comment]
No se ve bien el reporte
RFP40083 Listado de Baja / Modificación de Fílmicos Recibidos
Se ven dos registros con importes erroneos

**Comment by vivikorz** [comment]
Este issue fue probado en desa e int y por dicho motivo @MBESCUDERO envio @rscocco un mail solicitando: "El objeto FP40021 y lo consolides en los entornos de desarrollo e integración. Ya que lo veo en folder git_19 y en teoria eso no deberia haber llegado nunca a desarrollo.
Por favor pasanos tambien el export a Axel y a mí. 
Por favor cuando lo hayas hecho , avisale a Vivi." YA QUE no se veia correcto y no fue algo que hayan tocado para este release.

**Comment by rscocco** [comment]
Se consolida en modelo Filmo Alfa el Objeto del modelo Preproductivo, para dejar sin efecto los cambios realizados en el Objeto modificado : pFP40021  por el  git : https://github.com/SistemasArtear/Filmoteca/issues/19    

Ya esta deployada en servidor Gxdes .

**Comment by vivikorz** [comment]
Probado precierre integracion. Adjunto reporte
[VKORZ_Baja_Mod_Contratos_2021830_302097.pdf](https://github.com/SistemasArtear/Filmoteca/files/7079818/VKORZ_Baja_Mod_Contratos_2021830_302097.pdf)
Se prueba cierre definitivo para ver la grabacion de pp's

**Comment by vivikorz** [comment]
Por favor pasar a PREPRODUCCION
@rscocco @MBESCUDERO @axel-miller @sisva @yoea13

**Comment by rscocco** [comment]
Se implementa en Filmoweb Pre-productivo-.

**Comment by vivikorz** [comment]
Probado en preprod cierre definitivo se puede ver el contrato 2395
Su cabecera enterfaces anteriores valor 246050 a agosto 491100
Sus esclas de tener sumatoria 1.420.000 pasa a tener 1760.000 5 escalas mas de 440.000 cada una. 
Esto genera un A de 246050 por cabecera y un MA de 1760.000 por las escalas agregadas
Se ven 2 registros en PP6003 PARA PROVEEDOR 968020 Y PPKCON = 2395
pp6002 1 solo registro para proveedor 968020y contrato 2395 de 2006050 su registro es correcto ya que es sumatoria de los 2 registros encontrados en pp6003
select *From pp6001 WHERE PPkpRo = 968020 and tvkidmov = 'MA' AND IFKINT = 222; SE VE 1 REGISTRO DE 2006050 CORRECTO. 
ok preprod se pasara a prod con todo el release

**Comment by rscocco** [comment]
Se implementa en Filmoweb Integracion

**Comment by rscocco** [comment]
Se implementa en servidores Gxproductivo  según solicitud :   https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556&
