### ISSUE TITLE
Mostrar Programas Habilitados para la señal

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#55]
Hoy en Armado programacion, Horarios programas  toma de la tabla SGV.PGW001 y  al tomar esta tabla permitio de manera erronea dar de alta un progrma que no estaba habilitado para dicha señal
Por lo tanto se pide:
El sistema debe validar que el programa esté habilitado para la  misma a través de la Unidad de Negocio. Para ello, debe existir un registro en la tabla SGV.MAOCOSTOS con código formado por la Unidad de Negocios más el código del Programa (sin los dígitos correspondientes a la repetición/segmento).
Además, la Unidad de Negocios debe estar relacionada a la señal en cuestión(señal del start). Dicha relación se encuentra registrada en la tabla SGV.MARELACION, habilitado, para la señal (MAREKSENIAL) y unidad de negocios dada (MAREKUNEGOCIO).
Cabe aclarar, que el programa también debe estar habilitado (en SGV.PGW001)

SELECT *
FROM PGW001 PROG, MAOCOSTOS COS, MARELACION REL 
WHERE
  COS.MAOCKORDENCOSTO =  REL.MAREKUNEGOCIO || trim(to_char(PROG.PGWKCOD/100, '0999999'))
  AND COS.MAOCMTIPO='P'  --Orden de costo para Programa
  AND REL.MAREESTADO IS NULL -- Relación habilitada
  AND PROG.PGWMINHAB = 'N' -- El programa NO está inhabilitado
  AND REL.MAREKSENIAL=[Cod. Señal] 
  AND PROG.PGWKCOD = [ID Programa]

  Deberia realizarse la modificacion en :
PR_LEVANTAR_LISTA_PROGRAMAS
PR_LISTAR_PROGRAMA
PR_LEVANTARPH6001_DES )

**Comment by vilinares** [comment]
Se realizo la modificación de los procesos FIL_PKG_ARMADO_PROGRAMACION, FIL_PKG_DESCONFIRMAR_PROG, FIL_PKG_FP320, FIL_PKG_FP370 en ambiente de desarrollo

**Comment by vivikorz** [comment]
Di de alta a mano en tabla PGW001 EL codigo de pgm 6768700 con descripcion VIVI
Entro a horario de programas pido descripcion VIVI y lo trae y me permite ingresar horario. Eso no seria correcto
Mirando logprocesos se puede observar:

73735671	FIL_PKG_FP320	PR_ALTAPH6001	"ORA-20004: ##YA EXISTE EL PROGRAMA A DAR DE ALTA##
ORA-06512: at "FILMO.FIL_PKG_FP320", line 511
"
73735670	FIL_PKG_FP320	FN_EXISTE_PROGRAMA	Comienzo fn_existe_programa (Señal = C13 - Codigo Programa = 6768700
73735669	FIL_PKG_FP320	PR_ALTAPH6001	Inicio PR_ALTAPH6001 ( Señal: C13 Codigo: 6768700 Dia: 1 Desde: 0 Hasta: 0)
73735668	FIL_PKG_FP320	PR_LISTAPROGRAMAS_DES	Fin PR_LISTAPROGRAMAS_DES

**Comment by vilinares** [comment]
Se modifico la rutina PR_LISTAPROGRAMAS_DES que no estaba en la lista de las modificaciones solicitadas originalmente. Ya se encuentra en ambiente de desarrollo.

**Comment by vivikorz** [comment]
73735974	FIL_PKG_FP320	PR_LISTAPROGRAMAS	Inicio PR_LISTAPROGRAMAS ( Codigo: )
73735973	FIL_PKG_FP320	PR_LISTAPROGRAMAS	Fin PR_LISTAPROGRAMAS
73735972	FIL_PKG_FP320	PR_LISTAPROGRAMAS	Inicio PR_LISTAPROGRAMAS ( Codigo: )
73735971	FIL_PKG_FP320	PR_LISTAPROGRAMAS	Fin PR_LISTAPROGRAMAS
73735970	FIL_PKG_FP320	PR_LISTAPROGRAMAS	Inicio PR_LISTAPROGRAMAS ( Codigo: )
73735969	FIL_PKG_FP320	PR_LISTAPROGRAMAS	Fin PR_LISTAPROGRAMAS
73735968	FIL_PKG_FP320	PR_LISTAPROGRAMAS	Inicio PR_LISTAPROGRAMAS ( Codigo: )
73735967	FIL_PKG_FP320	PR_LEVANTARPH6001_DES	Fin PR_LEVANTARPH6001_DES
73735966	FIL_PKG_FP320	PR_LEVANTARPH6001_DES	Inicio PR_LEVANTARPH6001_DES ( Señal: C13 Descripcion: 6768700)
73735965	FIL_PKG_FP320	PR_LEVANTARPH6001_DES	Fin PR_LEVANTARPH6001_DES
73735964	FIL_PKG_FP320	PR_LEVANTARPH6001_DES	Inicio PR_LEVANTARPH6001_DES ( Señal: C13 Descripcion: )
73735963	FIL_PKG_FP320	PR_LEVANTARPH6001	Fin PR_LEVANTARPH6001
73735962	FIL_PKG_FP320	PR_LEVANTARPH6001	Inicio PR_LEVANTARPH6001 ( Señal: C13 Codigo: 6768700)
73735961	FIL_PKG_FP320	PR_LEVANTARPH6001	Fin PR_LEVANTARPH6001
73735960	FIL_PKG_FP320	PR_LEVANTARPH6001	Inicio PR_LEVANTARPH6001 ( Señal: C13 Codigo: )
73735959	FIL_PKG_ARMADO_PROGRAMACION	PR_LEVANTAR_LISTA_PROGRAMAS	Fin PR_LEVANTAR_LISTA_PROGRAMAS
73735958	FIL_PKG_ARMADO_PROGRAMACION	PR_LEVANTAR_LISTA_PROGRAMAS	Fin PR_LEVANTAR_LISTA_PROGRAMAS
73735957	FIL_PKG_ARMADO_PROGRAMACION	PR_LEVANTAR_LISTA_PROGRAMAS	Inicio PR_LEVANTAR_LISTA_PROGRAMAS
73735956	FIL_PKG_ARMADO_PROGRAMACION	PR_LEVANTAR_LISTA_PROGRAMAS	Inicio PR_LEVANTAR_LISTA_PROGRAMAS
73735955	FIL_PKG_FP320	PR_LISTAPROGRAMAS_DES	Fin PR_LISTAPROGRAMAS_DES
73735954	FIL_PKG_FP320	PR_LISTAPROGRAMAS_DES	Inicio PR_LISTAPROGRAMAS_DES ( Descripcion: )
73735953	FIL_PKG_FP320	PR_LISTAPROGRAMAS_DES	Fin PR_LISTAPROGRAMAS_DES
73735952	FIL_PKG_FP320	PR_LISTAPROGRAMAS_DES	Inicio PR_LISTAPROGRAMAS_DES ( Descripcion: VIVI)

Tenemos en pgw001 el codigo 6768700 con descr.VIVI
Lo busque y no lo trajo eso es correcto
@vilinares @sisva
