### ISSUE TITLE
CONFIRMAR SIN AMORTIZACION 

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#58]
ORA-06502: PL/SQL: numeric or value error: character string buffer too small
ORA-06512: at "FILMO.FIL_PKG_CONF_SIN_AMORT", line 260

Ampliar a varchar 300

**Comment by vilinares** [comment]
Se realizo la corrección en Ambiente de Desarrollo

**Comment by vivikorz** [comment]
cargado programacion p 12/7 la familia ingals y confirmado ok pido pasaje a preprod

**Comment by vilinares** [comment]
Se crea TAG_FILMO_20210802_1-12-HOTFIX_PL para su pasaje a Preprod

**Comment by rscocco** [comment]
Se implementa en la Base Oracle pre-productiva los documentos descargados de :  **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-08-02)%20%2358**
Y registrados con el TAG PL:    **TAG_FILMO_20210802_1-12-HOTFIX_PL**

Detalle de ejecución : 
Package FIL_PKG_CONF_SIN_AMORT compilado
Package body FIL_PKG_CONF_SIN_AMORT compilado

**Comment by vivikorz** [comment]
ok preprod. Copiado datos y cofirmado el dia 7/7 y 5/7 sin amorticacion

**Comment by vivikorz** [comment]
ok preprod pido pasae a prod

**Comment by rscocco** [comment]
El DBA implemento en la Base Oracle Productiva los documentos descargados de : **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-08-02)%20%2358**
Y registrados con el TAG PL: **TAG_FILMO_20210802_1-12-HOTFIX_PL**

Según solicitud :   **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53378**
