### ISSUE TITLE
 RFP400F4 - Resumen de movimientos

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#59]
Descripción | Por  ùnica vez se deberà poner en la lìnea de saldos x Recibir PARA SOLO M24  un moviento que sume 2.842.838 en importe en pesos....con la leyenda  "Mov.cto.2395 y 2378 CFM".  Al saldo que arroje este listado se deberà SUMAR  2.842.838 (pesos) y este saldo recièn ahì grabarse en IF6002...  

Descripción | Por  ùnica vez se deberà poner en la lìnea de saldos x Exhibir  PARA SOLO M24  un moviento que sume 2.842.838 en importe en pesos....con la leyenda  "Mov.cto.2395 y 2378 CFM".  Al saldo que arroje este listado se deberà SUMAR  2.842.838 (pesos) y este saldo recièn ahì grabarse en IF6002...  

Una vez hecho el cierre de JULIO  se deberà sacar esta lìnea (se cargarà un ISSUE para dicha acciòn..) 

Hubo un mantis hace tiempo 10839 que tubo algo similar

**Comment by axel-miller** [comment]
Se remiten los Cambios

**Comment by rscocco** [comment]
Ya esta disponible en Filmoweb ALFA

Objeto modificado :   FP400F4

**Comment by vivikorz** [comment]
@axel-miller @MBESCUDERO @sisva Este issue lo probaré en desarrollo pero vale aclarar que tenia los calculos de las recepciones ralizadas sin julio o sea para implentar las R no contabilizadas de 01/06 ya que en julio ya iban a formar parte del saldo. Debo agregarle al saldo el R correspondiente a julio (400473 cto 2398 + 400000 cto 2395).

**Comment by vivikorz** [comment]
Por implementar en agosto se deben corregir los montos ya que el alta de contrato de 2395 es 1420000 y su recepcion a julio inclusive es 1420000 dif.de alta  menos recepciones es 0
Por contrato 2378 A es 4805676 menos recepciones a julio inclusive es 2002365
Por dicho motivo pido correccion de este issue (no habia estado rechazado, sólo se modifica por incluir un mes mas en recepcion


Descripción | Por ùnica vez se deberà poner en la lìnea de saldos x Recibir PARA SOLO M24 un moviento que sume 2.842.838 en importe en pesos....con la leyenda "Mov.cto.2395 y 2378 CFM".  Al saldo que arroje este listado se deberà SUMAR 2.002.365 (pesos) y este saldo recièn en cierre definitivo debe grabarse en IF6002...

Descripción | Por ùnica vez se deberà poner en la lìnea de saldos x Exhibir PARA SOLO M24 un moviento que sume 2.002.365 en importe en pesos....con la leyenda "Mov.cto.2395 y 2378 CFM". Al saldo que arroje este listado se deberà SUMAR 2.002.365 (pesos) y este saldo recièn en cierre definitivo  grabarse en IF6002...

Una vez hecho el cierre de agosto se deberà sacar esta lìnea (se cargarà un ISSUE para dicha acciòn..)

Hubo un mantis hace tiempo 10839 que tubo algo similar

**Comment by rscocco** [comment]
Se toman Objetos de Alfa  sin OK y se implementan en integración,  para pruebas,  según lo solicitado.

Ya esta disponible, Gx Filmo Integracion.

**Comment by axel-miller** [comment]
Se remiten los cambios segun nota 23/08

**Comment by rscocco** [comment]
Ya esta disponible en Filmoweb ALFA

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Ya esta disponible en Filmoweb ALFA

**Comment by vivikorz** [comment]
Por favor Ricardo pasar a integracion asi veo grabacion en tablas y no tomo esquema que utilizan mis compañeros.
Gracias.
@rscocco @axel-miller

**Comment by rscocco** [comment]
Ya esta disponible en Filmoweb Integracion

**Comment by vivikorz** [comment]
Probado precierre y emision de reporte resumen ok.
Adjunto pdf
[VKORZ_Resumen_Mov_2021830_727973.pdf](https://github.com/SistemasArtear/Filmoteca/files/7079804/VKORZ_Resumen_Mov_2021830_727973.pdf)

**Comment by vivikorz** [comment]
Por favor pasar a PREPRODUCCION.
@rscocco @axel-miller @MBESCUDERO @sisva @yoea13

**Comment by rscocco** [comment]
Se implementa en Filmoweb Pre-productivo-.

**Comment by vivikorz** [comment]
Resumen en precierre en preprod
Se ve agregada la linea solicitada y correcto hecho el calculo
@axel-miller @MBESCUDERO @sisva @yoea13

**Comment by vivikorz** [comment]
Probado en preprod cierre definitivo controlado y visto la grabacion en tabla IF6002 QUE SOLO sucede en cierre defintivo
Grabo M24 correcto y las otras señales tambien para ifz 222

**Comment by rscocco** [comment]
Se implementa en Filmoweb Integracion

**Comment by rscocco** [comment]
Se implementa en servidores Gxproductivo  según solicitud :   https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556&

**Comment by rscocco** [comment]
Se implementa en servidores **Gxproductivos** el proyecto **Filmoweb.war**

Seg+un solicitud :   **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53606**
