### ISSUE TITLE
SFA04.05.WS_FACTURACION_GC_FILMOTECA

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#6]
SINO ENCUENTRA ASIENTOSAP NO DEBE EJECUTARSE
Y SUCEDIO QUE SE EJECUTO SIN HABER ASIENTOSAP Para 2020/10    

//Leer ASIENTOSAP buscando una interfaz de tipo filmo, con estado activo
Hay_asiento_contable ='N'
Leer ASIENTOSAP
	donde Tipo='F'
	          y Estado ='A'
Si encuentra
	Empresa = ASIENTOSAP.empresa
	Periodo  = ASIENTOSAP.periodo
	Nro_Interno = ASIENTOSAP.NroInterno
	XML_envio = ASIENTOSAP.Xmlenvio
	XML_Wsenvio = ASIENTOSAP.Xmlwsenvio
	Hay_asiento_contable ='S'
Finsi

POR FAVOR CRONEARLO COMO ESTAN LOS DEMAS PL

**Comment by vilinares** [comment]
Se crea el proceso CRON_FILMO_SAP que llama al PKG_WS_FACT_GC_FILMO.PR_WS_FACTURACION. Dentro del PKG se hace la validación que en ASIENTOSAP exista comprobantes en Estado A para procesar. Igualmente coloque en el proceso que verifique primero antes de hacer la llamada al PKG. Ya se encuentra en Desarrollo para probar

**Comment by vilinares** [comment]
Ya se encuentra en Desarrollo para probar

**Comment by vivikorz** [comment]
BUSCO EL CRON EN GSG-DES Y EJECUTO

  Begin­

 CRON_FILMO_SAP;

­ end;

No puedo leer nada, en los logs que me sea significativo

desde sql se ve Conectando a la base de datos GSGV - DES.

El proceso ha terminado.

Desconectando de la base de datos GSGV - DES. 18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /contratos_a
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /facturas_ev
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /wsv_ext_a2
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /wsv_a
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /sfaweb_a
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /host-manager
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /facturas
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /dwhof_a
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /wsv_aora
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /wsv_ext_a
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /tablero_alfa
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /filmoweb_a
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /consumidores_alfa
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /sesiones
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /aopweb
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /facturasext_ev
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /wsv_ext_alfa2
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /menu_a
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /wsv_ext_des
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /manager
18 Nov 2020 08:16:00 [scheduler_Worker-5] ERROR com.googlecode.psiprobe.beans.ResourceResolverBean  - Failed to lookup: users
javax.naming.NameNotFoundException: Name UserDatabase is not bound in this Context
	at org.apache.naming.NamingContext.lookup(NamingContext.java:770)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:153)
	at org.apache.naming.factory.ResourceLinkFactory.getObjectInstance(ResourceLinkFactory.java:97)
	at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:304)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:793)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:140)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:781)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:140)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:781)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:153)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:137)
	at javax.naming.InitialContext.lookup(InitialContext.java:351)
	at com.googlecode.psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:148)
	at com.googlecode.psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:128)
	at com.googlecode.psiprobe.beans.ContainerWrapperBean.getPrivateDataSources(ContainerWrapperBean.java:172)
	at com.googlecode.psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:161)
	at com.googlecode.psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:45)
	at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:276)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:260)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:86)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:529)
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /sfaweb_x_a
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /probe
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /sgvwebext_des
18 Nov 2020 08:16:00 [scheduler_Worker-5] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading GLOBAL resources

Pero no me queda claro si el proceso no se corre yA que no habria registros en asiento sap con F  Y

**Comment by vivikorz** [comment]
Por favor de que manera podria ver que el cron no se ejecuta

**Comment by vilinares** [comment]
Los mensajes se colocaron en LOG_PROCESOS de GSGV, porque el cron no envía correo. Se debe realizar el siguiente query en GSGV:
select * from log_procesos
where log_proceso = 'CRON_FILMO_SAP'

**Comment by vivikorz** [comment]
ok desarrollo pido pasaje a integracion.

**Comment by vilinares** [comment]
Se realizo pasaje a Integración

**Comment by vivikorz** [comment]
1 -Trabaje en integracion con lote 202005 nro.136 le puse A y lo que estaba con E para filmo de ese período le puse empresa 20, ejecute cron_filmo_sap y se ve en logs su corrida y en log_prcoeso de gsgv-int.  
Se ve la corrida ejecutada: Inicio armar XML Empresa:1 Periodo:202005 Nro. Interno:136
Se ve otro registro de otro asiento ejecutada Invoco WS:1 Periodo:202005 Nro. Interno:181 Fecha: 18/11/2020 o sea correcto.
Vuelvo a ejectuar y esta vez no deberia hacer nada ya que no hay nada para ejecutar
Conectando a la base de datos GSGV - INT.
El proceso ha terminado.
Desconectando de la base de datos GSGV - INT. se ve ejecutado y en http://gxint.artear:82/logs/wsv_i_log4j.log no se ven registros procesados eso e correcto. y en logprocessos: No se encontro asientos para procesar en AsientoSap

**Comment by vivikorz** [comment]
OK INTEGRACION

**Comment by vilinares** [comment]
Se crea TAG_FILMOTECA_20201118_1-10_PL para su pasaje a Preprod

**Comment by rscocco** [comment]
Se implementa en la Base oracle preproductiva el documento descargado de : **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2020-11-18)%20-%20%236**  y registrado con el tag PL :    **TAG_FILMOTECA_20201118_1-10_PL**

**Comment by vivikorz** [comment]
Se ejecutó el cron schedulado tal como fue pedido viernes 12hs
Fin de Proceso de CRON_FILMO_SAP Mensaje: Error
No se encontro asientos para procesar en AsientoSap
Inicio de Proceso de CRON_FILMO_SAP
Por lo tanto se probo corriendo el cron con datos, sin datos y schedulado
Lo que me queda por hacer es pasarlo a prod pero luego de ver bien cuando debería ejecutarse en prod.
Lo vere con Escudero, Scocco
Y cargare glpi de pasaje

**Comment by rscocco** [comment]
El DBA  implementa en la Base oracle Productiva el documento descargado de : **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2020-11-18)%20-%20%236** y registrado con el tag PL : **TAG_FILMOTECA_20201118_1-10_PL**   y solicitado por glpi :    **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=51255**
