### ISSUE TITLE
Armar Asientos  Alta y  Recepcion de CFM (por unica vez)

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#61]
Deberán enviarse a sap los asientos de alta de contrato por CFM de los contratos 2395 y 2378 que no fueron enviados a sap en las interfaces de enero y julio 2021. Fecha donde fueron creados los contratos.

 Propuesta se correrá el glpi de implementacion sobre pp6003 para interfaz ant ifz anterior antes de fin de agosto para poder tener los datos para realizar precierres.  De esta manera se podrán generar los mov.de la ifz del mes de agosto y reportes. 
Luego de generado el cierre definitivo de agosto y antes de la interfaz de agosto estos mov. agregados deberemos ponerlos en ifz de agosto y asi iria el asiento que el usuario espera @MBESCUDERO @axel-miller

**Comment by rscocco** [comment]
Se implementa en servidores Gxproductivo  según solicitud :   https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556
