### ISSUE TITLE
(pl) Pkg FIL_PKG_FP210 (filtro adicional en PP6003)

### ISSUE THREAD

**Issue by MBESCUDERO** [SistemasArtear/Filmoteca#62]
En el pkg del asunto se solicita agregar el siguiente filtro "PPKSNKEXH <>'S' y PPKSNKEXH <>'N' " en las busquedas sobre la tabla PP6003.
La lectura de la tabla PP6003 se encuentra en 2 lugares

**Comment by vilinares** [comment]
Se realizo la corrección solicitada en ambiente de Desarrollo

**Comment by vivikorz** [comment]
Probe en desarrollo y por lo que pude ver la rutina que se toco se llama pr_F01AltaFP21003 y es llamada desde ingreso de materiales.
Entre a desarrollo y con el titulo SE0838 cto.2378 que tiene ya su registro con ppsnkexh = N y filtro correcto. Y ademas busque que no tenga N y filtro y tambien vi

pr_F01AltaFP21003                        
pr_grillaFP21005 
pr_seleccionarFP21003


  FOR reg_pp IN (SELECT *
                                         FROM pp6003
                                        WHERE mtknrotit = reg.mtknrotit
                                          AND ttktpotit = reg.ttktpotit
                                          AND grkGrupo  = reg_gr.grkGrupo
                                          AND ppkcon    = reg_gr.cokCon
                                          AND snkcod    = reg_gr.snkcod
                                          AND (tvkidmov  = 'BR' OR
                                              (tvkidmov  = 'MR' AND ppmTpoMdf = 'B'))
                                          AND ppksnkexh NOT IN ('S','N')  -- Issue #62 VL 31/08/2021
                                     
Pido pasaje a integracion. @vilinares @MBESCUDERO @sisva

**Comment by vilinares** [comment]
Se realizo pasaje a INT

**Comment by vivikorz** [comment]
Tomado en integracion. Desde ingreso de materiales, visualice la filmolog  se ve que llama a PR_F01ALTAFP21003

se puede ver en pl           FOR reg_pp IN (SELECT *
                                         FROM pp6003
                                        WHERE mtknrotit = reg.mtknrotit
                                          AND ttktpotit = reg.ttktpotit
                                          AND grkGrupo  = reg_gr.grkGrupo
                                          AND ppkcon    = reg_gr.cokCon
                                          AND snkcod    = reg_gr.snkcod
                                          AND (tvkidmov  = 'BR' OR
                                              (tvkidmov  = 'MR' AND ppmTpoMdf = 'B'))
                                          AND ppksnkexh NOT IN ('S','N')  -- Issue #62 VL 31/08/2021
                                      )
                        LOOP

Inserte capitulos desde remito al cokcon = 2412 cap.100 y 1800 y grabao correcto. Este tituo tiene A con ppsnkex = N y sin nada

**Comment by vilinares** [comment]
Se crea TAG_FILMO_20210831_1-13_P para su pasaje a Preprod

**Comment by rscocco** [comment]
Se implementa en oracle preprod el documento descargado de :   **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-08-31)%20%2362**  y registrados con el TAG PL :    **TAG_FILMO_20210831_1-13_P**

Detalle de Ejecución :  
Package FIL_PKG_FP210 compilado
Package body FIL_PKG_FP210 compilado

**Comment by vivikorz** [comment]
Probado en preprod 
desde log procesos se puede ver que entra a 
PR_F01ALTAFP21003
ademas visto en preprod el                         



                        FOR reg_pp IN (SELECT *
                                         FROM pp6003
                                        WHERE mtknrotit = reg.mtknrotit
                                          AND ttktpotit = reg.ttktpotit
                                          AND grkGrupo  = reg_gr.grkGrupo
                                          AND ppkcon    = reg_gr.cokCon
                                          AND snkcod    = reg_gr.snkcod
                                          AND (tvkidmov  = 'BR' OR
                                              (tvkidmov  = 'MR' AND ppmTpoMdf = 'B'))
                                          AND ppksnkexh NOT IN ('S','N')  -- Issue #62 VL 31/08/2021

o sea cumple con el arreglo pedido
Ok preprod 
Se pasara a prod junto con todo el release
@MBESCUDERO @vilinares @rscocco @sisva @yoea13

**Comment by rscocco** [comment]
El DBA implementa en base Productiva los documentos descargados de :
https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-08-31)%20%2362 y registrados con el TAG PL : TAG_FILMO_20210831_1-13_P

Según solicitud : https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53556&
