### ISSUE TITLE
RFP400 Resumen de movimientos.

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#63]
Se pide deshacer lo hecho en issue 59 
https://github.com/SistemasArtear/Filmoteca/issues/59
Dado que era un ajuste a impactar con el cierre de agosto y no debe estar en los proximos cierres
Sacar linea tanto de la parte Por Recibir y de la linea Por Exhbir.

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
ya esta diponible en filmoweb  alfa

**Comment by vivikorz** [comment]
Copiados datos de produccion en desarrollo.
Corrido precierre mes 09/2021. Como no tenia datos de produccion grabados para M24 al mes de setiembre
Confirme una exhibicion de la Jaula de la Moda, para ver esta exhibicion en titulos recibidos OK
Titulo por exhibir ok comparo setiembre con cierre de agosto y se ve la diferencia en los CFM de 400473 eso es corecto.
Titulo por recibir sale correcto igual al por exhibir el saldo del 2378 y el 2395 y 2412 salen como agosto ya que no tuvieron exhibiciones
En resumen se ve el renglon de lo recibido x cfm ok
Adjunto pdf testing desarrollo se puede ver que no sale mas la linea de ajsute cto.o 2395 2378 
Grabo correcto en if6002
[desa_Resumen_Mov_202199_952199.pdf](https://github.com/SistemasArtear/Filmoteca/files/7137034/desa_Resumen_Mov_202199_952199.pdf)
Pido pasaje a integracion
@MBESCUDERO @rscocco @axel-miller @sisva @yoea13

**Comment by rscocco** [comment]
Ya esta disponible en Filmoweb de Integracion

**Comment by vivikorz** [comment]
TOMO TESTING EN INTEGRACION

**Comment by vivikorz** [comment]
Tomados datos previos al cierre de agosto en integracion
Corrido precierre se ve el recumen sin la linea o sea esta correcto
[integraionResumen_Mov_202199_889379.pdf](https://github.com/SistemasArtear/Filmoteca/files/7139416/integraionResumen_Mov_202199_889379.pdf)ADJUNTO PDF
Pido pasaje a preprod

**Comment by rscocco** [comment]
ya esta disponible en preprod

**Comment by vivikorz** [comment]
Copiando datos de produccion en preprod

**Comment by vivikorz** [comment]
1 - Hecho precierre en preprod. Sin ningun dato agregado se ve resumen sin linea de ajuste, es correcto. 
2 - Cargo para el 3/9 un capitulo de la jaula de la moda para ver su R x  EF

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53606
