### ISSUE TITLE
PR_CONFIRMAR_TODO

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#64]
El boton confirmar deberá incluir que además el titulo_contrato que se esta confirmando 

Especificado en 
Confirmacion Programacion Con Costeo
Boton confirmar todo

**Comment by vilinares** [comment]
Revisando los procesos detecto el error, para corregirlo se necesita modificar el proceso pr_tmp_confirmar y colocar parte de esta rutina en una nueva, que será invocada por Java antes de realizar la llamada de pr_tmp_confirmar , antes de iniciar el loop donde se encuentra la rutina antes mencionada.

**Comment by vilinares** [comment]
Rodrigo me informo que esto seria lo que habría que hacer:

En el método procesarConfirmacionGrillaProgramacion de la clase ConfirmarProgramacionServiceImpl está el bucle que llama al código que ejecuta el stored procedure pr_tmp_confirmar (this.confirmarProgramacionDao.procesarRegistrosGrillaProgramacion(procesarConfirmacionRequest);)
En cuanto al truncate de la tabla temporal, desde java lo que habría que hacer es ejecutar directamente el sql correspondiente (algo como lo que se indica acá: 
https://stackoverflow.com/questions/2900016/how-to-truncate-a-table-with-spring-jdbctemplate)

**Comment by vilinares** [comment]
Ya se encuentra en ambiente de Desarrollo la modificación de PL

**Comment by vivikorz** [comment]
Necesito un java para que me indique  en que momento graba en la tabla grilla excedente y grilla rating ya que con el boton "lapicito" ya deberia grabar y asi dice el EA y x lo que veo graba solo con el boton confirmar

**Comment by vilinares** [comment]
Cuando este asignado el JAVA, que me avise para que aclaremos la manera de funcionar la pantalla, porque creo que algo nos esta faltando para coordinar los eventos

**Comment by rodrigo-fernandez** [comment]
Se realizaron los cambios indicados en los comentarios para que la aplicación funcione como se esperaba.

Se deployó una nueva versión de Filmoteca en desarrollo (jboss des).

Tag: **[TAG_FILMOTECA_V1.14_20211109_1-7-24](https://github.com/SistemasArtear/Filmoteca/releases/tag/TAG_FILMOTECA_V1.14_20211109_1-7-24)**

**Comment by vivikorz** [comment]
Tomada la señal canal 13 TITULO lA NOCHE DE MIRTHA LEGRAND DEL MES DE NOVIEMBRE. 
Cargadas las duraciones excedentes.
Confirmado luego desde dias posteriores ok

**Comment by vivikorz** [comment]
BEGIN pr_copia_datos_produccion('FILMO'); END;

**Comment by vivikorz** [comment]
Tomado los datos de produccion
EL TITULO SE10846 CTO.2381 Para 6/11 excedente 6
 EL TITULO SE10846 CTO.2381 Para 13/11 excedente 13
EL TITULO SE10846 CTO.2381 Para 20/11 excedente 20
EL TITULO SE10847 CTO.2381 Para 7/11 excedente 7
 EL TITULO SE10847 CTO.2381 Para 14/11 excedente 14
EL TITULO SE10847 CTO.2381 Para 21/11 excedente 21
Luego me situe en dia 23 para poder confirmar todo
Tabla  GRILLA_COSTEOPOREXC se ve para esos titulos el excedente cargado ok
TABLA GT6001 SE VE TODO CONFIRMADO HASTA EL DIA 23/11
TABLA HF6001 SE VE EL HISTORIAL DE LO CONFIRMADO HOY 24/11 USUARIO VKORZ

**Comment by rodrigo-fernandez** [comment]
Se estuvo viendo el problema, y para solucionarlo se modificó el stored procedure **pr_listar_programacion** para que muestre los valores almacenados en la **TMP_CONFIRMAR**.

**Comment by vivikorz** [comment]
ok desarrollo por favor @rodrigo-fernandez y @vilinares pasar a integracion

**Comment by vilinares** [comment]
Se realizo pasaje a Integración

**Comment by vivikorz** [comment]
@rodrigo-fernandez cuando puedas pasa a int lo de java. Gracias

**Comment by rodrigo-fernandez** [comment]
Se deployó la nueva versión de Filmoteca en integración (jboss int).

Tag: **[TAG_FILMOTECA_V1.14_20211109_1-7-24](https://github.com/SistemasArtear/Filmoteca/releases/tag/TAG_FILMOTECA_V1.14_20211109_1-7-24)**

**Comment by vivikorz** [comment]
Tomo mes de diciembre para la señal Canal 13
Dado que no tengo para año 2022 contratos con CFM. Tomo el contrato 2381 que es mirtha legrand, voy desconfirmando dias para volver luego a cargar el excedente y realizar confirmar todo
Tomo SE10846 PARA DIA 4/12 LE PONGO 4 EN EXCEDENTE.
SE10847 DIA 5/12 LE PONGO 5 EN EXCEDENTE
Tomo SE10846 PARA DIA 11/12 LE PONGO 11 EN EXCEDENTE.
SE10847 DIA 12/12 LE PONGO 12 EN EXCEDENTE
Tomo SE10846 PARA DIA 18/12 LE PONGO 18 EN EXCEDENTE.
SE10847 DIA 19/12 LE PONGO 19 EN EXCEDENTE

**Comment by vivikorz** [comment]
Lo que puedo observar en confirmar todo (y quizas sea en confirmar de manera individual) que en tabla Historico_GrillaExcedente la duracion excedente la pone en 0. Ver que trabaje con el 5/12 cto.2381 desconfirmé porque venia de produccion confirmado y luego cargue duracion excedente. En grilla costeo excedente la grabo correcto y no asi en el historico
@vilinares @rodrigo-fernandez @sisva

**Comment by vivikorz** [comment]
Tomo SE10846 PARA DIA 4/12 LE PONGO 44 EN EXCEDENTE.
SE10847 DIA 5/12 LE PONGO 55 EN EXCEDENTE

Se puede observar que graba en gt6001 grilla excedente e histórico correctamente

PIDO PASAJE A PREPROD Y ADEMAS ESte último arreglo de historico de excedente y rating volcarlo en desa.
Gracias @vilinares @sisva

**Comment by vilinares** [comment]
Se realizo corrección en proceso ya que faltaba actualizar los históricos

**Comment by vilinares** [comment]
Se crea TAG_FILMO_20220113_1-14_PL para su pasaje a Preprod

**Comment by rscocco** [comment]
Se implementa en la Base Oracle preproductiva el documento descargado de :   **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2022-01-13)%20%2364**   registrado con el TAG PL :    TAG_FILMO_20220113_1-14_PL01

Detalle de ejecución : 
Package FIL_PKG_CONFIRMAR_PROG compilado
Package body FIL_PKG_CONFIRMAR_PROG compilado

**Comment by rscocco** [comment]
Estimada @vivikorz ,  **no tenes asignado el issue,**  por  que estoy trabajando en el
si hicistes las pruebas te adelantastes.   En cuanto este disponible te lo asigno como siempre.

Ya desde ayer estoy en contacto con @vilinares  para interiorizarme del pasaje,  porque no hay un issue de implementacion que detalle que es necesario pasar para esta Version de FILMO.     Hoy me contacte con @rodrigo-fernandez Por la migracion de java al GHit y su configuracion.     @sisva,  en unos minutos estará terminado y asignado a @vivikorz

**Comment by rscocco** [comment]
-  Se deploya en servidores **Jbosspreprod01 y 02** el proyecto **Filmo.war**  
Registrado con el TAG Java :  **TAG_FILMOTECA_V1.14_20211109_1-7-24**

-  Se implementa en la **Base Oracle preproductiva** el documento descargado de :   **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2022-01-13)%20%2364**   registrado con el TAG PL :    **TAG_FILMO_20220113_1-14_PL01**

Detalle de ejecución : 
Package FIL_PKG_CONFIRMAR_PROG compilado
Package body FIL_PKG_CONFIRMAR_PROG compilado


@vivikorz  -  ahora podes comenzar las pruebas.

**Comment by vivikorz** [comment]
Tome datos de produccion y copie en preprod
Tome dias 4 5 6 11 12 13 y 18 de diciembre y desconfirme todos sus titulos Luego
cargue excedente para contrato 2381 dia 4 exc.4
dia 5 exc.5
dia 11 exc.11
dia 12 exc. 12
DIA 18 exc.18
Me quedo luego en dia 18 y doy confirmar todo y lo esperado es que deje la marca de confirmado S en GT. ESO ES CORRECTO O SEA no se rompio nada de lo anterior
En HF graba las desconfirmaciones y las confirmaciones anda OK (no se rompio).
Tabla GrillaPorExedente Marca ajuste en S (porque desconfirme) y marca de Contabilizado en N porque eran exhbiciones de diciembre y ya estamos en enero eso es correcto, por lo tanto no se rompio tampoco y graba todos los exedentes desde el dia de confrirmacion 18/12 y confirmar todo hsasta exhibiciones del 4/12 eso es correcto.
O sea primero cargué los excedentes todos y luego desde el ultimo dia confirme y funcionó
