### ISSUE TITLE
Reporte Por Recibir formato .csv

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#69]
[PBARBERI_Por_Recibir_202196_769495(5).pdf](https://github.com/SistemasArtear/Filmoteca/files/7198202/PBARBERI_Por_Recibir_202196_769495.5.pdf)
[PBARBERI_Por_Recibir_2108.csv](https://github.com/SistemasArtear/Filmoteca/files/7186225/PBARBERI_Por_Recibir_2108.csv)
El reporte en formato csv. para el contrato 2378 2412 2395 salen mal los originales, si se compara con el pdf
adjunto csv que salio en cierre definitivo de agosto y que esta en portal diferente a pdf
Adjunto los dos reportes tanto el csv. como el pdf. 
El erroneo es el csv.

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
ya esta disponible en Filmo alfa

**Comment by vivikorz** [comment]
Ejecutando cierre definitivo mes 09/2021

**Comment by vivikorz** [comment]
@
[VKORZ_Por_Recibir_2021921_498274.pdf](https://github.com/SistemasArtear/Filmoteca/files/7205295/VKORZ_Por_Recibir_2021921_498274.pdf)
[VKORZ_Por_Recibir_2110.csv](https://github.com/SistemasArtear/Filmoteca/files/7205296/VKORZ_Por_Recibir_2110.csv)
Para poder ejecutar la generacion del reporte x recibir es neceario correr cierre definitivo
No veo la correccion en csv. Si comparo valores de los 3 contratos 2378 2395 2412 la parte del cash no son iguales el pdf al csv.
2378 SE010838 LA JAULA DE LA MODA 2021 Cash a perpetuidad 06/01/2021 1.201419.00 dato del pdf  Dato correcto
el csv adjunto para este titulo la parte de cash dice 79.716.150 dato incorrecto
@axel-miller @MBESCUDERO @sisva @yoea13

**Comment by vivikorz** [comment]
Volvere a copiar datos a desarrollo para que @axel-miller corra 09/2021

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Ya está disponible en filmoweb ALFA

**Comment by rscocco** [comment]
Ya esta disponible en Filmoweb de Integracion.

**Comment by vivikorz** [comment]
Probado en integracion el reporte de titulos x recibir version csv. Se ven correctas las columnas y su importe
[VKORZ_Por_Recibir_2109.txt](https://github.com/SistemasArtear/Filmoteca/files/7237632/VKORZ_Por_Recibir_2109.txt)

**Comment by vivikorz** [comment]
PIDO PASAJE A PREPROD
@rscocco @axel-miller @sisva @yoea13 @MBESCUDERO

**Comment by rscocco** [comment]
Ya esta disponible en Filmoweb de pre-produccion.

**Comment by vivikorz** [comment]
tomo preprod

**Comment by vivikorz** [comment]
[VKORZ_Por_Recibir_2109 (2).csv](https://github.com/SistemasArtear/Filmoteca/files/7253958/VKORZ_Por_Recibir_2109.2.csv)
[VKORZ_Por_Recibir_2021929_018405 (2).pdf](https://github.com/SistemasArtear/Filmoteca/files/7253959/VKORZ_Por_Recibir_2021929_018405.2.pdf)
Copiado datos en preprod, realizado ok operativo insertando a mano en if6001
Luego corrido cierre definitivo con :: 
http://gxpreprod.artear:82/filmoweb/servlet/hfp45001?VKORZYmYtMTYzMjkzNTg1NDkwN

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53672&

**Comment by rscocco** [comment]
Se implementa en servidores **Gxproductivo** el proyecto **Filmoweb.war.** 

Según solicitud :   **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53672**
