### ISSUE TITLE
RFP40092 Reporte x Exhbibir en pdf y    RFP400d8   por Exhibir en csv.             

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#73]
Por favor deshacer lo realizado para estos 2 reportes   en issue https://github.com/SistemasArtear/Filmoteca/issues/52

(ojo que en ese issue habia mas reportes. Solo deshacer lo realizado para RFP40092 y RFP400d8)
@sisva @yoea13 @MBESCUDERO

**Comment by vivikorz** [comment]
DESAHACER LO QUE SE AGREGO:
 Cambios reporte FP40090:

Para cada TN6001 que analiza el reporte
1- buscar si tiene CFM
	Leer TituloCFM 
		donde cokcon = tn6001.cokcon	
		y Grkgrupo 	 = tn6001.grkgrupo
		y Snkcod	 = tn6001.snkcod
		y ttktpotit  = tn6001.ttktpotit
		y mtknrotit	 = tn6001.mtknrotit
	
	Si encuentra al menos 1
		seguir con el punto 2
	Finsi
2- Buscar las altas , recepciones y anulaciones que existan para el titulo
del punto 1 y calcular si hay recepciones pendientes, que será el resultado
del importe de las altas menos las recepciones mas las anulaciones
	2.a - Se buscan y se sumarizan las altas contabilizadas para eso se recorre PP6003 buscando altas de CFM 
		  de periodos previos
		  
		  Sumar en total_alta_pp PP6003.ppnimpexh
						donde snkcod = tn6001.snkcod
						y ppkcon	 = tn6001.cokcon
						y grkgrupo	 = tn6001.grkgrupo
						y ttktpotit  = tn6001.ttktpotit
						y mtknrotit	 = tn6001.mtknrotit
						y tvkidmov 	 = 'A'
						y ppksnkexh	 = 'S' o 'N'
						
	2.b - Se buscan las altas para el titulo cfm que se producen en este cierre en la tabla TG
	
		  Sumar en total_alta_tg  tg6001.tgdnum02
						donde tguusrtmp = usuario
						y tgmwrk = wrkstn
						y tgfdte = Hoy
						y TGhtme = HoraN6
						y TGK01	 = 'A'
						y tg6001.tgk10 ='S' o 'N' 
						
	2.c - Se buscan las recepciones contabiliza para eso se recorre PP6003 buscando recepciones CFM de periodos previos
		
			Sumar en total_recibido_pp PP6003.ppnimpexh 
						donde snkcod = tn6001.snkcod
						y ppkcon	 = tn6001.cokcon
						y grkgrupo	 = tn6001.grkgrupo
						y ttktpotit  = tn6001.ttktpotit
						y mtknrotit	 = tn6001.mtknrotit
						y tvkidmov 	 = 'R'
						y ppksnkexh	 = 'S' o 'N'
	
	2.d - Se buscan las recepciones del titulo cfm que se hacen en este cierre buscando en TG6001
		  Sumar en total_recibido_tg tg6001.tgdnum02
						donde tguusrtmp = usuario
						y tgmwrk = wrkstn
						y tgfdte = Hoy
						y TGhtme = HoraN6
						y TGK01	 = 'R'
						y tg6001.tgk10 ='S' o 'N' 
	
	2.e - Se buscan y suman las anulaciones del titulo cfm de periodos previos buscando en PP6003
			Sumar en total_anulado_pp PP6003.ppnimpexh 
						donde snkcod = tn6001.snkcod
						y ppkcon	 = tn6001.cokcon
						y grkgrupo	 = tn6001.grkgrupo
						y ttktpotit  = tn6001.ttktpotit
						y mtknrotit	 = tn6001.mtknrotit
						y tvkidmov 	 = 'BR'
						y ppksnkexh	 = 'S' o 'N'
	
	2.f - Se buscan y suman las anulaciones del titulo cfm que se hacen en este periodo buscando en TG6001
		  Sumar en total_anulado_tg tg6001.tgdnum02
						donde tguusrtmp = usuario
						y tgmwrk = wrkstn
						y tgfdte = Hoy
						y TGhtme = HoraN6
						y TGK01	 = 'BR'
						y tg6001.tgk10 ='S' o 'N'  

3- Se calcula si saldo pendiente de recepción

   Saldo = total_alta_pp + total_alta_tg - total_recibido_pp - total_recibido_tg + total_anulado_pp + total_anulado_tg

4- Si el resultado del punto 3 es mayor a cero se debe grabar en TG del reporte para que salga impreso con el importe del saldo
	Si saldo > 0
		//imprimir en el reporte con el valor obtenido en punto 3
	Finsi

**Comment by axel-miller** [comment]
Se remiten los cambios

**Comment by rscocco** [comment]
Ya está disponible en Filmoweb  de ALFA

**Comment by vivikorz** [comment]
Tomo testing en desarrollo

**Comment by vivikorz** [comment]
Tomados los datos de produccion.
Realicé ok operativo setiembre
Tire cierre definitivo
Adjunto los reportes x exhibir tanto pdf como csv. Se ven correctos. Solo sale la parte de canje o sea lo que no corresponde a CFM ya que el usuario no considera que en este reporte deban estar incluidos.

[VKORZ_Por_Exhibir_2021928_679919.pdf](https://github.com/SistemasArtear/Filmoteca/files/7246978/VKORZ_Por_Exhibir_2021928_679919.pdf)

[VKORZ_Por_Exhibir_2109.csv](https://github.com/SistemasArtear/Filmoteca/files/7246977/VKORZ_Por_Exhibir_2109.csv)
](url)
OK DESARROLLO. PIDO PASAJE A INTEGRACION
@sisva @axel-miller @MBESCUDERO @rscocco @yoea13

**Comment by rscocco** [comment]
Ya está disponible en Filmoweb de  INTEGRACION

**Comment by vivikorz** [comment]
Corro PRECIERRE en producccion
Copio datos a integracion
Comparo

**Comment by rscocco** [comment]
Ya esta disponible en Filmoweb de Preproduccion.

**Comment by vivikorz** [comment]
tomo preprod

**Comment by vivikorz** [comment]
[VKORZ_Por_Exhibir_2109 (2).csv](https://github.com/SistemasArtear/Filmoteca/files/7254054/VKORZ_Por_Exhibir_2109.2.csv)
[VKORZ_Por_Exhibir_2021929_018405.pdf](https://github.com/SistemasArtear/Filmoteca/files/7254055/VKORZ_Por_Exhibir_2021929_018405.pdf)
Copiado datos de produccion en preprod
Corri cierre defintivo ya que es necesario para generar el pdf y  csv.
Ya no estan las EF a futuro. Solo estan en los reportes por exhibir los capitulos recibidos y no exhibidos
OK PREPROD
Pasara a prod con todo el release
@MBESCUDERO @axel-miller @sisva @yoea13 @rscocco

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53672&

**Comment by rscocco** [comment]
Se implementa en servidores **Gxproductivo** el proyecto **Filmoweb.war.** 

Según solicitud :   **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=53672**
