### ISSUE TITLE
Implementacion

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#79]
Se implementaran:
Issue 64 que tiene un componente java y un pl 
Issue 55 su componente es pl

Los tag estan mencionados en los issues corroborar con @vilinares @rodrigo-fernandez

**Comment by rscocco** [comment]
Por git:  **https://github.com/SistemasArtear/Filmoteca/issues/55**

Se implementa en la base preproductiva de Oracle los documentos descargados de :  **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-10-21)%20%2355** y registrados con el TAG PL :    **TAG_FILMO_20211021_1-14_PL**

Detalle de Ejecución:
Package FIL_PKG_ARMADO_PROGRAMACION compilado
Package body FIL_PKG_ARMADO_PROGRAMACION compilado
Package FIL_PKG_DESCONFIRMAR_PROG compilado
Package body FIL_PKG_DESCONFIRMAR_PROG compilado
Package FIL_PKG_FP320 compilado
Package body FIL_PKG_FP320 compilado
Package FIL_PKG_FP370 compilado
Package body FIL_PKG_FP370 compilado

**Comment by vilinares** [comment]
Se agregaron unos permisos para solucionar el problema en la implementación en el Issue #55, por favor agregar para el pasaje el script 00

**Comment by rscocco** [comment]
Se implementa en la base preproductiva de Oracle los documentos descargados de : https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2021-10-21)%20%2355 y registrados con el TAG PL : TAG_FILMO_20211021_1-14_PL

Se agregarin los grants de SGV  para FILMO en Preprod
