### ISSUE TITLE
Validador Contratos - Diferencia entre importe de titulos y grupo

### ISSUE THREAD

**Issue by MBESCUDERO** [SistemasArtear/Filmoteca#80]
El validador de contrato debería haber informado diferencia de importe entre titulos y grupo de contrato 2439, señal M24, para los 10 grupos que son con cargo.
La validación correcta es:
- Si el tipo de titulo es 'CC' , el valor de TN6001.tnnimpuni debe ser igual al GR6001.grnimpgru para el cokcon,grkgrupo y snkcod , siempre que el TNmestado sea 'A'
- Si el tipo de titulo es 'SC',  la sumatoria del TN6001.tnnimpuni debe ser igual al GR6001.grnimpgru para el cokcon, grkgrupo, snkcod, siempre que el TNmestado sea 'A'

El validador es FIL_PKG_CONTRATOS.PR_VALIDARCONTRATO

Por favor antes de realizar corrección contarnos el motivo por el que no detecta el caso reportado.

**Comment by vilinares** [comment]
Se realizo ajuste solicitado en ambiente de desarrollo

**Comment by vivikorz** [comment]
Ejecuté en desarrollo: 
BEGIN
    -- Call
    FILMO.CRON_VALIDADOR_CONTRATOS;
    -- Transaction control
    COMMIT;
END;

Al ejecutr me salio el siguiente error:
Error que empieza en la línea: 1 del comando :
BEGIN
    -- Call
    FILMO.CRON_VALIDADOR_CONTRATOS;
    -- Transaction control
    COMMIT;
END;
Informe de error -
ORA-20001: ORA-20001: ORA-06502: PL/SQL: error : character string buffer too small numérico o de valor
ORA-06512: en "FILMO.PKG_MAIL", línea 244
ORA-06512: en "FILMO.CRON_VALIDADOR_CONTRATOS", línea 8
ORA-06512: en línea 3 

Ya lo está viendo @vilinares 
@MBESCUDERO @sisva

**Comment by vilinares** [comment]
Revisando detecte que el query seguía arrojando datos erróneos, cambie la manera a algo mas sencillo como lo indico Mabel en la solicitud y funciono. Se le pasaron los contratos que quedaron con diferencia a Viviana para su revisión.

**Comment by vivikorz** [comment]
Contrato 2359 tiene mal el importe de alta de contrato en pp6003, correcto en pp6002/6001 en ifz 214 .
select *from pp6001 where ppkpro = 38563 and snkcod = 'M24' AND IFKINT = 214;
select *from pp6002 where ppkpro = 38563 and snkcod = 'M24' AND IFKINT = 214;
select *from pp6003 where ppkpro = 38563 and snkcod = 'M24' AND IFKINT = 214;

**Comment by vivikorz** [comment]
nd Copy To: 
 Subject: DESESTIMAR TEST ALFA - FILMOTECA: ERROR en Validacion de Contratos
  
 Cuerpo del Mail:  
 &envio.Text: Se ha realizado la validaciÃ³n de los contratos y se encontraron los siguientes resultados:

Contrato 1847 - SeÃ±al M24 - Grupo  1 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 1944 - SeÃ±al C13 - Grupo  1 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2038 - SeÃ±al C13 - Grupo  1 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2056 - SeÃ±al M24 - Grupo  2 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2157 - SeÃ±al M24 - Grupo  1 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2206 - SeÃ±al M24 - Grupo  1 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2296 - SeÃ±al M24 - Grupo  1 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2359 - SeÃ±al M24 - Grupo  1 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2359 - SeÃ±al M24 - Grupo  2 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2359 - SeÃ±al M24 - Grupo  3 - Los importes de los titulos deben coincidir con el importe de cada grupo;
 &envio.HTMLText:
___________________________________________________]
15 Mar 2022 16:26:06,929 DEBUG rrw1422   [VKORZ--&menssmtp.Login]
15 Mar 2022 16:26:06,929 DEBUG rrw1422   [VKORZ--3333333 &errrcode    0]
15 Mar 2022 16:26:06,929 DEBUG rrw1422   [VKORZ--1 &menssmtp.Send]
15 Mar 2022 16:26:06,929 DEBUG rrw1422   [VKORZ--&unHost:SIN_SALIDA_DE.ARTEAR &unPuerto: 25 &errrcode:         0 &errrdesc:]
15 Mar 2022 16:26:06,929 DEBUG rrw1422   [VKORZ--]
15 Mar 2022 16:26:06,929 DEBUG rrw1422   [VKORZ--Fin]
15 Mar 2022 16:26:06,929 INFO  aenviamail [VKORZ--Fin &xmlrespuesta:OK Mail enviado satisfactoriamente]

**Comment by vivikorz** [comment]
Copiado en desarrollo los datos de produccion. No hubo otros contratos con problemas. Lo que voy a hacer es pasar a integracion pero además lo que hay que hacer es dejar los contratos en correcto estado ya que sino va a frenar el cierre

**Comment by vivikorz** [comment]
BEGIN
-- Call
FILMO.CRON_VALIDADOR_CONTRATOS;
-- COMMIT
end;

**Comment by vivikorz** [comment]
Tomo prueba en integracion

**Comment by vivikorz** [comment]
Copie datos en integracion y corro abriendo el sql 
BEGIN
-- Call
FILMO.CRON_VALIDADOR_CONTRATOS;
-- COMMIT
end;

**Comment by vivikorz** [comment]
http://gxint.artear:82/logs/consumidores_int.log
___________________________________________________
 Enviado desde: Viviana_C_Korz@artear.com
 Enviado por: Viviana_C_Korz@artear.com
 Send To:  Viviana_C_Korz@artear.com
 Copy To:  Ariel_H_Villegas@artear.com
 Blind Copy To:  Mabel_B_Escudero@artear.com
 Subject: DESESTIMAR TEST BETA - FILMOTECA: ERROR en Validacion de Contratos
  
 Cuerpo del Mail:  
 &envio.Text: Se ha realizado la validaciÃ³n de los contratos y se encontraron los siguientes resultados:

Contrato 1847 - SeÃ±al M24 - Grupo  1 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 1944 - SeÃ±al C13 - Grupo  1 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2038 - SeÃ±al C13 - Grupo  1 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2056 - SeÃ±al M24 - Grupo  2 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2157 - SeÃ±al M24 - Grupo  1 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2206 - SeÃ±al M24 - Grupo  1 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2296 - SeÃ±al M24 - Grupo  1 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2359 - SeÃ±al M24 - Grupo  1 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2359 - SeÃ±al M24 - Grupo  2 - Los importes de los titulos deben coincidir con el importe de cada grupo;
Contrato 2359 - SeÃ±al M24 - Grupo  3 - Los importes de los titulos deben coincidir con el importe de cada grupo;
 &envio.HTMLText:
___________________________________________________]
17 Mar 2022 08:56:04,689 DEBUG rrw1422   [VKORZ--&menssmtp.Login]
17 Mar 2022 08:56:04,689 DEBUG rrw1422   [VKORZ--3333333 &errrcode    0]
17 Mar 2022 08:56:04,689 DEBUG rrw1422   [VKORZ--1 &menssmtp.Send]
17 Mar 2022 08:56:04,689 DEBUG rrw1422   [VKORZ--&unHost:SIN_SALIDA_DE.ARTEAR &unPuerto: 25 &errrcode:         0 &errrdesc:]
17 Mar 2022 08:56:04,689 DEBUG rrw1422   [VKORZ--]
17 Mar 2022 08:56:04,689 DEBUG rrw1422   [VKORZ--Fin]
17 Mar 2022 08:56:04,689 INFO  aenviamail [VKORZ--Fin &xmlrespuesta:OK Mail enviado satisfactoriamente]

**Comment by vivikorz** [comment]
Para dejar los contratas correctos en TN6001 SE REALIZA LO SIGUIENTE:
UPDATE TN6001 SET TNNIMPUNI = '8800' WHERE cokcon = 2359 and grkgrupo = 1;
UPDATE TN6001 SET TNNIMPUNI = '8800' WHERE cokcon = 2359 and grkgrupo = 2;
UPDATE TN6001 SET TNNIMPUNI = '8400' WHERE cokcon = 2359 and grkgrupo = 3;

UPDATE TN6001 SET TNNIMPUNI = '87500' WHERE cokcon = 2296 and grkgrupo = 1;

UPDATE TN6001 SET TNNIMPUNI = '84800' WHERE cokcon = 2206 and grkgrupo = 1;

UPDATE TN6001 SET TNNIMPUNI = '112800' WHERE cokcon = 2157 and grkgrupo = 1;
UPDATE TN6001 SET TNNIMPUNI = '1400' WHERE cokcon = 2056 and grkgrupo = 2;
UPDATE TN6001 SET TNNIMPUNI = '554580' WHERE cokcon = 2038 and grkgrupo = 1 and snkcod = 'C13';.
Vuelvo a correr el pl validador

**Comment by vilinares** [comment]
Se creo TAG_FILMO_20220317_1-15_PL para su pasaje a Preprod

**Comment by rscocco** [comment]
Se implementa en la base oracle de preprod el documento descargado de :  **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2022-03-17)%20%2380**  
y registrado con el TAG : PL :   **TAG_FILMO_20220317_1-15_PL**

Detalle de  Ejecución :  
Package FIL_PKG_CONTRATOS compilado
Package body FIL_PKG_CONTRATOS compilado

**Comment by vivikorz** [comment]
Copio datos en preprod. Tomo prueba de validador en preprod

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=54463
@vilinares @rscocco @MBESCUDERO @sisva @yoea13

**Comment by rscocco** [comment]
El DBA implemento en la base oracle de Productiva el documento descargado de : **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2022-03-17)%20%2380**
y registrado con el TAG PL : **TAG_FILMO_20220317_1-15_PL**

Según solicitud :   **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=54463**

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=54463 Implentado
