### ISSUE TITLE
Crear Sinónimos para las tablas de Filmo

### ISSUE THREAD

**Issue by dieroch** [SistemasArtear/Filmoteca#81]
Se pide crear un sinónimo a las tablas del esquema Filmo, según lo definido en la planilla anexa. Aclaro los sinónimos deben crearse sólo dentro del esquema Filmo, no para usar desde GSGV. 

[Filmo - Sinonimos para las Tablas en uso.ods](https://github.com/SistemasArtear/Filmoteca/files/8384090/Filmo.-.Sinonimos.para.las.Tablas.en.uso.ods)

En el EA se creó un DER dentro del proyecto Fimoteca usando estos sinónimos, buscar el package: FIL.DER.Sistema Actual 2021.

**Comment by vilinares** [comment]
Se crearon los sinónimos en ambiente de desarrollo

**Comment by caarlosalfano** [comment]
Las pruebas en Desarrollo están O.K.

![imagen](https://user-images.githubusercontent.com/68925602/161322503-c3fe3f62-c1ce-40ef-a2c4-1f92993eafc7.png)

**Comment by caarlosalfano** [comment]
Por favor hacer el pasaje a Integración. Gracias!

**Comment by vilinares** [comment]
Se realizo pasaje a Integración

**Comment by caarlosalfano** [comment]
Las pruebas en Integración están O.K. 

![imagen](https://user-images.githubusercontent.com/68925602/161337229-9ac9dc75-baca-4f3e-baa1-2b14934bd63c.png)

**Comment by caarlosalfano** [comment]
Por favor hacer el pasaje a PreProducción. Gracias!

**Comment by rscocco** [comment]
Ser implementa en la base **Oracle preprod** los codumentos descargados de ;   **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2022-04-04)%20%2381**
 y registrado con el TAG PL :    **TAG_FILMO_20220404_HOTFIX_PL**

Detalle de ejecución: 
Synonym FILMO.AMORTIZACIONTIPO creado.
Synonym FILMO.AMORTIZACIONSENIAL creado.
Synonym FILMO.CALIFICACIONARTISTICA creado.
Synonym FILMO.TIPOMOVCTACONTABLE creado.
Synonym FILMO.CTACONTABLE creado.
Synonym FILMO.CALIFICACIONCOMERCIAL creado.
Synonym FILMO.CHEQUEOTECNICO creado.
Synonym FILMO.CALIFICACIONMORAL creado.
Synonym FILMO.CONTRATO creado.
Synonym FILMO.AMORTIZACIONPORCPASADA creado.
Synonym FILMO.CONTRATOSENIAL creado.
Synonym FILMO.AMORTIZACIONPORCCUOTA creado.
Synonym FILMO.DIFERENCIAINTERFAZSENIAL creado.
Synonym FILMO.DERECHOTERRITORIAL creado.
Synonym FILMO.TITULOCAPITULOACTOR creado.
Synonym FILMO.FICHAACTOR creado.
Synonym FILMO.FICHACINEMATOGRAFICA creado.
Synonym FILMO.FICHAEMISION creado.
Synonym FILMO.FICHAEMISIONSENIAL creado.
Synonym FILMO.FICHAEMISIONCAPITULO creado.
Synonym FILMO.FICHAEMISIONROLLO creado.
Synonym FILMO.FICHASINOPSIS creado.
Synonym FILMO.PRGRMCIONCONTRATOCANDIDATO creado.
Synonym FILMO.GENERO creado.
Synonym FILMO.GRUPO creado.
Synonym FILMO.PRGRMCIONEXHIBICONFIRMADA creado.
Synonym FILMO.REMITOTITULOCONTRATOHIST creado.
Synonym FILMO.PRGRMCIONHISTCONFIRMACION creado.
Synonym FILMO.GRUPOSENIALHEREDAHIST creado.
Synonym FILMO.GRUPOTITULOHIST creado.
Synonym FILMO.CONTRATOHIST creado.
Synonym FILMO.GRUPOCAPITULOHIST creado.
Synonym FILMO.GRUPOHIST creado.
Synonym FILMO.CONTRATOSENIALHIST creado.
Synonym FILMO.GRUPOTITULOSENIALHEREDAHIST creado.
Synonym FILMO.INTERFAZCIERRE creado.
Synonym FILMO.INTERFAZCIERRESEÑAL creado.
Synonym FILMO.CALIFICACIONAUTOCONTROL creado.
Synonym FILMO.TIPOMOVMATERIAL creado.
Synonym FILMO.TITULO creado.
Synonym FILMO.CHEQUEOTECNICOOBSERV creado.
Synonym FILMO.CONTRATOOBSERV creado.
Synonym FILMO.TITULOACTOR creado.
Synonym FILMO.PROGRAMAHORARIOEMISION creado.
Synonym FILMO.CIERRECONTABLEPROVEEDORES creado.
Synonym FILMO.CIERRECONTABLECONTRATOS creado.
Synonym FILMO.CIERRECONTABLETITULOS creado.
Synonym FILMO.PROVEEDOR creado.
Synonym FILMO.PROCESOBLOQUEADO creado.
Synonym FILMO.PARAMETRO creado.
Synonym FILMO.GRUPOTITULOPAYTV creado.
Synonym FILMO.REMITOTITULOCONTRATO creado.
Synonym FILMO.REMITOTITULO creado.
Synonym FILMO.GRUPOTITULORERUNOBSERV creado.
Synonym FILMO.REMITO creado.
Synonym FILMO.CHEQUEOTECNICOSENIAL creado.
Synonym FILMO.SENIALHEREDA creado.
Synonym FILMO.CHEQUEOTECNICOPARTESEG creado.
Synonym FILMO.GRUPOSENIALHEREDA creado.
Synonym FILMO.GRUPOTITULOSENIALHEREDA creado.
Synonym FILMO.TIPOCONTRATO creado.
Synonym FILMO.TIPOCOMIENZODERECHOS creado.
Synonym FILMO.TIPOIMPORTE creado.
Synonym FILMO.TITULOCAPITULOCOPIA creado.
Synonym FILMO.TITULOCOPIA creado.
Synonym FILMO.TIPOMODIFICACIONVIGENCIA creado.
Synonym FILMO.GRUPOTITULO creado.
Synonym FILMO.TITULOCAPITULO creado.
Synonym FILMO.TOLERANCIAPERMITIDA creado.
Synonym FILMO.GRUPOCAPITULO creado.
Synonym FILMO.TITULOSINOPSIS creado.
Synonym FILMO.TIPOTITULO creado.
Synonym FILMO.TIPOMOVCONTABLE creado.
Synonym FILMO.COTIZACIONDOLAR creado.
Synonym FILMO.VALORLIBRERIA creado.

**Comment by caarlosalfano** [comment]
Las pruebas en PreProducción están O.K.

![image](https://user-images.githubusercontent.com/68925602/161828167-436a5c18-127d-45eb-bb54-4b060583b7e2.png)

**Comment by dieroch** [comment]
Se pide pasaje a Prod en https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=54560
