### ISSUE TITLE
Alta de Contrato -  Titulos Con Capitulos - Recontratacion

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#83]
Informa el usuario que en el caso de contratos de la familia de los concapitulos recontratacion no graba bien el importe unitario en la tabla TN6001

Ejemplo proveedor Trinity señal M24, "Cafe con aroma de mujer" existe en otro contrato anterior 

En mi prueba de preprod rescato del log SELECT *FROM LOGsfilmoteca where logCLAVE like '%2458%';
 
COKCON=2458*GRKGRUPO=1*SNKCOD=M24*TTKTPOTIT=SU*MTKNROTIT=10251*TDKTPODER=F*DTKDERTER=6 *AMKIDAMO=58*AMKIDAMO2=0*TNMSTDBY=N*TNNCNTPAS=159*TNNPASPEN=0*TNNCNTTIE=0*TNMUNITIE= *TNMMARPER=S*TNFCOMDER=01-04-2022 00:00:00*TNNCNTTRE=1*TNFFECPEN=01-01-0001 00:00:00*TNMAUTAUT= *TNMPASLIB=N*TNFCOMLIB=01-01-0001 00:00:00*TNMTITCON=N*TNDOBSER=                                        *TNFFCHDRE=01-04-2022 00:00:00*TNFFCHHRE=01-01-0001 00:00:00*TNMTOTAMO=N*TNMRECMAT=N*TNNNUMANT=0*TNNNUMPOS=0*TNMCNTEXH=N*TNMTOTALI=N*TNMESTADO=A*TNMAJUCAM=N*TNMRECTRAT=S*TNNCNTEXC=0*TNNUNEXC= *TNMPAARG= *TNMCOPIA=N*TNUUSRING=VKORZ     *TNTFYHING=21-04-2022 12:18:53*TNUUSRMOD=          *TNTFYHMOD=01-01-0001 00:00:00*TNMCNTLIB=N*TNNIMPUNI=200*TNNGRUANT=0*TNNGRUPOS=0*TNMAMOSIE=N*TNMCNTSIE=N* 

Se puede ver en este log como le envia en el insert tnnimpuni = 200 y deberia haber enviado  GRNIMPGRUP = 31800 YA QUE EL GRUPO TENIA 159 ORIGINALES CADA UNO A 200 PERO AL TRATARSE DE CONCA DEBE ENVIAR EL IMPORTE DEL GRUPO

En carga de grupos no recoentratacion  envia bien.

**Comment by vilinares** [comment]
Se realizo la modificación en ambiente de desarrollo

**Comment by vivikorz** [comment]
Prueba reportada por el usuario:
Grabo en desarrollo prov.38563 
Su 10251 Cafe con Aroma de mujer. 159 ORIGINALES, 0 REPETECIONES - Repeticion y Recontratacion - NO perpetuo
31800 cada capitulo valor 200. 
Grabo en TN6001.TNNIMPUNI = 31800 OK
HN6001.HNNIMPUNI = 31800 OK
GR6001.GRIMPGRU = 31.800 y GR6001.GRINIMPUNI   = 200 OK
@vilinares

**Comment by vilinares** [comment]
Se realizo pasaje a Integración

**Comment by vivikorz** [comment]
Detalle de la prueba en integracion
1- Cargo contrato proveedor FILMIC para M24 con Titulo Cafe con  Aroma a Mujer con 4 originales y 4 repeticiones, Repeticion con Recontratacion
Se generó el contrato 2461grabó en TN6001 en  TN6001.TNNIMPUNI  = 2000 importe cargado en GR6001.GRIMPGRU Eso es correcto en HN6001.hnnimpuni = 2000 
2- Tomo el contrato 2455 que es del proveedor Trinity agrego grupo familia ingals SU10298 es repeticion con recontratacion carga correctamente el importe unitario en TN6001 y en HN6001.

**Comment by vivikorz** [comment]
(se pasará con los issues 38 y 39 - Clonador) ya que en prueba integral de clonacion incluye esta prueba a pesar de que no son los mismos objetos

**Comment by vivikorz** [comment]
[NuevosContratos.pdf](https://github.com/SistemasArtear/Filmoteca/files/8669371/NuevosContratos.pdf)

**Comment by vivikorz** [comment]
En integracion he probado y note que para prueba integral en TN6001 al dar de alta un contrato con titulo CC Repeticion - No Recontratacion cuya fecha de comienzo de derechos es por Fecha de contrato, o sea el usuario no la carga, el sistema debe tomar la fecha del CO6001 y grabarla en TN6001.TNFFCHDRE SUMARLE  TN6001.TNNCNTTIE Y CON ESO GRABAR TNFFCHHRE.
No lo está haciendo correctamente, deja en bco.
Reporto error a @vilinares e informa que sql utilizado es: 
BEGIN
                  SELECT 1
                    INTO l_existe
                    FROM rm6001 rm, rt6001 rt, gr6001 gr
                   WHERE rm.rtkidrem   = rt.rtkidrem
                     AND cokcon        = p_contrato
                     AND grkgrupo      = p_grupo
                     AND snkcod        = p_senial
                     AND ttktpotit     = SubStr (p_clave, 1, 2)
                     AND mtknrotit     = SubStr (p_clave, 3, 6)
                     AND ROWNUM        <= gr.grncntori
                   ORDER BY rm.rmknumcap, rm.rmknumpart;
               EXCEPTION
                  WHEN NO_DATA_FOUND THEN
                     l_existe := 0;
                  WHEN TOO_MANY_ROWS THEN
                     l_existe := 1;
               END;
               -- por pedidod de xxx se agrega el calculo de la fecha hasta
               --para los tipos de derechos 'C','F'
               IF l_existe = 0 THEN
                  CASE p_idTpoDer
                     WHEN 'C' THEN
                        SELECT coffchco
                        INTO l_desdeTit
                        FROM co6001
                        WHERE cokCon = p_contrato;
                     WHEN 'F' THEN
                        l_desdeTit := reg.grfcomder;
                     WHEN 'R' THEN
                        NULL;
                  END CASE;
               END IF;            END IF;--            l_desdeTit := l_nuevoComienzo;
            -- Si se actualizo la fecha Desde Real
            SELECT Decode (p_marPerm, 'S', k_fechaCero, Decode (reg.grmunitie, 'D', l_desdeTit + reg.grncnttie, Add_Months (l_desdeTit, reg.grncnttie * Decode (reg.grmunitie, 'A', 12, 1))))
              INTO l_hastaTit
              FROM dual;
Le pido que agregue al if que p_proveedor coincida con RT.PRKPRO ya QUE ESTARIA DEJANDO MAL LOS DATOS X QUE ES EL TIPICO REGISTRO QUE DEJA MARCA DE CONSULTAR EN S = TNMTITCON

**Comment by vivikorz** [comment]
SU 10298 PROVEEDOR VIEJO TRINITY LA FAMILIA ING. CTO.2439
Cargo lo mismo en otro contrato como repeticion Y RECONTRATACION con proveedor TRINITY
RERUN
Grabo contrato 2465 con TNNIMPUNI = 22.000 QUE ES IGUAL AL IMPORTE GRUPO

**Comment by vivikorz** [comment]
REALIZADO CIERRE DEFINITIVO - Pp6003
       select *from pp6003 where ifkint = 231 AND PPKCON = 2465;

**Comment by vilinares** [comment]
Se crea TAG_FILMO_20220513_1-7_1-15-1_PL para su pasaje a Preprod

**Comment by vivikorz** [comment]
SU 10298 PROVEEDOR VIEJO TRINITY LA FAMILIA ING. CTO.2439
Cargo lo mismo en otro contrato como repeticion Y RECONTRATACION con proveedor TRINITY
RERUN
Grabo contrato 2465 con TNNIMPUNI = 220.000 QUE ES IGUAL AL IMPORTE GRUPO
hn6001 ok grabado importe unitario del titulo = al del grupo

select *from tn6001 where mtknrotit = 10298 and ttktpotit = 'SU';

SELECT *fROM HN6001 WHERE HOKCON = 2464;

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=54822
@rscocco @vilinares @sisva @rodrigo-fernandez @MBESCUDERO

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=54822& prod
