### ISSUE TITLE
PreCierre y Cierre Contable

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#84]
Está perdiendo el mes de proceso y toma el mes anterior. Tanto en titulos de reporte como en la grabacion de los pp's repitiendo le nro.de ifz del mes  anterior. 
Se sospecha que es por alguna rutina de titulos con costeo especial (cfm)

**Comment by MBESCUDERO** [comment]
Se pasa la corrección para su deploy

**Comment by rscocco** [comment]
Ya esta disponible en Filmo de ALFA

**Comment by vivikorz** [comment]
Contrato 2442 Se cargo como No canje en marzo y en abril pasaron a canje.
Borrando solo el grupo 1 y volviendo a cargar el titulo SE10892 CTO.2442 en grupo 2

**Comment by rscocco** [comment]
Ya está disponible en filmoweb de integracion

**Comment by vivikorz** [comment]
Detalle de testing en integración:
1- Con los datos copiados de produccion tiro precierre.

**Comment by vivikorz** [comment]
Prueba en preprod. Copiados los datos de produccion.
Realizado el precierre de abril,
Se ven los reportes correctos y los saldos de canal 13 correctos porque  está tomando correctamente el saldo final de marzo como inicial de abril. (ANTES de la correcion volvia a tomar como saldo inicial de abril el saldo de febrero, como que marzo no se hubiera procesado.
[VKORZ_Por_Recibir_2022426_784944.pdf](https://github.com/SistemasArtear/Filmoteca/files/8565828/VKORZ_Por_Recibir_2022426_784944.pdf)
[VKORZ_Por_Exhibir_2022426_784944.pdf](https://github.com/SistemasArtear/Filmoteca/files/8565829/VKORZ_Por_Exhibir_2022426_784944.pdf)
[VKORZ_Resumen_Mov_2022426_784944.pdf](https://github.com/SistemasArtear/Filmoteca/files/8565830/VKORZ_Resumen_Mov_2022426_784944.pdf)
)

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=54656
@rscocco @MBESCUDERO @sisva

**Comment by rscocco** [comment]
Se implemento en servidore **gxproductivo** contexto **filmoweb.war**
Según solicitud :  **https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=54656**
