### ISSUE TITLE
Correccion de contratos informados en el validador 

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#86]
Para correr el validador es necesario ejecutar: 
BEGIN
-- Call
FILMO.CRON_VALIDADOR_CONTRATOS;
-- COMMIT
end;
ver el mensaje en: http://gx"xx".artear:82/logs/consumidores_int.log 

Correr las siguientes sentencias: 
UPDATE TN6001 SET TNNIMPUNI = '8800' WHERE cokcon = 2359 and grkgrupo = 1;
UPDATE hN6001 SET HNNIMPUNI = '8800' WHERE hokcon = 2359 and hrkgrupo = 1;

UPDATE TN6001 SET TNNIMPUNI = '8800' WHERE cokcon = 2359 and grkgrupo = 2;
UPDATE hN6001 SET HNNIMPUNI = '8800' WHERE hokcon = 2359 and hrkgrupo = 2;

UPDATE TN6001 SET TNNIMPUNI = '8400' WHERE cokcon = 2359 and grkgrupo = 3;
UPDATE hN6001 SET HNNIMPUNI = '8400' WHERE hokcon = 2359 and hrkgrupo = 3;

UPDATE TN6001 SET TNNIMPUNI = '87500' WHERE cokcon = 2296 and grkgrupo = 1;
UPDATE hN6001 SET HNNIMPUNI = '87500' WHERE hokcon = 2296 and hrkgrupo = 1;

UPDATE TN6001 SET TNNIMPUNI = '84800' WHERE cokcon = 2206 and grkgrupo = 1;
UPDATE hN6001 SET HNNIMPUNI = '84800' WHERE hokcon = 2206 and hrkgrupo = 1;

UPDATE TN6001 SET TNNIMPUNI = '112800' WHERE cokcon = 2157 and grkgrupo = 1;
UPDATE hN6001 SET HNNIMPUNI = '112800' WHERE hokcon = 2157 and hrkgrupo = 1;

UPDATE TN6001 SET TNNIMPUNI = '1400' WHERE cokcon = 2056 and grkgrupo = 2; 
UPDATE hN6001 SET HNNIMPUNI = '1400' WHERE hokcon = 2056 and hrkgrupo = 2;

UPDATE TN6001 SET TNNIMPUNI = '554580' WHERE cokcon = 2038 and grkgrupo = 1 and snkcod = 'C13';.
UPDATE hN6001 SET HNNIMPUNI = '554580' WHERE hokcon = 2038 and hrkgrupo = 1 and hrksnkcod = 'C13';

UPDATE TN6001 SET TNNIMPUNI = '23400' WHERE cokcon = 1944 and grkgrupo = 1 and snkcod = 'C13';
UPDATE hN6001 SET HNNIMPUNI = '23400' WHERE hokcon = 1944 and hrkgrupo = 1 and hrksnkcod = 'C13';

UPDATE  GR6001 SET GRNIMPGRU = '0', GRNIMPUNI = '0' WHERE GRKGRUPO = 1 AND COKCON = 1847;
UPDATE  HR6001 SET HRNIMPGRU = '0', HRNIMPUNI = '0' WHERE HRKGRUPO = 1 and hokcon = 1847;
UPDATE CO6001 SET CONIMPTOT = '2400' WHERE cokcon = 1847;
UPDATE  Ho6001 SET Honimptot = '2400'  WHERE  hokcon = 1847;
UPDATE CS6001 SET CSNMTOSN = '2400' WHERE cokcon = 1847;
UPDATE hS6001 SET hSNMTOSN = '2400' WHERE hokcon = 1847;
Vuelvo a correr el pl validador y deberian desaparecer dichos contratos del mail

**Comment by vivikorz** [comment]
Corri estos sql's
ejecuto el cron
Sale el sig.mensaje
28 Apr 2022 17:27:04,960 DEBUG rrw1422   [VKORZ--Sin Adjunto]
28 Apr 2022 17:27:04,960 DEBUG rrw1422   [VKORZ--
___________________________________________________
 Enviado desde: Viviana_C_Korz@artear.com
 Enviado por: Viviana_C_Korz@artear.com
 Send To:  Viviana_C_Korz@artear.com
 Copy To:  Ariel_H_Villegas@artear.com
 Blind Copy To: 
 Subject: DESESTIMAR TEST ALFA - FILMOTECA: ERROR en Validacion de Contratos
  
 Cuerpo del Mail:  
 &envio.Text: Se ha realizado la validaciÃ³n de los contratos y se encontraron los siguientes resultados:

Contrato 1847 - SeÃ±al M24 - Grupo  1 - Los importes de los titulos deben coincidir con el importe de cada grupo;
 &envio.HTMLText:


Por lo tanto me queda por ver que sucede con el cto.1847 que titulo en especial no esta correcto.
Pero los sql's anteriores descriptos  estan ok

**Comment by vivikorz** [comment]
UPDATE  GR6001 SET GRNIMPGRU = '0', GRNIMPUNI = '0' WHERE GRKGRUPO = 1 AND COKCON = 1847;

**Comment by MBESCUDERO** [comment]
Detallo a continuación las sentencias a ejecutar para dejar consistentes el archivo PP6003:
INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, TTKTPOTIT, MTKNROTIT, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 8400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=2359 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A');

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, TTKTPOTIT, MTKNROTIT, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 8400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=2359 AND GRKGRUPO=2 AND SNKCOD='M24' AND TVKIDMOV='A');
    

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, TTKTPOTIT, MTKNROTIT, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 8018.18, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=2359 AND GRKGRUPO=3 AND SNKCOD='M24' AND TVKIDMOV='A');
    

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, TTKTPOTIT, MTKNROTIT, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 87500, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=2296 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A');
    

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, TTKTPOTIT, MTKNROTIT, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 84800, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=2206 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A');
    

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, TTKTPOTIT, MTKNROTIT, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 112800, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=2157 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A');
    

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, TTKTPOTIT, MTKNROTIT, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 1400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=2056 AND GRKGRUPO=2 AND SNKCOD='M24' AND TVKIDMOV='A');
    

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, TTKTPOTIT, MTKNROTIT, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 23400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1944 AND GRKGRUPO=1 AND SNKCOD='C13' AND TVKIDMOV='A');
    

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, TTKTPOTIT, MTKNROTIT, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);
    
INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 8072, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 10985, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 11280, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 11282, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 11698, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 11980, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12093, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12094, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);
    
INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12095, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12096, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12097, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12098, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12099, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);
    
INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12101, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12102, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);
    
INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12103, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12104, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12105, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12106, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12107, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);
    
INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12110, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12113, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12114, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12115, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);

INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12116, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);
    
INSERT INTO PP6003 (SELECT IFKINT, SNKCOD, PPKPRO, 'MA',PPKCON, GRKGRUPO, 'LM', 12117, TOKNROCAP, TOKPARTE,
    PPNNRODET, PPMTPOMDF, TOKSGTO, AMKIDAMO, 400, PPNNUMPAS, PPNNUMCUO, PPMESTAMOR, PPKTPOIMP, PPKPGKCOD, PPKGTKFECE, PPKSNKEXH,
    PPNDURMIN FROM PP6003 WHERE PPKCON=1847 AND GRKGRUPO=1 AND SNKCOD='M24' AND TVKIDMOV='A' AND TTKTPOTIT='LM' AND MTKNROTIT=8065);


​

**Comment by vivikorz** [comment]
Ejectuado en produccion 
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=54711

@sisva @MBESCUDERO
