### ISSUE TITLE
Implementacion   HOTFIX FILMO V1.15.1 y FILMOTECA V1.7 CLONADOR 

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#89]
Issues a implementar 
Alta de Contrato - Titulos Con Capitulos - Recontratacion #83
Clonador: Remito de titulo sin contrato #38 
Clonador Relaciona TituloRemito con Contrato #39 
@rodrigo-fernandez @vilinares Por favor detallar en este issue de implementacion todo lo que es necesario pasar a preprod de los issues mencionados anteriormente.
Y asignar a  @rscocco

**Comment by rscocco** [comment]
Se deploya **Filmo.war** en servidores **jbospreprod01 y 02** el Tag: **TAG_FILMOTECA_V1.7_20211217_1-7-25**


Se implementa en la Base Oracle preprod los documentos descargados de : **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2022-05-13)%20%2338%20-%2039%20-%2083**
y registrados con el TAg PL :   **TAG_FILMO_20220513_1-7_1-15-1_PL**

detalle de implementacion : 
Procedure PR_CLONAR_TIT_SC compilado
Procedure PR_CLONAR_TIT_CC compilado
Package FIL_PKG_ALTA_CONTRATOS_2 compilado
Package body FIL_PKG_ALTA_CONTRATOS_2 compilado
Package FIL_PKG_MODIF_CONTRATOS_2X compilado
Package body FIL_PKG_MODIF_CONTRATOS_2X compilado

**Comment by vilinares** [comment]
Se realizaron ajuste en el script 02, por favor actualizar en Preprod

**Comment by rscocco** [comment]
Se implementa en la Base Oracle preprod el  documento 02  descargados de : **https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2022-05-13)%20%2338%20-%2039%20-%2083**
y registrados con el TAg PL : **TAG_FILMO_20220513_1-7_1-15-1_PL**

Detalle de implementacion :
**Procedure PR_CLONAR_TIT_CC compilado**

**Comment by vivikorz** [comment]
Por favor @vilinares pasar el ultimo arreglo a preprod. Gracias

**Comment by vilinares** [comment]
Se agrego modificación al TAG por favor colocar en Preprod de nuevo el script 02

**Comment by vilinares** [comment]
Se implementa en la Base Oracle preprod el documento 02 descargados de : https://github.com/SistemasArtear/plsql/tree/master/FILMO/Pasajes/Pasaje%20(2022-05-13)%20%2338%20-%2039%20-%2083
y registrados con el TAg PL : TAG_FILMO_20220513_1-7_1-15-1_PL

Detalle de implementacion :
Procedure PR_CLONAR_TIT_CC compilado

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=54822
@rscocco @vilinares @rodrigo-fernandez @sisva @MBESCUDERO

**Comment by vivikorz** [comment]
https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=54822&
