### ISSUE TITLE
Consulta Titulo Vigente  

### ISSUE THREAD

**Issue by vivikorz** [SistemasArtear/Filmoteca#9]
El subfile queda cargado con 15 registros por página, es necesario tener más registros por página e indicar  cuántas "páginas" tiene la búsqueda.

**Comment by psarco-artear** [comment]
Se agrega filtro para seleccionar cantidad de registros cargados en el grid.
Se agrega totalizador de paginas del grid y numero de pagina actual. Se agrega funcionalidad: en caso de ser la primera pagina, se des habilita botón "anterior" y en caso de ser la última página se des habilita botón siguiente.
Modelo: FILMO
Objeto: HFCW12001 (UPD)

**Comment by rscocco** [comment]
Ya está disponible en Filmo Alfa

**Comment by vivikorz** [comment]
Probado en desarrollo y  rechazo porque la barra de desplazar no fue pedida y queda perdido el botón situar.
Y prefiero que la cantidad de registros a cargar quede arriba del botón situar.
Gracias

**Comment by psarco-artear** [comment]
Se corrige dimensión de la pantalla para que ajuste a la resolución correspondiente. Se probó en ambiente local con diferentes configuraciones de pantalla con resultados satisfactorios.

**Comment by psarco-artear** [comment]
Modelo: FILMO
Objeto: HFCW12001 (UPD)

**Comment by rscocco** [comment]
ya esta disponible en Filmo ALFA 
Objeto: HFCW12001

**Comment by vivikorz** [comment]
Probado en desarrollo con paralelo en produccion ya que tengo los mismos datos.
Probado para Canal A, C13, M24
Probado con busqueda por titulo orginal y por titulo castellano ok
Probado que coincida con el orden de aparicion tal cual produccion
Probado cantidad de páginas
OK DESARROLLO
´Pido pasaje a integracion con todo release

**Comment by rscocco** [comment]
ya esta disponible en Filmo INT
Objeto: HFCW12001

**Comment by vivikorz** [comment]
Probado en paraleleo con prod. Filtro de titulo castello y por nro.de calve-
Probado cantidad de páginas. ok
Pido pasaje  a preprod cuando se termine de probar todo el release en int

**Comment by vivikorz** [comment]
Probado para señal C13 TITULO ORIGINAL Y TITULO CASTELLANO QUE SEA EL GRAN ...OK COMPARADO CON PROD.
Probado para M24 titulo original LA y trajo 6 paginas controle el inicio y fin de cada pagina y coicidia con PROD.
Muestra nro.de paginas ok
pido pasaje a preprod cuando pase todo el release

**Comment by rscocco** [comment]
ya esta disponible en Filmo INT
Objeto: HFCW12001

**Comment by vivikorz** [comment]
oik preprod visto los filtros y cantidad de paginas
pasara a prod con todo el release

**Comment by rscocco** [comment]
Se implementa en servidores Gxprod el proyecto Filmo.war.

Según solicitud:    https://apps.canal13.artear.com.ar/glpi/front/ticket.form.php?id=52333
